### ISSUE TITLE
Median Spectrum Calculator

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#10071]
With the hybrid input model (with param e nonparam sources), when I put a breakpoint below this line (https://github.com/gem/oq-engine/blob/master/openquake/calculators/postproc/median_spectrum.py#L46) and look at cmaker.imtls I get a `KeyError`.

**Comment by micheles** [comment]
@mmpagani , can we close this issue?

**Comment by mmpagani** [comment]
We can close it but I think the problem still stands.
