### ISSUE TITLE
Explore the possibility of combining multiple gmfs.hdf5 files

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#10113]
Explore the possibility to combine multiple gmfs_files in event-based-risk calculations in the engine:

`gmfs_file = gmf-data_1.hdf5 gmf-data_2.hdf5 gmf-data_3.hdf5 ...`

The goal is to include the possibility to combine gmfs procured from different hazard models.

Some considerations:
-  gmf-data has the same investigation time
- files are considered independent (no need to consider possible double counting). In the future, that possibility could be added.

**Comment by micheles** [comment]
I am implementing it under the constraint that the sites and events are disjoint. Them the site collection is just the sum of the site collections, the event table is the sum of the events and the gmf_data table is the sum of the gm_data tables.
Notes:

- an error is raised if two sites overlap
- an error is raised if the gmf_data tables have different columns
- an error is raised if the gmf_data tables have different investigation_time
- an error is raised if the gmf_data tables have different effective_time
