### ISSUE TITLE
characteristicFaultSource with griddedSurface sometimes fails for gmpe with Rjb distances 

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#10197]
Discovered by @rcgee... In some cases, the source mesh created from a `characteristicFaultSource` with a `griddedSurface` becomes a 2D array instead of 1D array in the function [get_joyner_boore_distance](https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/geo/surface/gridded.py#L107), causing the calculation to fail. It is unclear how extensive this problem such as whether it applies to other source or surface typologies. So far, we get the error with the `event_based` calculator during computation of gmfs, and have not managed to reproduce it in classical mode. When I manually reduce the number of sites (e.g. by creating a new file), the error disappears after a certain amount of sites are discarded (say 1/100 are kept, filtered using awk). Instead, when the sites are reduced by sampling during the calculation (using `OQ_SAMPLE_SITES=0.01`), the error persists.

**Comment by mmpagani** [comment]
Thanks Kendra. Which model is generating this error?Sent from my iPhoneOn 6 Dec 2024, at 03:49, Kendra Johnson ***@***.***> wrote:﻿
Assigned #10197 to @mmpagani.

**Comment by micheles** [comment]
Interesting, I was not aware of this problem. Please ask Robin to send me a job.zip exhibiting the issue and I will fix it.

**Comment by kejohnso** [comment]
Whoops, I made the job but forgot to attach it.... 
[job.zip](https://github.com/user-attachments/files/18041456/job.zip)
