### ISSUE TITLE
The association query uses best_maximum_distance instead of asset_hazard_distance

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#1864]
This is a _huge_ mistake that has been there for years. It has been fixed by https://github.com/gem/oq-engine/pull/1921 but we still lack tests.

**Comment by raoanirudh** [comment]
The intended behaviour is as follows:

1.  The `region_constraint` is an optional parameter, applicable only to risk calculations, which defines the polygon that will be used for filtering the assets from the exposure model.

    The vertices of the polygon are listed in the Well-known text (WKT) format:
 `region_constraint = lon_1 lat_1, lon_2 lat_2, ..., lon_n lat_n`

    If the specified polygon is not already topologically closed (i.e., the last point is not the same as the first point), it should be closed during validation.

2. Asset filtering based on the `region_constraint`:

  * If the `region_constraint` **is not provided**, all assets in the exposure model are considered for the risk calculation.

  * If the `region_constraint` **is provided**, all assets in the exposure model located outside the polygon defined by the `region_constraint` are discarded; only those *assets within the polygon* are considered for the risk calculation.

3. The `asset_hazard_distance` is an optional parameter, applicable only to risk calculations, which defines a search radius (in km) that will be used for associating a hazard input site to each asset.

    If this parameter **is not provided**, a default value of *5 km* is used as the `asset_hazard_distance`.

    For each asset considered for the risk calculation (obtained after the filtering in Step 2):

    - If no hazard input site is found within the radius defined by the `asset_hazard_distance`, the asset is skipped and a message is provided mentioning the id of the asset that is affected by this issue. See note in the following comment regarding the handling of this case in an elegant manner.

    - If multiple hazard input sites are found within the radius defined by the `asset_hazard_distance`, the hazard input site with the shortest distance from the asset location is associated with the asset. It is acceptable for the associated hazard input site to be located outside the polygon defined by the `region_constraint`.
