### ISSUE TITLE
Datastore does not work well with WebUI

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#1870]
New calculators which are using the 'datastore' feature does not work well with the WebUI in a server/multiuser installation.

Since in a multiuser installation the WebUI process is not started by the end user that is actually running the computation, the datastore is written in the webserver process owner's homedir instead of the calculation user's home. In any case the datastore cannot be created on the users' home because lack of privileges.

When an end user tries to run a risk computation on top of a previously calculated hazard it will fails because it tries to find the datastore in the user's home, instead the data is stored in the WebUI process owner's home.

Calculation run through the WebUI should check for the datastore in the process owner's home and then in the user's home, even if this could break cross-compatibility with the command line: previously it was possible to run the hazard from the command line and then the risk from the WebUI and vv. This will be an issue also for exporting data: calculations done with the command line cannot be exported by the webui (if the home read permissions are owner-only) and vv (if the user is not the webserver's owner group). At this point probably we'll need to hide calculations done with different techniques (loosing very useful feature).

This has been marked as critical since the WebUI on Wilson (run by the 'openquake' user) will be used next week in the Risk workshop to run hazard + risk.

**Comment by daniviga** [comment]
The issue is slight different as supposed: the problem is not related with the ownership of the datastore (unless cli and webui are mixed), but on the gunicorn multi-processing.

If the WebUI is run with a single gunicorn process everything is working as expected. If more than one worker is used the risk computation fails with

```python
Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/openquake/engine/engine.py", line 218, in run_calc
    _do_run_calc(calculator, exports)
  File "/usr/local/openquake/oq-engine/openquake/engine/engine.py", line 254, in _do_run_calc
    calc.pre_execute()
  File "/usr/local/openquake/oq-risklib/openquake/calculators/scenario_risk.py", line 105, in pre_execute
    base.RiskCalculator.pre_execute(self)
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 451, in pre_execute
    HazardCalculator.pre_execute(self)
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 272, in pre_execute
    self.read_exposure_sitecol()
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 290, in read_exposure_sitecol
    self.gmfs = get_gmfs(self)
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 490, in get_gmfs
    gmf = calc.datastore['gmfs/col00'].value
  File "/usr/local/openquake/oq-risklib/openquake/commonlib/datastore.py", line 281, in __getitem__
    'No %r found in %s' % (key, [self, self.parent]))
KeyError: "No 'gmfs/col00' found in [, ]"
```

The error is not reproducible with the django internal serve since it's multi-thread but mono-process.

Running gunicorn in a single process mode has a big impact in the pre and post processing phase, when only the master process is running: only one core will be used.

**Comment by daniviga** [comment]
Another issue that could be related also to the oq-engine, but by definition is visible only on the webui, is that hdf5 files are not closed at the computation end.
On the oq-engine is less problematic since the master process exits as soon as the calculation ends (no persistent oq-engine process); the webui is in an infinite loop (persistent listening process) so its process exists only when the interface is restarted/stopped. This could bring to two issues: the number of open files will increase constantly, there could be a conflict with the same file open and accessed multiple times.

**Comment by micheles** [comment]
Closing the datastore is not a problem (see https://ci.openquake.org/job/zdevel_oq-engine/1479). On the other if gunicorn shares the file descriptors this is a big issue since HDF5 does not support access from multiple processes. That means that we have to rewrite the architecture of the engine server. For the risk workshop I strongly suggest not to use gunicorn but simply the django development server.

**Comment by daniviga** [comment]
Thanks @micheles. Currently I switched all the configurations to run Gunicorn in a single process mode. This works without any error. The only issue is that the pre and post processing phase are run on a single core. I'm pretty sure that your suspect is right and Gunicorn shares descriptors between workers. I will give Tornado a try, in any case I need to use WSGI otherwise we'll need to rewrite the application.

**Comment by daniviga** [comment]
In any case even with the 'datastore close' fix and the Django embedded server I see this kind of errors:

```python
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139906663831296:
  #000: ../../../src/H5O.c line 246 in H5Oopen(): unable to open object
    major: Symbol table
    minor: Can't open object
  #001: ../../../src/H5O.c line 1357 in H5O_open_name(): object not found
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../../src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'rlzs_assoc' doesn't exist
    major: Symbol table
    minor: Object not found
```

they are not breaking the computation, but maybe are related to the "Infinite loop closing".

**Comment by daniviga** [comment]
The multiple process error (not the error above, which does not affect the computation) seems to be solved by https://github.com/gem/oq-engine/pull/1872.
We'll keep the bug open to investigate more about these issues.
