### ISSUE TITLE
Update the documentation and the manual with new demos

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#1878]
The documentation and the manual (@raoanirudh) must be updated with the news demos and their new path (hazard and risk dirs).

We should also check that the documentation is consistent with the current path of the demos in both Ubuntu and RedHat.

Instruction about migration from NRMl 0.4 to 0.5 are missing.

**Comment by daniviga** [comment]
Also documentation about the WebUI is missing (doing it)

**Comment by micheles** [comment]
The docs about the migration are here: https://github.com/gem/oq-engine/blob/master/doc/engine/What's-new.md

Also Anirudh tells me that the manual is okay, so I am closing the issue.
