### ISSUE TITLE
Icebox: running risk on a specific hazard output is broken

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#1886]
It is broken for the event based risk calculator, but soon it will broken for all calculators if we do not implement the feature. However, rather than implementing the feature, it is best to remove the "Run risk" button. If there is a job_risk.ini file the risk should be computed for all outputs. Remember that 1) the Icebox is mean to be used for demo computations 2) the event based calculator is now so fast that we can run it on all outputs.

NB: if we use a single file for computing both hazard and risk (the recommended way) the problem disappear (the "Run Risk" button is not even displayed).

**Comment by micheles** [comment]
Alternative: we can keep "Run Risk". However, it should be necessary only to upload the risk files (job_risk.ini, risk models, exposure) not also the hazard files (in particular the source model, which can be quite large).

**Comment by daniviga** [comment]
It already works in that way. only the risk related files are needed.

**Comment by micheles** [comment]
After discussion with Vitor, it looks like this is not a problem. Vitor is actually in favor of removing icebox: he says that we do not want people to run large calculations and visualizations on the platform. Instead, they should run calculations on the Web UI. For the visualization they should use the risk modeler toolkit or a QGIS plugin.
