### ISSUE TITLE
webui: traceback isn't always displayed in the traceback window

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#1959]
in the WebUI the traceback froma  failed calculation is not always show in the "traceback" modal window. However it is possible to get it from the "console" window.

BAD:
![screenshot from 2016-02-22 16-26-23](https://cloud.githubusercontent.com/assets/1818657/13222634/21f2e834-d981-11e5-9a39-a0c53d726d32.png)

![screenshot from 2016-02-22 16-26-48](https://cloud.githubusercontent.com/assets/1818657/13222636/23166a42-d981-11e5-8add-c45948b18aee.png)

GOOD:

![screenshot from 2016-02-22 16-28-27](https://cloud.githubusercontent.com/assets/1818657/13222693/681450dc-d981-11e5-9253-ab71541bc96e.png)

![screenshot from 2016-02-22 16-28-06](https://cloud.githubusercontent.com/assets/1818657/13222684/5d71d820-d981-11e5-96b2-c5bff8e5dcd9.png)

**Comment by CatalinaYepes** [comment]
I'm also getting a similar problem:

![image001](https://cloud.githubusercontent.com/assets/6975363/14534852/468779ea-026b-11e6-9fd8-0da9a457737e.png)

but the terminal gives:
![screen shot 2016-04-14 at 18 03 38](https://cloud.githubusercontent.com/assets/6975363/14534888/6a532810-026b-11e6-86cf-115c7a427367.png)

**Comment by daniviga** [comment]
We didn't have any further feedback about this. I would close it and re-open if needed.
