### ISSUE TITLE
error with the export_dir when using the gui in the VM

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#1997]
By default users tend to specify the `export_dir` in the configuration file.

The following message appears, and it is difficult to identify the error because it is placed in the middle of the message (not at the end), so users have to scroll up and find the reason of the error.

![screen shot 2016-03-29 at 10 31 37](https://cloud.githubusercontent.com/assets/6975363/14102459/0a2e4870-f59b-11e5-8a5b-3a63e6624cb0.png)

After closing the error message window, the GUI shows like if the calculation is being executing, but with an empty console, and is not possible to read again the error message.

**Comment by daniviga** [comment]
The WebUI should always ignore the user defined `export_dir` and use the `TEMPDIR`
