### ISSUE TITLE
webui: the description is showing "A job" instead of the specified description

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#2001]
The description field in the webui is showing "A job" instead of the specified description in some cases.

See examples 
![screen shot 2016-04-14 at 18 06 54](https://cloud.githubusercontent.com/assets/6975363/14534960/b99119a0-026b-11e6-9983-16e9f0fda046.png)

**Comment by micheles** [comment]
This has been fixed in master a long time ago.
