### ISSUE TITLE
Useless WebUI in packages

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2066]
In the current configuration the WebUI installed by packages is almost useless, because it will not show calculation made by the users (the daemon is run by 'openquake') and any calculation run via the WebUI will be seen only through it (for the same reason). I see three solutions:

1. Do not start the WebUI automatically. If you want to use it in a proper way you have to follow the documentation ad configure django-pam or the django authentication
2. Start the WebUI and show all users calculation (no security). Anyway, any calculation run on the webui will be owned by openquake
3. Provide a WebUI configured with django auth enabled (with an admin account configured). The admin can create new users from the admin. Optionally the admin can add django-pam

I do NOT want to provide also django-pam: to make it work some changes must be done that could heavily affect security on the system (allow django to access `/etc/shadow`). I don't want to take these actions on behalf of other sysadmins/users.

Comments?

**Comment by daniviga** [comment]
I've changed the milestone. I think we need to address this issue before release 2.0: as a user I would expect to see my (or any) calculation when I open the WebUI otherwise I would consider it as a "bug".

**Comment by micheles** [comment]
The principle should be "make things easy for the naive user". So, the default should be no authentication, everybody must see everybody else calculations. For the few wanting to install on a server/cluster and provide OpenQuake as a service to third party users (for instance the sysadmin of an university department or of an insurance company), we can give a few tips about how to set up the authentication.

**Comment by daniviga** [comment]
I agree with Michele. At this point I propose the solution 2, but binding the WebUI daemon on 127.0.0.1 only.

If you want to expose the WebUI to your network maybe you want to add authentication first.

**Comment by pslh** [comment]
I agree with the previous comments, and suggest that we adopt solution 2 binding on 127.0.0.1 only.  Anyone wishing to open the web UI to other computers should decide how they wish to manage access.

**Comment by daniviga** [comment]
Solution 2 is in PR #2073
