### ISSUE TITLE
NRML 0.5 format for the source model

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2099]
Here is one proposal, which is mimicking what we did for the risk files in the migration NRML 0.4 -> 0.5:

- [x] we will keep backward compatibility forever, i.e. the engine will be able to read NRML 0.4 files and to upgrade them on-the-fly automatically and no warning will be printed
- [x] there will be a command `oq upgrade_nrml <dir>` to bulk-upgrade all the source models in the given directory
- [x] the new format will be the same as before, except that now the source model will be a sequence of SourceGroups containing sources instead of a sequence of sources
- [x] attributes of the SourceGroups will be transmitted to the underlying sources
- [x] the SourceGroup must have a mandatory attribute tectonicRegion
- [x] the number of srcs_weights is equal to the number of sources in the group and the sum of the
weights is one, if present.

Here is an example

```xml
<?xml version='1.0' encoding='utf-8'?>
<nrml xmlns:gml="http://www.opengis.net/gml"
      xmlns="http://openquake.org/xmlns/nrml/0.5">
  <sourceModel name="Test source model" grp_interdep='indep'>
    <sourceGroup name="group1"  tectonicRegion="Stable Continental Crust"
                 src_interdep="indep" rup_interdep="mutex"
                 srcs_weights="0.1 0.2 0.7">
      <pointSource id="1" name="point" >
        ...
      </pointSource>
      <pointSource id="2" name="point" >
        ...
      </pointSource>
      <pointSource id="3" name="point" >
        ...
      </pointSource>
    </sourceGroup>
    <sourceGroup name="group2"  tectonicRegion="Stable Continental Crust"
                 src_interdep="indep" rup_interdep="indep"
                 srcs_weights="0.1 0.2 0.7">
      <pointSource id="4" name="point">
        ...
      </pointSource>
      <pointSource id="5" name="point">
        ...
      </pointSource>
      <pointSource id="6" name="point">
        ...
      </pointSource>
    </sourceGroup>
        ...
  </sourceModel>
</nrml>
```

An alternative proposal is to make the parser smarter, so that it can read both NRML 0.4 and NRML 0.5, and also mixed files containing both sources and SourceGroups: in this case there will be no deprecation of the old format and no suggestion of upgrading it.

**Comment by mmpagani** [comment]
+ I don't have a particular preference for the strategy to be used for maintaining backward compatibility (i.e. smarter parser Vs. upgrading tool). 
+ Regarding the weights, in the nrml definition - as you indicate - this is an optional parameter. The way we treat it when it's not defined I suggest we leave it to the calculators. 
+ I'm fine with the assumption that a SourceGroup is homogeneous wrt Tectonic region i.e. point 5 above
