### ISSUE TITLE
Error messages for wrong command lines are not ideal

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2104]
For instance

``` bash
$ oq engine --foo
usage: oq [-v]
                   {dbserver,info,purge,show,show_attrs,upgrade_nrml,tidy,plot_sites,plot,run,reduce,export,engine,help}
                   ...
oq: error: unrecognized arguments: --foo
```

we get the error for `oq` not for `oq engine`. It is not clear if this can be solved, since it looks like an issue of argparse.

**Comment by micheles** [comment]
It is not worth spending time for this. It also probably very difficult.

**Comment by raoanirudh** [comment]
For reference, git uses the [Damerau-Levenshtein algorithm](https://github.com/git/git/blob/master/levenshtein.c) to suggest alternatives for mistyped commands. See also the functions `help_unknown_cmd(...)` and `help_unknown_ref(...)` in https://github.com/git/git/blob/master/help.c for git's solution to this issue.

**Comment by micheles** [comment]
We can do that in Python, there are libraries for autocompletion. The problem is that I do not want to abandon argparse which is in the standard library. Also, I do not think it is worth the effort, given that the direction we are going is towards a Web/QGIS interface. The command-line will be left for power users who know what they are doing,
