### ISSUE TITLE
oq purge 0 should also purge the database

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2130]
Currently it only purges the HDF5 files, but not the DB. It means that in the WebUI one sees the old calculations, but cannot download the outputs since the underlying HDF5 files have been removed. Perhaps it is enough to make the computation invisible (set the `relevant` flag to false).

**Comment by daniviga** [comment]
I would be in favor of purging the DB too, but only if `multi_user` is false, to avoid accidental removal of other users data.
