### ISSUE TITLE
SourceModelParser from nrmllib to commonlib

### ISSUE THREAD

**Issue by andreaS86** [gem/oq-engine#2177]
Good morning.

I have installed the OQ v. 2.0.1. for windows.
I have an issue regarding a python script which is working well in an older version of OQ (built in Ubuntu environment). Here the "SourceModelParser" is called from the nrmllib which, as far as I understood, now it is superseded. To make it work I changed the string 

> _from openquake.nrmllib.hazard.parsers import SourceModelParser_  
in
> _from openquake.commonlib.source import SourceModelParser_
and the importing process is fine.

The issue is the following: when this SourceModelParser is called something goes wrong because (I guess) something is different from the previous version.
The attached image reports the error I got.

Do you have any suggestions to make it work? 
Thank you in advance for you support. 

Andrea
![image](https://cloud.githubusercontent.com/assets/20818993/17394022/48b31256-5a27-11e6-9cd8-7e865bc9c200.png)

**Comment by micheles** [comment]
You can use the mailing list for this kind of questions. Which script are you using? If it is a script to convert XML to CSV you do not need it since the engine can export to CSV directly nowadays.

**Comment by andreaS86** [comment]
Dear Michele,

thank you for the answer and sorry for writing in the wrong section but I
was told to write here.
I haven't developed directly the script I am using so I can tell you what I
understood.
That *SourceModelParser* is called in the *def* "
*_get_source_model_from_file*" in the *class* *HC* and then is used to
define a source model which is an input to compute the hazard and its
disaggregation.

I hope to have been clear enough.

Anyway, if it is more suitable for you I can open a thread in the mailing
list; here is ok?
https://groups.google.com/forum/?fromgroups#!forum/openquake-users

Thank you again and have a nice day.
Andrea.



2016-08-05 8:14 GMT+02:00 Michele Simionato <notifications@github.com>:

**Comment by micheles** [comment]
Sorry for the delay, but August is a vacation period. Please send the script you are using, otherwise it is impossible to help you.

**Comment by andreaS86** [comment]
Dear Michele,

it was holiday for me too. Anyway, as requested, I attach the script we
were talking about.
Probably you will see some unnecessary lines but this script was not coded
by myself so I left them there.

Thank you and have a nice day,
Andrea.




2016-08-24 9:30 GMT+02:00 Michele Simionato <notifications@github.com>:

**Comment by micheles** [comment]
I don't see any attachment, just use the mailing list.
