### ISSUE TITLE
Improve the dbserver behaviour when CTRL-C is fired

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2201]
When the _dbserver_ process is started manually (usually by `oq dbserver start`) it cannot be stopped with `ctrl-c`. If `ctrl-c` is pressed by mistake the process does not exit even if `oq dbserver stop` says "dbserver already stopped" and the _dbserver_ process can be stopped only using kill; this is dangerous because even if the process stays alive it does not accept any new connection and another _dbserver_ process is spawned if a new calculation is fired.

A similar issue appears when `oq webui start` is used: when `ctrl-c` is fired to stop the _webui server_ the dbserver stays in background but it cannot be stopped by `oq dbserver stop` (it returns "dbserver already stopped") and must be killed instead. As said before if a new calculation is started a new dbserver process is created:

```bash
$ oq webui start
$ ps a | grep dbserver
29087 pts/9    Sl+    0:01 /home/daniele/py2/bin/python2 -m openquake.server.dbserver

# CTRL-C #
  File "/home/daniele/py2/bin/oq", line 9, in <module>
    load_entry_point('openquake.engine', 'console_scripts', 'oq')()
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/commands/__main__.py", line 44, in oq
    parser.callfunc()
  File "/home/daniele/GIT/gem/openquake/oq-hazardlib/openquake/baselib/sap.py", line 184, in callfunc
    return self.func(**vars(namespace))
  File "/home/daniele/GIT/gem/openquake/oq-hazardlib/openquake/baselib/sap.py", line 239, in main
    return func(**kw)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/commands/webui.py", line 47, in webui
    rundjango('runserver', hostport)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/commands/webui.py", line 30, in rundjango
    subprocess.call(args)
  File "/usr/lib64/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

$ ps a | grep dbserver
29087 pts/9    Sl     0:01 /home/daniele/py2/bin/python2 -m openquake.server.dbserver
$ oq dbserver stop
dbserver already stopped
$ oq webui start # (or oq engine --run <...>)
$ ps a | grep dbserver
29087 pts/9    Sl     0:01 /home/daniele/py2/bin/python2 -m openquake.server.dbserver
29341 pts/9    Sl     0:00 /home/daniele/py2/bin/python2 -m openquake.server.dbserver
```

**Comment by micheles** [comment]
The reason why the CTRL-C does not work properly is that the DbServer internally uses a thread and the CTRL-C does not propagate well. The reason why it uses a thread (initially I wanted to use a separate process) is that due to a bug of multiprocessing in Python 2.7 it is impossible to pass a connection to the worker process (it is not pickleable). The good news is that now I have figured out a way to get back the result of the query without passing the connection to the worker, so I can use processes and the CTRL-C works just fine.
