### ISSUE TITLE
Classical damage : error related to PoE = 1

### ISSUE THREAD

**Issue by maxpittore** [gem/oq-engine#2299]
Using engine version 2.1.0-0~dev1467757438-83448cf

Currently oq-egine raises an exception if PoEs == 1 are found in the Hazard model. 
This indeed can happen if very small values of imls are used (e.g. small PGA values), and should not cause an exception. 

I´m currently patching it by changing PoE == 1 in PoE = 1.0-ie-6 (or anyway a small value, by which the modified PoE won´t affect the resulting damage outputs)

Massimiliano Pittore

**Comment by micheles** [comment]
The origin of the problem is explained here: https://groups.google.com/d/msg/openquake-users/1OgarSfy1-8/oBROSkS8LQAJ
