### ISSUE TITLE
Move openquake.cfg in a new /etc/openquake/engine folder.

### ISSUE THREAD

**Issue by nastasi-oq** [gem/oq-engine#2303]
Currently the engine configuration file lies in `/etc/openquake` folder.
Add a `/etc/openquake/engine` directory where move `openquake.cfg` file should be more consistent and with a better namespaces separation (we already have `/etc/openquake/platform`).
**PAY ATTENTION:** when implement it for packaging update/upgrade phase from the old infrastructure.

**Comment by daniviga** [comment]
We can close this since the issue was caused by the oq-engine install aside the OpenQuake Platform. We are now using standalone installers.
