### ISSUE TITLE
Exposure model schema enhancements

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#2320]
_From @raoanirudh on February 10, 2016 11:18_

**1. Support unit conversions for occupants**

The three conversion types supported for costs should also be supported for occupants. This would require allowing allowing a line like the following to be added to the exposure xml:

``` xml
<conversions>
  <occupants type="aggregated">
</conversions>
```

where the valid types are the same as those used for costs, i.e., `"aggregated"`, `"per_asset"`, or `"per_area"`.

Thus, when the exposure model is read, OpenQuake should perform the same multiplications that are used for the costs (depending upon the specified conversion type) in order to get the total number of occupants:

``` python
if occupants_type == "aggregated":
  return occupants
if occupants_type == "per_asset":
  return occupants * number
if occupants_type == "per_area":
  area_type = self.area_types
  if area_type == "aggregated":
    return occupants * area
  elif area_type == "per_asset":
    return occupants * area * number
```

**2. Constrain values for the** `period` **attribute of the** `<occupancy>` **tag**

Currently, this attribute accepts a free string. Instead, the options should be limited to `"day"`, `"transit"`, or `"night"`.

**3. Reinvestigate feasibility of replacing** `"per_asset"` **with** `"per_unit"`

The `"per_asset"` option as currently used actually refers to the individual structural units comprising an asset. Relabelling `"per_asset"` as `"per_unit"` would eliminate the confusion users regularly report.

_Copied from original issue: gem/oq-risklib#691_

**Comment by raoanirudh** [comment]
_From @micheles on February 10, 2016 12:19_

About point 3 we can probably allow both `per_asset` and `per_unit`, as aliases, to ensure backward compatibility. Then we will only document `per_unit` and deprecate `per_asset` (possibly raising a warning). `oq-lite tidy` would replace `per_asset` with `per_unit` to upgrade old exposures.

**Comment by micheles** [comment]
After 3.5 years nothing was done, so it is does not see so important. Also, rather than changing the names in the XML perhaps we should do the renaming work on the IPT side.
