### ISSUE TITLE
Events in the event set xml should identify the source typology from which they are generated

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#2322]
_From @g-weatherill on April 14, 2016 7:50_

In the event set outputs it would be helpful to understand if the rupture is generated by a point/area source, a simple fault source or a complex fault source

_Copied from original issue: gem/oq-risklib#774_

**Comment by micheles** [comment]
I am closing this since it seems low priority. Also the new format already contains some information in that direction: for instance a complexFaultRupture comes from a complex fault source, a simpleFaultRupture from a single fault source, a singlePlaneRupture from a PointSource, etc.
