### ISSUE TITLE
Move the commonlib.parallel library into baselib

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2389]
Inside the oq-hazardlib repository there is a package called `openquake.baselib`. The purpose of that package is to collect basic functionality independent from seismology. In particular the parallelization library, which has nothing to do with science, should go there. For historical reasons, it went into `openquake.commonlib` instead, in the oq-engine repository. This is the wrong place, since commonlib is meant to collect more specific utilities, for instance the parsers for NRML, which is a format specific to seismology.

Having `parallel` inside baselib means that users of hazardlib can write parallel programs without installing the engine. This was my original plan but in the past the parallelization library was not mature enough to be moved outside of the engine. Also, thanks to the recent improvements on our cluster, now the workers can access directly the input files in the controller node, so it is a lot easier to write parallel scripts. A scientist (say Graeme) can write a parallel script working on its machine and have it run *unchanged* on the cluster. The syntax will be

```bash
$ python parallel_script.py  # use the 32 cores of Wilson
$ OQ_DISTRIBUTE=celery python parallel_script.py  # use the 256 cores of the workers
```
Any abuse of this functionality will be punished by Daniele ;-)

**Comment by daniviga** [comment]
Do you plan then to move also part of the configuration file to hazardlib? Or this feature will anyway require a full engine installation to be able to use its configuration?

Because `OQ_DISTRIBUTE=celery` relies on the settings, about the RabbitMQ host and the celery queue, which are provided by `oq-engine/openquake.cfg`

**Comment by mmpagani** [comment]
I would be useful to have an example of a 'parallel' script. 
ciao

**Comment by micheles** [comment]
I am writing some documentation right now. Here is an example:

```python
import os
from openquake.baselib import parallel

def sum_list(lst):
    return sum(lst)


if __name__ == '__main__':
    print(apply(sum_list, (range(100),)))  # sequential
    print(parallel.apply(sum_list, (range(100),)).reduce(acc=0))  # parallel
```

@daniviga 
We will think of something. For sure we do not need the all of the engine.

**Comment by mmpagani** [comment]
Thanks Michele. I look forward to discuss this with you. This example is too abstract for me.
