### ISSUE TITLE
Documentation: new stuff

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2391]
## Anaconda
- [ ] Done  

**environment.yml**
```yaml
name: openquake
channels:
- IOOS
dependencies:
- IOOS::libspatialindex=1.8.5=0
- IOOS::rtree=0.8.2=py27_0
- cython=0.25.1=py27_0
- decorator=4.0.10=py27_0
- django=1.8.4=py27_0
- docutils=0.12=py27_2
- funcsigs=1.0.2=py27_0
- futures=3.0.5=py27_0
- geos=3.3.3=0
- h5py=2.6.0=np111py27_2
- hdf5=1.8.17=1
- mkl=11.3.3=0
- mock=2.0.0=py27_0
- nose=1.3.7=py27_1
- numpy=1.11.1=py27_0
- openssl=1.0.2j=0
- pbr=1.10.0=py27_0
- pip=9.0.0=py27_0
- psutil=4.4.2=py27_0
- python=2.7.12=1
- readline=6.2=2
- requests=2.11.1=py27_0
- scipy=0.18.1=np111py27_0
- setuptools=27.2.0=py27_0
- shapely=1.5.11=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - pyshp==1.2.3
```
```bash
conda env create -f ./environment.yml
source activate openquake
pip install -e oq-hazardlib/ #after the git clone
pip install -e oq-engine/ #after the git clone

```
Notes:

- Special thanks to Hyeuk Ryu
- Unofficially supported
- A couple of tests have minor numerical differences (<10e-5)

TODO: 
- py35 version
- run some tests on different OSes (Linux, Mac, Windows)

## Docker

- [x] Done

**Comment by pslh** [comment]
Following experiments running RMTK on Luis laptop (win10 + anaconda) we used:
conda install matplotlib==1.5.3
conda install scipy==0.17.1
conda install -c scitools shapely 1.5.13
conda install basemap==1.0.7

**Comment by daniviga** [comment]
Closing for now. We need a better understanding of how to manage rolling dependencies on Anaconda first.
