### ISSUE TITLE
The exporter for 'avglosses-rlzs' is broken

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2425]
This was used for integration with the SVIR plugin. I was producing csv files with header
['lon', 'lat', 'asset_ref', 'asset_value', 'average_loss',  'stddev_loss', 'loss_type']

It looks like it has been broken for several months (there was no test for it). Check with Paolo if we need to maintain this or if it better to change the format in the platform side.

**Comment by micheles** [comment]
This is an example of the format exported by the engine now:

```
asset_ref,taxonomy,lon,lat,nonstructural,structural
a0,"RM",81.29850,29.10980,9.95370E+01,3.06198E+02
a1,"RC",83.08230,27.90060,5.51371E+01,6.70444E+01
a2,"W",85.74770,27.90150,9.00514E+00,1.63837E+02
a3,"RM",85.74770,27.90150,1.60448E+01,2.38587E+02
```

**Comment by ptormene** [comment]
The previous format was much more complicated to handle from QGIS, because it consisted of multiple csv files that had to be merged together in a single QGIS layer.
In 863de5c I've updated the plugin to use the new (simpler) format.

**Comment by micheles** [comment]
I have removed the old exporter, so there is no problem anymore.
