### ISSUE TITLE
Try to run the engine with Python 3.6

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2429]
It should use less memory, see http://www.infoworld.com/article/3149782/application-development/python-36-is-packed-with-goodness.html

**Comment by daniviga** [comment]
See https://travis-ci.org/gem/oq-engine/builds/197382861

I had to use newest scipy (0.18) and numpy (1.12) because no other wheels exist for Python 3.6 (and I have not time now to make them), but this mix is producing different numbers.

**Comment by micheles** [comment]
At some moment we will have to upgrade to newer versions of numpy/scipy independently from the usage of Python 3.6, but at the moment there is no urgency. Let's try again in 6 months or so.

**Comment by daniviga** [comment]
It works and all tests are green (I've been able to run the full test suite on Wilson). I was investigating an issue (segfault) with numpy and working on that [I've been able to produce](https://github.com/gem/oq-containers/pull/11) a [preliminary set](http://ftp.openquake.org/wheelhouse/linux/py36/) of Python dependencies we use for Python 3.6; few optional deps are still missing (rtree, which is available as not manylinux1) and basemap.

**Comment by daniviga** [comment]
Build on travis: https://travis-ci.org/gem/oq-engine/builds/207682371
