### ISSUE TITLE
Merge https://github.com/GEMScienceTools/oq-engine-docs inside oq-engine

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2470]
This will make it easier to have the documentation synchronized with the code. Also it will make it easier to prepare the release. The manual will be automatically generated by Jenkins.

**Comment by daniviga** [comment]
It should be also included in the installers and/or packages.

**Comment by daniviga** [comment]
The builder has been setup: https://ci.openquake.org/job/builders/job/manual-builder/

**Comment by daniviga** [comment]
Closed via #2511
