### ISSUE TITLE
Put openquake.cfg in a proper place when installed via pip

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2478]
Currently `oq` looks for `openquake.cfg` in `/etc/openquake` and in `site-packages`. This does not play well with installations from pip because:

1. It is not part of the python package 
2. It cannot be installed in `/etc`
3. `site-packages` folder is the wrong place (out of the openquake context)

To work around this issue in various installers we are setting the `OQ_SITE_CFG_PATH` env var (see https://github.com/gem/oq-installers/blob/master/unix/env/install.sh#L75 and https://github.com/gem/oq-installers/blob/master/windows/nsis-installer/oq-console.bat#L6)

**Comment by daniviga** [comment]
Under linux, and maybe mac, a good place could be `~/.config`, it would be great that the configuration file is created at the first run if not found:

1. Use the env variable
if empty
2. Look in /etc/openquake
if does not exist
3. look in local user config store (it should be `~/.config` per https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
4. if does not exist yet
create it from a template (this is what almost every software does), i.e. renaming openquake.cfg in openquake.cfg.dist and using that as a template

**Comment by daniviga** [comment]
This is what we should do on every platform:

```python
if os.environ['OQ_SITE_CFG_PATH']:
    config_prefix = OQ_SITE_CFG_PATH
else:
    if config.multi_user:
        # currently 'engine' subdir is not used
        config_prefix = '/etc/openquake'
    else:
        if sys.platform == 'win32':
            config_prefix = os.environ['APPDATA']
        elif sys.platform == 'darwin':
            config_prefix = '~/Library/Preferences/openquake'
        else:
            config_prefix = (os.environ['XDG_CONFIG_HOME'] + '/openquake' if
                             os.environ['XDG_CONFIG_HOME'] else '~/.openquake')
```

**Comment by micheles** [comment]
Here are my thoughts:

1. We have already 1 million of different ways of installing the engine, let's try to minimize the differences.
2. In a source installation openquake.cfg (the file at top level of the repository) is the default configuration file and it works perfectly well for single user situations, so much that travis is using it (I would not mind moving it to engine/openquake.cfg, though)
3. for some reason such file is not in the source code when installed by pip; it should be there instead (say in `lib/python/site-packages/openquake/engine/openquake.cfg`), and it should be the last path checked (add a line `paths.append(OQDIR)` at the end of `_Config._get_paths`)
4. .config should not be created by the engine, /etc/openquake.cfg should be created by the package: let's try to differentiate between installation time and normal runtime

**Comment by daniviga** [comment]
See the PR as reference on how it works now
