### ISSUE TITLE
Decorate documentation to automate updates during release.

### ISSUE THREAD

**Issue by nastasi-oq** [gem/oq-engine#2481]
In markdown files adding well formed html comments just before lines/blocks that needs modifications during the packages release workflow speed up the process and potentially allow us to automatize it.

''<\!-- GEM master: __action__ stable: __action2__ -->''

Examples of actions:
  * ''next-release''
  * ''master''
  * ''any other string''

It will be skipped during rendering by github and will be processed/tracked during release.

Placement of comment could be just after the current content on the same line (to test it).

**Comment by daniviga** [comment]
Closed by https://github.com/gem/oq-engine/pull/2581
