### ISSUE TITLE
Turn matplotlib into a real dependency of the engine and test it on Travis

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2482]
This is something to discuss with Daniele. The testing on travis can be done by running things like

```bash
$ MPLBACKEND=Template oq plot_uhs -1
```
after running the AreaSource demo (similarly for the other kind of plots). `MPLBACKEND=Template` is a fake backend which should not require X to run.

**Comment by daniviga** [comment]
Matplot lib is already a dependency declared in `setup.py` and can be installed via

```bash
$ pip install -e oq-engine/[plotting]
```

**Comment by micheles** [comment]
I mean mandatory and not optional dependency.

**Comment by daniviga** [comment]
Does it save a png if the server is headless?

**Comment by daniviga** [comment]
Anyway, we have binary deps for all the platform we support, so it's a go for me

**Comment by micheles** [comment]
The goal of the test is to prove that the construction of the plot is fine, not that the check that the plot is the expected one (that would be a lot more difficult). For the purpose of the engine (plotting as a debugging tool not meant for the final user) that's more than enough. It is true that storing a png would be useful, then we should use the command

```
$ MPLBACKEND=Agg oq plot_uhs -1
```

**Comment by daniviga** [comment]
Ok, I would be in favor of making matplotlib mandatory when switch to opt is made (currently we cannot make it mandatory because Trusty and RHEL are using old versions of matplotlib)
