### ISSUE TITLE
Work around the celery/rabbitmq shortcomings

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2497]
Transferring large amount of data with celery/rabbitmq is an issue. It is easy to run out of memory when unpickling large arrays, and also we can have rabbitmq block or run out of mnesia space. Moreover, the performance is far from optimal. On the other hand, we discovered that reading the data via NFS works perfectly well. This is why a few months ago we introduced a configuration parameter `shared_dir` pointing to a NFS mounted directory readable by all workers. Apart from UCERF, there are no calculators taking advantage of this feature yet.

Here is the proposal: let's introduce tasks able to read directly from the shared directory and let's add an attribute `shared_dir_on` to such tasks. The value of `shared_dir_on` is a boolean flag, true if the `shared_dir` is defined in the configuration file, false otherwise. Then the distribution logic will be the
following:

1. if `shared_dir_on` is true, use celery if `use_celery` is true (i.e. nothing strange)
2. if `shared_dir_on` is false, use `concurrent.futures` even if `use_celery` is true, but print a warning

In this way the tasks will run even on clusters where there is no `shared_dir`, only the computation will be slower, since it will use the cores of the controller node and not the other machines.

This is the best possible solution, since the alternative is having the calculation fail because of excessive data transfer if it is large; if it is small it is not an issue to run it on the controller node only.

Here is a list of operations that would benefit from this logic (i.e. reading directly from the datastore without passing for the celery/rabbitmq combination):

1. hazard curves post-processing
2. loss curves post-processing
3. event based risk from GMFs
...

**Comment by daniviga** [comment]
```
    if shared_dir_on is false, use concurrent.futures even if use_celery is true, but print a warning

In this way the tasks will run even on clusters where there is no shared_dir, only the computation will be slower, since it will use the cores of the controller node and not the other machines.
```

I'm not in favor of this: sometime you cannot setup NFS (probably most of our users cannot, and even us in Zurich).
Our biggest Italian user (INGV) has a quite powerful cluster but with a small master node. Their computations are then too big (aka slow) for just their master, but they work well on the entire cluster in a reasonable amount of time; with this change their cluster will become useless at all (and same for us in Zurich). What's the advantage?
If `use_celery` is `true` we must give it a chance. It will probably work anyway for most of medium size computations, even without a shared dir, like it's working now.

**Comment by micheles** [comment]
Daniele, let's say I keep the current calculators unchanged. The issue is that I see coming a new generation of calculators (UCERF is already here) using the NFS approach. With this proposals such calculators can be run also by users like the INGV, although slowly, while currently they cannot be run at all.

**Comment by daniviga** [comment]
If we don't break backward compatibility then I'm favor. I would also say that isn't uncommon for a cluster setup to enable an NFS share, if users want a cluster then they should be prepared for this kind of jobs; my only concerns are when you cannot setup it (no easy fw access, unrealible/lagging connection...)

**Comment by daniviga** [comment]
One more question, I guess from your first message that one of the biggest issue is pickling, unplicking data, so even if we change the broker and/or the results backend this problem will stay. I was reading yesterday an article about celery, where they suggested rabbitmq as broker, but redis as backend: redis isn't perfect as broker (we saw it in the past, with nonworking revoke) but as we always suspected is far better efficient for sending back results. This maybe can improve a bit the scalability of "legacy" calculators.

**Comment by micheles** [comment]
The typical use case for the shared_dir approach is post-processing of a large quantity of data with a trivial function. Suppose for instance there are 100 GB of data for 1,000 realizations and that the post-processing operation is computing an average that will return 100 MB of data. Now that trivial computation (the average is basically a sum) would fail because of the massive data transfer, whereas when this proposal will be implemented it will work just fine and it will be fast, even if the master has few cores.
The issue is not returning back large quantities of data, is sending such large quantities of data all at once.
If we can avoid that, the post-processing will become a lot more efficient.
