### ISSUE TITLE
The name of the datastore file starts with `-`

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2521]
when it's downloaded from the WebUI.

For instance `-home-openquake-arao-oqdata-calc_13074.hdf5`; this cause issues on Unix environments. We should strip the leading dash.

**Comment by daniviga** [comment]
We send out `"attachment; filename=/home/daniele/oqdata/calc_2.hdf5"` which cannot be used on Unix and then `/` are converted to `-` by the browser.
