### ISSUE TITLE
LXC are not always stopped by packager.sh

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2585]
It seems there's a condition in `packager.sh` where the script is able to exit after an error without passing through the teardown function, leaving an LXC alive. This morning several LXC were running with no jobs active on Jenkins:

```
ubuntu-lxc-eph_vySMLH   RUNNING 0         -      10.0.3.238 -    
ubuntu14-lxc-eph_BD2q8P RUNNING 0         -      10.0.3.76  -    
ubuntu14-lxc-eph_Nj4Q9n RUNNING 0         -      10.0.3.10  -    
ubuntu14-lxc-eph_U9uNaE RUNNING 0         -      10.0.3.149 -    
ubuntu14-lxc-eph_oBnLtA RUNNING 0         -      10.0.3.246 -    
ubuntu14-lxc-eph_seezMf RUNNING 0         -      10.0.3.204 -    
ubuntu16-lxc-eph_EJnmAE RUNNING 0         -      10.0.3.49  -    
ubuntu16-lxc-eph_Nxit4E RUNNING 0         -      10.0.3.111 -    
ubuntu16-lxc-eph_Q2V73a RUNNING 0         -      10.0.3.187 -    
```

Not sure if the issue is here, on the packager of hazardlib.

**Comment by nastasi-oq** [comment]
Working on oq-taxonomy I found a setup that is resilient to web-driven build interruption.
1. add a dumb signal handler trapping SIGTERM
2. add a real signal handler into the packager.sh script
3. into the signal handler function disable the SIGTERM signal with ``trap "" SIGTERM``

I don't know if it is related with this issue.

**Comment by daniviga** [comment]
They seem to work as expected now.
