### ISSUE TITLE
CSV format for scenario losses_by_asset output

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#2600]
Currently, the losses_by_asset csv output produced by a scenario_risk calculation lists the ground-up losses and insured losses for a loss category as a single field separated by a whitespace. For instance:

| asset_ref | taxonomy | lon      | lat    | contents\~mean:2   | contents\~stddev:2 | structural\~mean:2 | structural\~stddev:2 |
|-----------|----------|----------|--------|-------------------|-------------------|-------------------|---------------------|
| a3        | tax1     | -122.57  | 38.113 | 120.168 90.126    | 133.78 100.335    | 37.9632 28.4724   | 71.689 53.76675     |
| a2        | tax2     | -122.114 | 38.113 | 1279.49 959.6175  | 1669.93 1252.4475 | 189.23 141.9225   | 279.58 209.685      |
| a5        | tax1     | -122     | 37.91  | 651.673 488.75475 | 907.532 680.649   | 388.122 291.0915  | 557.767 418.32525   |
| a4        | tax3     | -122     | 38     | 2214.98 1661.235  | 2342.36 1756.77   | 1344.04 1008.03   | 2092.88 1569.66     |
| a1        | tax1     | -122     | 38.113 | 1652.8 1239.6     | 1979.55 1484.6625 | 1561.7 1171.275   | 2501.51 1876.1325   |
| a6        | tax2     | -122     | 38.225 | 2255.41 1691.5575 | 2352.51 1764.3825 | 735.526 551.6445  | 1127.89 845.9175    |
| a7        | tax1     | -121.886 | 38.113 | 606.314 454.7355  | 897.459 673.09425 | 375.297 281.47275 | 652.628 489.471     |

The field headings are not self-explanatory, and the combination of commas and whitespace necessitates a few additional post-processing steps before one can visualize the different loss categories.

Below is a proposal for improving this output (the table scrolls horizontally). The assets are ordered alphabetically.

| asset_ref | taxonomy | lon        | lat      | contents_mean | contents_stddev | contents_insured_mean | contents_insured_stddev | structural_mean | structural_stddev | structural_insured_mean | structural_insured_stddev |
|-----------|----------|------------|----------|---------------|-----------------|-----------------------|-------------------------|-----------------|-------------------|-------------------------|---------------------------|
| a1        | tax1     | -122.00000 | 38.11300 | 1652.80       | 1979.55         | 1561.70               | 2501.51                 | 1239.60         | 1484.66           | 1171.28                 | 1876.13                   |
| a2        | tax2     | -122.11400 | 38.11300 | 1279.49       | 1669.93         | 189.23                | 279.58                  | 959.62          | 1252.45           | 141.92                  | 209.69                    |
| a3        | tax1     | -122.57000 | 38.11300 | 120.17        | 133.78          | 37.96                 | 71.69                   | 90.13           | 100.34            | 28.47                   | 53.77                     |
| a4        | tax3     | -122.00000 | 38.00000 | 2214.98       | 2342.36         | 1344.04               | 2092.88                 | 1661.24         | 1756.77           | 1008.03                 | 1569.66                   |
| a5        | tax1     | -122.00000 | 37.91000 | 651.67        | 907.53          | 388.12                | 557.77                  | 488.75          | 680.65            | 291.09                  | 418.33                    |
| a6        | tax2     | -122.00000 | 38.22500 | 2255.41       | 2352.51         | 735.53                | 1127.89                 | 1691.56         | 1764.38           | 551.64                  | 845.92                    |
| a7        | tax1     | -121.88600 | 38.11300 | 606.31        | 897.46          | 375.30                | 652.63                  | 454.74          | 673.09            | 281.47                  | 489.47                    |

**Comment by micheles** [comment]
This is a bug indeed, a non-intended behavior. The name of the fields should be consistent with other exports, so I would use `contents~mean_ins` instead of `contents_insured_mean` and likewise for the other fields.
