### ISSUE TITLE
Event based ruptures output: reorganise polygon vertices

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#2618]
The polygon's geometry is not organised in the correct order: clockwise or counter-clockwise
See image
![screen shot 2017-03-09 at 15 09 40](https://cloud.githubusercontent.com/assets/6975363/23754310/d2304e8a-04dc-11e7-9157-7fb6f5a46a15.png)

**Comment by daniviga** [comment]
It's beautiful, in my opinion

**Comment by raoanirudh** [comment]
Not far off from a Kandinsky masterpiece!
![composition-viii](https://cloud.githubusercontent.com/assets/1707414/23760194/45356d4a-04ef-11e7-8fca-ff14f0b9f0e1.jpg)

**Comment by CatalinaYepes** [comment]
For some reason in some cases it works well
See the example for subduction Interface
<img width="1180" alt="screen shot 2017-03-10 at 12 07 21" src="https://cloud.githubusercontent.com/assets/6975363/23793144/2e22f55a-058a-11e7-8414-b75f27bd9bb3.png">

**Comment by daniviga** [comment]
This bug was reproduced during the hazard workshop, as signaled by @mmpagani

**Comment by micheles** [comment]
The bug is also in the demo for event based hazard. I suspect the bug has been there for years. I must ask Marco about how to order the vertices. The bug seems to be in `PlanarSurface.get_surface_boundaries`.

**Comment by ptormene** [comment]
In `oq-engine/openquake/calculators/export/hazard.py line 155`, the object r['boundary'] contains a string that already contains vertices in the order: (top left, top right, bottom left, bottom right).

WKT multipolygons require that the order be clockwise, in this case: (top left, top right, bottom right, bottom left).

If we are assuming that the boundary string is compatible with WKT, then it is using the wrong order.  
PH also suggests that storing the string is less space efficient than storing an array of floats - this might be relevant for large numbers of ruptures.

See also https://github.com/gem/oq-hazardlib/pull/617

**Comment by CatalinaYepes** [comment]
Also consider this modifications to the `rup_data` output. It has a similar format but the delimiters and the polygon coordinates have not been updated

**Comment by CatalinaYepes** [comment]
And the faults with the correct geometry!

<img width="908" alt="screen shot 2017-03-24 at 12 08 24" src="https://cloud.githubusercontent.com/assets/6975363/24291847/fdb5ed1c-108a-11e7-94d7-d86cb1aa338e.png">
