### ISSUE TITLE
Store the ruptures in a better way

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2645]
Now that the project /opt has landed, we may rely on having h5py version 2.6. This means that we could store the rupture geometries are variable-length arrays of points. This should improve a lot the time to store and read the ruptures.

**Comment by daniviga** [comment]
Please open an issue on oq-libs asking for inclusion of h5py 2.6

---
Daniele Viganò
http://daniele.vigano.me

On mobile, please excuse my brevity.

**Comment by daniviga** [comment]
Version 2.7 is out and it seems to include several enhancements, including one variable lenght arrays: should we move to it?

**Comment by micheles** [comment]
Not sure; first of all we should try to run all our tests and confirm than they are green. Then I should run some cases that were broken in the past and see if they are fixed now. We will see.
