### ISSUE TITLE
Classical damage outputs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#2670]
- [x] Quantile loss curves and maps that are not generated with this calculator, so a warning should be printed if asked for in the job.ini
- [x] The hazard curves should be call `quantile_hazard_curve-...` rather than `quantile_curve-`

**Comment by micheles** [comment]
I am raising an error if the user incorrectly sets `quantile_loss_curves` or `conditional_loss_poes` that are not meaningful for this calculator. Since there is no possible confusion, I am not changing the names of the hazard curves.
