### ISSUE TITLE
Classical risk outputs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#2671]
- [x] The loss curves have the format `asset_ref,taxonomy,lon,lat,losses:156,poes:156,avg` which is not Excel-friendly
- [x] The statistical loss curves should be generated in `csv` (quantiles and mean are in `xml`)
- [x] The hazard curves should be call `quantile_hazard_curve-...` rather than `quantile_curve-`

**Comment by micheles** [comment]
I am keeping the name of the hazard curves as they were. The names of the risk curves will be different, things like `loss_curves-sid-1-quantile-0.1.csv`.

**Comment by CatalinaYepes** [comment]
what does it mean `sid-1`?

**Comment by micheles** [comment]
It means site ID #1 (starting from zero).

**Comment by CatalinaYepes** [comment]
I think it should be `asset_ID`, since the user won't know originally which is the site ID.
