### ISSUE TITLE
Check tests numbers on macOS

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2727]
This must be planned for next sprint, we have at least two tests skipped: see https://github.com/gem/oq-engine/pull/2726 and https://github.com/gem/oq-engine/pull/2589. Also the test gmf_ebrisk case_3 is skipped.

For example the generation of loss maps stats is terribly wrong, the number of losses do not match...

We'll need help from the scientists too.

**Comment by daniviga** [comment]
We should raise priority of this. Another test is broken: https://ci.openquake.org/job/macos/job/master_mac_oq-engine/566/testReport/junit/openquake.calculators.tests.event_based_risk_test/EventBasedRiskTestCase/test_case_4/

We already have some tests skipped and macOS user base is quite relevant.

**Comment by daniviga** [comment]
The last reported case is relevant to https://github.com/gem/oq-engine/issues/2995 and not strictly related to macOS

**Comment by raoanirudh** [comment]
@daniviga, @micheles: I can check the test numbers on macOS 10.14. Which test cases should we be looking at specifically?

**Comment by daniviga** [comment]
I would say that currently the situation on macOS is stable so far. Closing.
