### ISSUE TITLE
There are two CSV formats for the hazard curves

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2807]
One used in the tests, one in the engine. The difference is that in the engine there is a single IMT per file, in the tests there are multiple IMTs. We should we unify the two formats. Should the engine use the multi-IMT format or should we split the files in the tests?

**Comment by raoanirudh** [comment]
I prefer the format which produces a separate CSV file for each IMT. Having separate files would make it easier to read and parse the curves, especially when a calculation involves multiple IMTs. With separate files for each IMT, we could even remove the IMT from the column headers and keep only the intensity levels.

**Comment by micheles** [comment]
This is pointless now, since we have change to format in https://github.com/gem/oq-engine/pull/3013.
