### ISSUE TITLE
Automatic manual version

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2887]
The OpenQuake version in the manual (cover), the citation and DOI (page 3) should be automatically updated by `build.sh` (sed?)

**Comment by raoanirudh** [comment]
And if possible, also the total number of pages on page 3

**Comment by daniviga** [comment]
Closed via #3427 and #3476 

DOI is still manually populated, but this requires a separated issue.

**Comment by daniviga** [comment]
DOI has been fixed here https://github.com/gem/oq-engine/pull/3588
