### ISSUE TITLE
Change the gmf_data export for event based, to be loadable by QGIS

### ISSUE THREAD

**Issue by ptormene** [gem/oq-engine#2896]
It should preferably have the same format as for scenario damage.

**Comment by micheles** [comment]
It should be visualized by rupture, so we need a web API like `extract/gmf_data/<ruptureID>`

**Comment by micheles** [comment]
It makes sense to define an output gmf_by_rupture: it can be also build totally in postprocessing.

**Comment by micheles** [comment]
The risk team says that the GMFs and ruptures should be visualized by clicking on the event loss table. This is an interesting visualization project for @ptormene, to be discussed with the scientists.

**Comment by micheles** [comment]
Let's close this, since there was no development after 4 years, so it is good as it is.
