### ISSUE TITLE
Produce a `bcr-stats` output for the BCR calculator

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#2907]
The benefit-cost ratio (BCR) calculator, if used with a non-trivial logic-tree currently, produces outputs for each of the individual branches realized in the calculation. These are saved in the datastore with the name `bcr-rlzs`. Unlike all of the other hazard and risk calculators however, mean and quantile results are currently not provided.

The mean calculated across all realized branches should be provided for all BCR calculations, and stored with the name `bcr-stats`, similar to the other risk calculators. For consistency with the other calculators, the calculation of the mean results can be skipped by specifying `mean_bcr_maps = false` in the job configuration file.

Users of the BCR calculator should also be able to request quantiles calculated across all realized branches, by using the parameter `quantile_bcr_maps` in the job configuration file to specify a set of quantiles (eg. `quantile_bcr_maps = 0.15, 0.50, 0.85`).

**Comment by micheles** [comment]
We have two methods `oqparam.hazard_stats()` (sensitive to `mean_hazard_curves`, `quantile_hazard_curves`) and `oqparam.risk_stats()` (sensitive to `mean_loss_curves`, `quantile_loss_curves`); I would not add a third one `oqparam.bcr_maps_stats()` sensitive to `mean_bcr_maps`, `quantile_bcr_maps`. Why not to keep using  `oqparam.risk_stats()`  ?
