### ISSUE TITLE
List calculation of all users

### ISSUE THREAD

**Issue by benf33** [gem/oq-engine#2916]
Currently oq engine --lhc/lrc only list calculations for the user running the command.
Is it possible to have the list of all the calculations of all users ?

Ben

**Comment by micheles** [comment]
I suggest you to use the mailing list for this kind of questions:
https://groups.google.com/forum/?hl=en#!forum/openquake-users

If you need just to see the list of calculations you can start the WebUI and the admin user can see all of them. Otherwise there is the command `oq db find %`.
