### ISSUE TITLE
Produce a `damages-stats` output for the `classical_damage` calculator

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#2919]
The `classical_damage` calculator, if used with a non-trivial logic-tree currently, produces outputs for each of the individual branches realized in the calculation. These are saved in the datastore with the name `damages-rlzs`. Unlike all of the other hazard and risk calculators however, mean and quantile results are currently not provided.

The mean calculated across all realized branches should be provided for all classical damage calculations, and stored with the name `damages-stats`, similar to the other risk calculators. For consistency with the other calculators, the calculation of the mean results can be skipped by specifying `mean_damage_maps = false` in the job configuration file.

Users of the classical damage calculator should also be able to request quantiles calculated across all realized branches, by using the parameter `quantile_damage_maps` in the job configuration file to specify a set of quantiles (eg. `quantile_damage_maps = 0.15, 0.50, 0.85`).

**Comment by micheles** [comment]
Again, I would reuse the parameters quantile_loss_curves and mean_loss_curves to describe the risk stats, as we did in the classical_bcr case.
