### ISSUE TITLE
Add paging to the WebUI (or any other method)

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2923]
We should investigate how to remove the 100 calculation limit in the WebUI main page. We added this limit because updating (in async, every 5s) a list of more than 100 calculations is very CPU intensive on the browser side and produces lags.

To remove this limitation we should add paging (aka subdivide the list in N pages with 50? calculations each); in this way the user can access all the computations but the browser will load only a subset of them.

@hascar proposed also to try with the continue scrolling/loading. This may also work, but we must make sure that only the visible calculations are refreshed, otherwise after some scroll we'll have again more than hundreds calculation to refresh.

To easily test this issue I would suggest to:
- Run in batch (via `oq engine --run`) 300 times the `ScenarioCase1` demo (which is _very_ fast)
- Remove the default 100 limit in the query/view
- Use Firefox (Chrome has a faster JS engine and is less overkilled by the number of calcs)

**Comment by micheles** [comment]
The investigation was done and the client-side approach was deemed a failure. Let's open another ticket when and if we decide to go back to this issue. It will require support from the server, i.e. passing an offset/limit to the SQL query returning the calculations.
