### ISSUE TITLE
Proposed Uncertainty Model for NGA East GMPEs

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#2954]
One forthcoming task is the implementation of the GMPEs for Central and Eastern North America (CENA) published as part of the NGA East Project (http://peer.berkeley.edu/publications/peer_reports/reports_2015/webPEER-2015-04_NGA-East_8.26.16.pdf). One GMPE is already in the library (http://docs.openquake.org/oq-engine/master/openquake.hazardlib.gsim.html#module-openquake.hazardlib.gsim.shahjouei_pezeshk_2016) and another is waiting inside a PR (https://github.com/gem/oq-engine/pull/2913). There are more to come.

In contrast to the majority of existing GMPEs in the OpenQuake library the NGA East models have a separate, and common, model for the standard deviations, as described by Al Atik (2015) (http://peer.berkeley.edu/publications/peer_reports/reports_2015/webPEER-2015-07-Alatik.pdf). This contains coefficients for inter-event, intra-event (single station and ergodic) and total standard deviations (presented in Chapter 5 of Al Atik 2015).

Here is the problem. The full standard deviation model takes into account epistemic uncertainties, and sets of coefficients are presented for the following cases:
1. Central, Low and High branches
2. Global, Constant (for CENA) and Magnitude-Dependent (for CENA)
3. Ergodic and Single Station

Considering all of these possibilities would result in 18 subclasses for each NGA East model (of which there are about 20). Implementing all of this would produce around 360 new GMPE classes. This doesn't seem like a good approach!

Instead I propose to implement the single common standard deviation model, with the corresponding options passed to the GMPE at instantiation (and set by the user in the nrml). For this I would create a new subclass of the openquake.hazardlib.gsim.base.GMPE class that accepts three optional keyword arguments at instantiation:

`model` : The choice of model from `global` (default), `cena_constant` (the magnitude independent model for CENA) and `cena` (the magnitude-dependent model)
`branch`: Choosing from `central` (default), `low`, `high`
`ergodic`: The choice of ergodic (True, default) or single station (False) models

The user could set their choice in the nrml via something like:
```xml
<logicTreeBranch branchID="b13">
    <uncertaintyModel model="global" branch="central" ergodic="True">DarraghEtAl20151CCSP</uncertaintyModel>
     <uncertaintyWeight>1.0</uncertaintyWeight>
</logicTreeBranch>
```

A prototype implementation of the uncertainty model and the alternative base class for the NGA East models is in the zipped file attached, but the general form of the base class is as such:

```python
class BaseNGAEastGMPE(GMPE):
    """
    Prototype extended base GMPE class for use with NGA East (and maybe other) GMPES
    """
    def __init__(self, model="global", branch="central", ergodic=True):
        """
        Instantiates the class with additional terms controlling which
        type of aleatory uncertainty model is preferred ('global',
        'cena_constant', 'cena'), which branch ('central', 'low', 'high')
        and whether the ergodic or partially ergodic version is preferred.
        """
        super(BaseNGAEastGMPE, self).__init__()
        self.model = model
        self.branch = branch
        self.ergodic = ergodic

    def get_stddevs(self, mag, imt, stddev_types, num_sites):
        """
        Returns the standard deviations for either the ergodic or
        non-ergodic models
        """
        tau = TAU_MODELS[self.model](imt, mag, self.branch)
        phi = PHI_SS_MODELS[self.model](imt, mag, self.branch)
        if self.ergodic:
            # If the model is ergodic the single-station phi (phi_ss) is
            # combined with the site-to-site within-event term (phi_s2s),
            # as described in equation 5.18 (p158), otherwise the
            # single-station phi (phi_ss) alone is taken
            phi_s2s = CENA_PHI_S2S[imt][self.branch]
            phi = np.sqrt(phi ** 2. + phi_s2s ** 2.)
        stddevs = []
        for stddev_type in stddev_types:
            assert stddev_type in self.DEFINED_FOR_STANDARD_DEVIATION_TYPES
            if stddev_type == const.StdDev.TOTAL:
                sigma = np.sqrt(tau ** 2. + phi ** 2.)
                stddevs.append(sigma + np.zeros(num_sites))
            elif stddev_type == const.StdDev.INTRA_EVENT:
                stddevs.append(phi + np.zeros(num_sites)) 
            elif stddev_type == const.StdDev.INTER_EVENT:
                stddevs.append(tau + np.zeros(num_sites))
        return stddevs
```

With this, each NGA East GMPE would simply inherit from the `BaseNGAEastGMPE` class and call the `.get_stddevs(...)` method. This would require only developing one test suite for the standard deviation model.

Comments and feedback from @mmpagani, @micheles and @treviallen would be appreciated before implementing further NGA East models along these lines.

[nga_east_base.py.zip](https://github.com/gem/oq-engine/files/1145609/nga_east_base.py.zip)

**Comment by micheles** [comment]
I changed the XML parser just to support this kind of use cases, so it looks like the right approach to me.

**Comment by mmpagani** [comment]
Hi Graeme, I'm happy with the proposed strategy. I think it will be useful to discuss the best strategy for testing the standard deviation model as you hint in your note.

**Comment by g-weatherill** [comment]
Some further updates to this issue:
1. One possibility for testing the standard deviation model is via comparison with the USGS code here (https://github.com/usgs/nshmp-haz/blob/master/src/org/opensha2/gmm/NgaEastUsgs_2017.java). These don't consider all of the possible cases proposed by Al Atik (2015), though, as they only provide the selected models for the 2017 NSHMP.

2. Following on from previous discussions, the NGA East mean models present some additional challenges. Two different forms of the models are presented in the NGA East literature: the original forms presented by the authors, and the adjusted forms presented here (http://peer.berkeley.edu/publications/peer_reports/reports_2015/webPEER-2015-08-NGA-East-Various826.pdf) - and in the electronic appendices. Quite simply, it would seem that the adjusted forms can only be implemented in the form of a table, whilst some of the originals have a parametric form. My suggestion then would be as a matter of priority to generate the hdf5 tables for each of the final proposed NGA East models. I would then sub-class the GMPETable object hard-coding the path of the GMPE_TABLE attribute to the corresponding hdf5 file for each model. The call to _get_stddevs() function would be replaced with the generalise standard deviation model described above.

**Comment by mmpagani** [comment]
Thanks Graeme. I answer point by point: 
0. The testing part I was referring to is the one inside the engine. I think that our current testing procedure supports only three types of standard deviation.
1.  Yes one possibility is to use the USGS code. However, I would rather contact PEER and ask for a comprehensive suite of codes implementing the various GMPEs.
2. Yes I knew there were two versions of NGA East GMPEs. I'm fine with the suggested prioritisation (this probably depends also on your final goals). As a side note, the increasing use of the table-based GMPEs is opening an additional issue regarding testing.

**Comment by treviallen** [comment]
Hi gents,

I was just getting back onto this when Marco's message arrived.  Graeme's proposed implementation of the NGA-E models seems sensible to me, but I'd have to trust him in that it could work within the engine.  

I think I might have mentioned that I've been testing the table (from PEER Report 2015/04) vs parametric forms of the models for Yenier & Atkinson (2015; YA15) and Shahjouei & Pezeshk (2016; SP16).  I've cleaned up the hazardlib version of YA15 a lot in the past few days - and noticed that the student I had working on it forgot to add the anelastic attenuation term (whoops!).  In any case, the attached fig shows my comparison of parametric vs table forms of the models.  The details of each curve are:

Parametric: hazardlib implementation of GMM
GSIM Table: PEER 2015/04 table converted to hdf5 format and passed into gsim_table.py
Tables: Direct copy & paste from PEER csv tables
Excel: Outputs from spreadsheet provided by YA for model evaluation

Note the parametric implementation for YA15 and the excel outputs match exactly.  However, the matches between the parametric models and the PEER implementation for both YA15 and SP16 are not great.  I'd previously noted that the SP16 plots in the BSSA paper and the PEER report appeared to be different.

I'd have to go back to the documentation and see how these models might have been modified for the PEER model implementation.  First thoughts could be:
1) stress drop adjustment
2) Vs30/kappa adjustment
3) point-source equivalent adjustment

I'm happy to share my hdf5 files of the NGA-E seed models, if you haven't already generated them yourself.

Hope that is somewhat comprehensible.
T 

![nga-e_test_m6 0_vs760](https://user-images.githubusercontent.com/20093971/28574067-1e73a10a-7190-11e7-8756-3ed65b58a002.png)

**Comment by g-weatherill** [comment]
Trevor/Marco

Thanks for the input. I have generated the basic set of hdf5 tables for the 20 adjusted models of the NGA East, as reported in PEER 2015/08. I am rethinking the uncertainty model approach and I will elaborate on the problems I'm finding and add a separate comment on it in due course..

For Marco's points:
1. I am trying as far as possible to avoid extending the supported standard deviations, and I don't think it is necessary. The parameters are always the same (tau, phi and sigma) it is simply the flexibility in how the user can control their generation that is needed.

2. I think the strategy for testing will depend on which models have parametric forms. For the adjusted versions only the tables are available, and these hdf5 tables have been generated from those published in the appendix to PEER 2015/08. I can use these same spreadsheet to generate the test tables but this is circular so I'm wondering if that adds value. The tables in the spreadsheets published with PEER 2015/04 could be used to test the original parametric forms of the models as Trevor is indicating. I'm not sure how much additional information PEER will supply as the electronic appendices represent the "official" models.

3. Eventually both the original forms and adjusted forms would be good to have in the oq-engine. As the latter can only be implemented in one way it makes sense to make these the priorities. For testing the table-based GMPEs in general I'm not sure if a testing strategy can or even should be developed. This simply puts the onus on the users to construct the tables correctly, in the same way we would expect them to do for an input model. Perhaps some tools to build the tables from a couple of more user-friendly formats (e.g. NGA East spreadsheets, text tables etc.) could be added to minimise the potential for error in table construction from the users.
