### ISSUE TITLE
Addition of Zhao et al (2016a, b, c) GMPEs to OpenQuake

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#2986]
Some new PSHA models in development using the suite of GMPEs produced by Zhao et al. (2016), which form the update of the Zhao et al. (2006) models.

1. Implement models for active shallow crust, subduction interface and subduction in-slab

2. These models introduce a new distance measure representing the distance through a volcanic zone (volcanic path). This is trickier to implement as it requires that the length of path from source-to-site that intersects with a regular volume (in 3D) must be calculated.

Suggest two-stage implementation, first with the GMPEs implemented and tested and the distance attribute `rvolc` added. Subsequently the addition of volcanic zones can be considered. Note that it may be the case that a volcanic zone is required that is neither a seismogenic source nor a site property. Some input from the users may be needed here (I am already contacting the authors for their code/test tables).

**Comment by g-weatherill** [comment]
Just to update ... the authors have provided (to me) their Fortran and Excel implementations. I will proceed with development and testing.

**Comment by mmpagani** [comment]
Thanks Graeme. Pls let us know if there's anything regarding this implementation you would like to discuss with us.
