### ISSUE TITLE
Add Atkinson 2010 Hawaii GMPE

### ISSUE THREAD

**Issue by cbworden** [gem/oq-engine#2988]
A useful GMPE that doesn't seem to be part of the available set:

Atkinson, G.M. (2010) Ground-Motion Prediction Equations for Hawaii from a Referenced Empirical Approach. Bulletin of the Seismological Society of America, Vol. 100, No. 2, pp. 751–761, April 2010, doi: 10.1785/0120090098

Note that the 'log A' term behaves badly as Rjb --> 0. Some tweaking of distances may be necessary. Maybe just make Rjb < 1 equal to 1.

**Comment by mmpagani** [comment]
Hi Bruce,

Thanks for signalling this. We are indeed working on the GMPE. See here: 
https://github.com/gem/oq-engine/pull/2966

Marco

**Comment by klunk386** [comment]
Hi Bruce,
I have included your suggestion in the implementation. The filter is considered only when calculating the adjustment coefficient at distances less than 1Km, which is then applied to unmodified ground motion as calculated directly from BooreAtkinson2008.
Cheers,
Valerio
