### ISSUE TITLE
The memory monitoring is not working

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2999]
Since a long time ago, we are losing the log messages when a computation is running out of memory. We should add a logserver_url to the `Monitor` and call `db.actions.log(db, job_id, timestamp, level, process, message)` in `Monitor.send`.

**Comment by micheles** [comment]
I have added a log message https://github.com/gem/oq-engine/commit/d64d3371f43e598d1322a53ebfbf8a5acd9a7e56 but it only logs in the celery logs, not in the main console.

**Comment by daniviga** [comment]
At least with #3005 I've been able to get the warning logs in the main console also using celery. Should we consider this closed?

**Comment by micheles** [comment]
No, it is not closed. The goal is to get in the console log also the warnings coming from remote machines going out of memory, not only the warning coming from the master.

**Comment by daniviga** [comment]
That's right. I was able to see warnings because I was running it on a single machine and those were actually warnings coming from the master process.
