### ISSUE TITLE
Add env vars to override openquake.cfg DbServer settings

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3003]
This will be very useful to run parallel CI jobs on systems with poor isolation (macOS and Windows).
We already have `OQ_DATADIR` for hdf5 files, but this (correctly) does not affect the dbsever.

We need to be able to change the db path and the dbserver port to point it in the job workspace.

**Comment by micheles** [comment]
What about using a configuration file openquake.cfg in a suitable location for this?
