### ISSUE TITLE
Calculation is not stopped when a process is killed/terminated 

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3007]
When one of the subprocesses is killed (by the user, by the OOM killer) the computation isn't stopped and other processes continues to crunch data until the tasks have been completed.

This is quite dangerous because it leaves several processes alive using resources (or even idle but with memory allocated) and in the case of OOM killer intervention the situation get works because of the high memory pressure (i.e OOM kills one process base on scoring but this does not stop other processes to leak, depending on the memory usage rate, the OOM killer may be too slow).

One solution could be (on unix) using:
`os.killpg(os.getpgrp(), signal.SIGKILL)` in `raiseMasterKilled`

Please note the `SIGKILL`: because how `MultiProcess` works (no cancel, no revoke) a KILL is required to stop process without waiting for a task to end.

**Comment by micheles** [comment]
Notice that the PIDs of all workers are known and stored in the list `openquake.baselib.parallel.executor.pids`, so one could loop on those and kill them.

**Comment by daniviga** [comment]
It seams that the only clean solution would be catch the `BrokenProcessPool` exception when submitting new tasks or when iterating on the results. If the exception is raised we can kill all the processes and die:

```python
    try:
        r = f.result()
    except futures.process.BrokenProcessPool as e:
        for pid in parallel.executor.pids:                                         
            try:                                                                   
                os.kill(pid, signal.SIGKILL)                                       
            except:                                                                
                pass   
        raise futureKilled
```

**Comment by micheles** [comment]
I suggest to change the base except to an `except OSError:  # pid not found`
