### ISSUE TITLE
Event based output updates

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#3024]
## Event based output updates
The following changes are proposed for the event_based_risk outputs:
- [x] Format `realizations` output (follow same format as #3001)
- [x] ~Hide `fullreport` output from webui~
- [x] Update the aggregate loss curves output
- [x] Update `avg_losses` output to include tags
- [x] Update `loss_maps` output
- [x] Remove `losses_by_tag` output
- [x] Update `ruptures.csv` output
- [x] Expose only outputs `-stats`

### aggregate loss curves output
- [x] Update output name `agg_loss` → `agg_loss_curve`
- [x] ~Include the `tag1-loss_curve`, `tag2-loss_curve`, ⋯ outputs~

### avg_losses output
- [x] To the current output, add the tags associated with each asset in additional columns

### loss_map output
Follow similar format as the `hmaps`:
- [x] The first line should include the quantile and the investigation time
- [x] ~Column headers should be modify as follow: `loss_type~poe-0.02` → `loss_type-0.02`~
- [x] Add the tags associated with each asset in additional columns

### losses_by_tag output
- [x] This output is redundant if we add the tags to the `avg_losses` output

### ruptures.csv output
- [x] Include in the first line the `ses_per_logic_tree_path`
- [x] Make sure `oq extract ruptures` works even via the webUI

### -stats output
- [x] By default do not show the realization outputs. Only show the `-stats` outputs (mean and quantiles)
- [x] Make sure that the loss curves and maps can be exported with `oq engine --eo`

**Comment by micheles** [comment]
We also want to be able to aggregate the avg_losses-stats from the QGIS plugin
