### ISSUE TITLE
Define a list of display names for the risk and hazard outputs together with the scientists

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3032]
They will appear in the WebUI and the QGIS plugin. The thing to change is the dictionary openquake.server.db.actions.DISPLAY_NAME.

**Comment by raoanirudh** [comment]
## Risk outputs
### Scenario Damage / Risk

- gmf_data → Ground Motion Fields
- damages_by_asset → Average Asset Damages
- (damages_by_event) → Aggregate Event Damages
- losses_by_asset → Average Asset Losses
- losses_by_event → Aggregate Event Losses

### Classical Damage / Risk

- damages → Asset Damage Distribution
- avg_losses → Average Asset Losses
- loss_curves → Asset Loss Curves
- loss_maps → Asset Loss Maps

### Event Based Risk

- agg_curves → Aggregate Loss Curves
- agg_loss_table → Aggregate Loss Table
- avg_losses → Average Losses
- loss_maps → Asset Loss Maps

**Comment by raoanirudh** [comment]
### Classical BCR

- bcr → Benefit Cost Ratios

**Comment by raoanirudh** [comment]
Suggestions for the hazard outputs:

sourcegroups → Seismic Source Groups
ruptures → Earthquake Ruptures
hcurves → Hazard Curves
hmaps → Hazard Maps
uhs → Uniform Hazard Spectra
disagg → Disaggregation
realizations → Realizations
