### ISSUE TITLE
"New version released" warning

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3084]
We should add a warning, in the command line and in the webui, that notifies users that a new OQ Engine release is available (for stable releases). This:
 - Can be disabled via confing (`openquake.cfg`)
 - Should silently fail if no connection is available
 - Should not create delays: a cache should be used (a field in the DB is enough...)

In the past this issue was less problematic since everyone was using Linux packages that get updated with `apt` or `yum`. Nowadays most people are using installers which need manual upgrade.

Releases can be retrieved from here https://developer.github.com/v3/repos/releases/

**Comment by pslh** [comment]
I think this is a good idea, do we have a time estimate?

**Comment by micheles** [comment]
This check takes at least 0.5 seconds, so I would not add an option to disable it or to cache it.
