### ISSUE TITLE
Maximum Distance Filter for GMPE calculation

### ISSUE THREAD

**Issue by klunk386** [gem/oq-engine#3091]
I have tested the new filter for a couple of magnitude values (maximum_distance = [(8, 200), (7, 100)]) and obtained non realistic results. This is likely due to linear extrapolation beyond bounding values, which filters in this case the intermediate magnitudes (<6) at very short distances. Although such behaviour can be avoided using a better binning within the maximum_distance command, I would suggest to introduce instead a step-wise filtering. In that way, the above example would be interpreted as:
`(do not calculate at distances above 100km for all magnitudes below 7) & (do not calculate  at distances above 200km for all magnitudes below 8) & (no distance filter above magnitude 8)`

**Comment by klunk386** [comment]
This is a sketch of what I would compute using the following settings:
`maximum_distance = [(8, 200), (7, 150), (6, 100), (5, 50)]`

![distancescaling](https://user-images.githubusercontent.com/22977002/31169670-af61d9d4-a8f9-11e7-873a-7b62763b2555.png)

**Comment by mmpagani** [comment]
I'm unsure on the type of feedback you expect from me on this issue. The first test you did seems perfectly reasonable to me since you are excluding magnitudes below 7. On the linear scaling I already told Michele that in my opinion it should be removed since it does not allow the user to properly control the behavior of the filter.

**Comment by klunk386** [comment]
In the first test, magnitudes below 7 are not excluded, but used only within a very narrow distance range, because of the extrapolation.

**Comment by mmpagani** [comment]
The interpolation should be removed. @micheles how complex it is to complete this stuff?

**Comment by micheles** [comment]
Not so complex and it is already market for engine-2.7, so it will fixed soon.
