### ISSUE TITLE
master randomly fails on Jenkins

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3133]
We have python processes dying probably due a segfault:

https://ci.openquake.org/job/master_oq-engine/3918/
https://ci.openquake.org/job/master_oq-engine/3911/

```
ubuntu   23245  0.0  3.0 2354212 793660 ?      Sl   Oct15  40:48 python2.7 /opt/openquake/bin/nosetests -a  -v --with-xunit --with-doctest --with-coverage --cover-package=openquake.hazardlib
ubuntu   23320  0.0  0.5 1736300 153452 ?      Sl   Oct15   0:01 python2.7 /opt/openquake/bin/nosetests -a  -v --with-xunit --with-doctest --with-coverage --cover-package=openquake.hazardlib
ubuntu   24193  0.0  0.0      0     0 ?        Z    Oct15   0:11 [/usr/bin/python] <defunct>
```

Containers were Xenial. Maybe related to what happened Saturday on the cluster?

**Comment by micheles** [comment]
This is not happening anymore. Let's keep it open for a few weeks and see.

**Comment by micheles** [comment]
It is not happening. I will close the ticket.
