### ISSUE TITLE
There is still a pickle error when reading composite_risk_model.attrs

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3143]
I should investigate the .npz extracted from `http://localhost:8800/v1/calc/25/extract/composite_risk_model.attrs` where 25 is the ID of the ScenarioRisk demo. Here is the error that Paolo gets:

```python
   Calculation 25: Scenario Risk Demo (Nepal)
   File "/home/michele/oq-irmt-qgis/svir/dialogs/viewer_dock.py", line 539, in load_losses_by_asset_aggr
       session, hostname, calc_id, 'composite_risk_model.attrs')
     File "/home/michele/oq-irmt-qgis/svir/dialogs/viewer_dock.py", line 475, in extract_npz
       return numpy.load(io.BytesIO(resp_content))
     File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 416, in load
       "Failed to interpret file %s as a pickle" % repr(file))
   Failed to interpret file <_io.BytesIO object at 0x7fc5d812b830> as a pickle
```

**Comment by micheles** [comment]
The test on travis are fine. The npz file is okay. The error message is misleading and has nothing to do with Python 2 <-> 3 pickle issues. The real issue is that `resp_content` is empty. It is empty because the extraction API is actually returning a 404. It is returning a 404 because job 25 was created by user travis and read by user paolo. This is why it works on travis and not on Paolo's machine. The problem was cause by the recent change in https://github.com/gem/oq-engine/pull/3134. Now thing are more correct that before and less forgiving. Perhaps the restore procedure should change the owner of the calculation? Or the extractor should not check ownership?

**Comment by micheles** [comment]
I think there is a good solution: if `settings.LOCKDOWN`  is True pass the username, otherwise ignore the username. It means that without LOCKDOWN any user can extract the data of any other user, which is the thing to expect.

**Comment by daniviga** [comment]
Agreed. Is also how everything else is working (calc list, output download), if I am not wrong.

**Comment by daniviga** [comment]
I would also add that anyway somewere on the client side the returned 404 isn't managed properly. @ptormene you should raise an error since a 404 is returned, before trying to look into its content.

**Comment by micheles** [comment]
Indeed, @ptormene you should change that in extract_npz, for instance by checking that the status code is 200 before extracting the content.
