### ISSUE TITLE
Make identification of a `venv` more robust

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3167]
It's currently done via `if 'VIRTUAL_ENV' in os.environ` but this does not work when an entry point in the `venv` is called directly, i.e.:

```bash
$ ~/venv/bin/oq engine --run job.ini
```
or via a `systemd --user` unit (happened already on the VM for Colombia).

Can be resolved in this way:

```python
import sys

def is_venv():
    return (hasattr(sys, 'real_prefix') or
            (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix))
```
(from https://stackoverflow.com/questions/1871549/python-determine-if-running-inside-virtualenv/42580137#42580137)

**Comment by micheles** [comment]
In Python 3 the check `sys.base_prefix != sys.prefix` seems to be enough (and then the venv directory can be extracted from sys.prefix without even looking at the environment variable). Let's hope we will migrate to Python 3 soon or later.
