### ISSUE TITLE
Add spectral period range as attribute of GMPE (or define consistent attribute name for coefficients table)

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#3172]
GMPEs cannot be used outside of the define spectral period range. At present the user is notified of this in the hazard calculation as the CoeffsTable object will throw a key error should they attempt to run a calculation for a spectral period outside of the range defined. It would be useful, however, to know what the spectral period range of the GMPE is without having to call the get_mean_and_stddevs(). This is a problem for the GMPE toolkit, which tries to define the period range of a GMPE without calling it. It does this by reading the period limits from the coefficients table. However, some GMPEs (particularly the older ones) do not consistently use COEFFS to refer to the coefficients table, and in fact no consistent approach to defining the coefficients tables was adopted. This caused a problem in a recent PR (https://github.com/GEMScienceTools/gmpe-smtk/pull/57).

I suggest adopting one or both of the following:

1. Add an attribute to the GMPE class, e.g.:  `DEFINED_FOR_PERIOD_RANGE = (0.01, 10.0)`

2. Use the common term COEFFS for the "main" coefficients table of all GMPEs, such that the period range could be retrieved easily.

**Comment by micheles** [comment]
I like 2). It is easy to add a check in MetaGSIM so that everytime you subclass a GSIM and you forget to define COEFFS you get an error. In this way we can easily fix all the legacy classes with missing COEFFS.

**Comment by mmpagani** [comment]
Ciao Graeme,
I agree with Michele, option 2 is more convenient and safer.
Thanks
Marco

**Comment by micheles** [comment]
Here is how you could implement the check in MetaGSIM:

```python
    def __init__(cls, name, bases, dic):
        if (cls.__module__ != 'openquake.hazardlib.gsim.base' and
                not hasattr(cls, 'COEFFS')):
            # apply the check to user classes only
            raise AttributeError('%s has no attribute COEFFS' % cls)
        super(MetaGSIM, cls).__init__(name, bases, dic)
```

**Comment by g-weatherill** [comment]
Thanks Michele/Marco. It looks like whilst there are quite a few GMPEs with this problem it doesn't take long to fix. I will work on it over the next couple of days and try to make the PR later this week or early next week.

**Comment by micheles** [comment]
After 2+ years nothing happened on this front, so I am closing the issue.
