### ISSUE TITLE
Add a csv importer for the exposure

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3190]
The XML exposure could contain a link to a .csv files with the asset information, something like

```xml
<assets> ./assets1.csv ./assets2.csv  </assets>
```

The mandatory fields are `asset_ref, number, taxonomy, lon, lat`.
The optional fields are `area`, `structural-value, structural-deductible, structural-insurance_limit` ... `occupants-day, occupants-night, occupants-transit` and then the tags and `geometry`.

**Comment by raoanirudh** [comment]
It would be useful to support compressed csv files too.

**Comment by micheles** [comment]
Why the field `number` is considered mandatory by IPT but it is not mandatory for the engine?
It is okay to make it mandatory for the engine but then exposure that worked in the past will not work anymore? For instance the exposure in classical_bcr/case_1 has no number. Currently if the number is missing it is considered 1. Currently the number is considered mandatory only in damage calculators, where if missing from the XML and error is raised.

**Comment by raoanirudh** [comment]
@micheles, the relevant section from the manual: 

> The `number` attribute is mandatory for damage calculations. For risk calculations, this attribute must be defined if either the area or any of the costs are provided per structural unit comprising each asset.

**Comment by micheles** [comment]
But in IPT it is always mandatory.

**Comment by CatalinaYepes** [comment]
@micheles we need to update IPT
