### ISSUE TITLE
Average losses for the classical_risk calculator

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#3201]
For the classical_risk calculator, the average losses (average _annual_ losses if `risk_investigation_time = 1`) were listed in the old xml outputs for the asset loss curves (https://github.com/gem/oq-engine/blob/engine-2.4/openquake/commonlib/nrml_examples/loss-curves.xml#L21), but are no longer visible to the user with the introduction of the new csv formats for the outputs. It would be useful to make them available through the datastore outputs or through the QGIS interface, using a format identical to the current avg_losses output for the event based calculator.

**Comment by micheles** [comment]
The information is in the datastore, inside `loss_curves-rlzs`. I would expose it via QGIS for what concerns the aggregation features. I would also expose the output to the engine, but only for the statistics, consistently with what we do in other cases.
