### ISSUE TITLE
ctrl-c does not kill subproc when also dbserver is started by same entrypoint

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3211]
When `oq webui start` is run and no DbServer is already running, DbServer is started automatically.

In this case, when a `CTRL-C` on the WebUI process is fired, the `oq-job-**` and `oq-workers` processes are left alive and stays in memory until the WebUI is restarted.

When the database server is started a priori everything is working as expected, both with and without `prctl`.

DbServer started manually:
![peek 2017-11-03 09-02](https://user-images.githubusercontent.com/1818657/32364646-5106ba3c-c076-11e7-9403-676e4076f662.gif)

DbServer started by `oq webui start`:
![peek 2017-11-03 09-06](https://user-images.githubusercontent.com/1818657/32364641-4cb14f92-c076-11e7-9303-c64c674b6853.gif)

**Comment by micheles** [comment]
Unfortunately this is true only for small jobs. For large jobs, even if the DbServer is not started by the WebUI, killing the WebUI leaves the jobs running.

**Comment by micheles** [comment]
Jobs started from the WebUI are already killed correctly, at least for Python 3. Job not started by the WebUI are not killed, but I would argue that this is the right behavior. It seems that the change in
https://github.com/gem/oq-engine/pull/3212/ fixed this bug too. Should we close it?

**Comment by daniviga** [comment]
No, unfortunately even using Python 3 I get orphan processes when I `CTRL-C` the WebUI and the DbServer has been started by it.

**Comment by daniviga** [comment]
To solve this issue we need to demonize the dbserver (see https://pypi.python.org/pypi/python-daemon/ as an example)
