### ISSUE TITLE
The disaggregation matrix should be 5-dimensional, not 6-dimensional

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3260]
Right now eeach task builds a matrix of shape (d1, d2, d3, d4, d5, d6), where d6 is the number of tectonic region types. Since all sources in a task are of the same tectonic region type, the matrix is full of
zeros except for the index corresponding to the given tectonic region type. In a model with 9 tectonic region types (i.e. India) we are essentially using 9 times more memory than needed. Now, this is not
necessarily a problem for the memory, since normally the memory occupation is not dominated by the size of the matrix. Still, it is a problem for the data transfer, since the size of the transferred arrays is proportional to the number of tectonic region types. In this case we would be transferring 9 times more data than needed, all space wasted in the transfer of zeros.

**Comment by g-weatherill** [comment]
Perhaps this might be an opportunity to re-assess the merit of disaggregating by tectonic region type. It is not obvious (to me at least) when this information is useful, and now that is is possible to disaggregate by source (https://github.com/gem/oq-engine/pull/3198) then the user can obtain more detailed and relevant information from that. Can we find out if any users actually make use of disaggregation by tectonic region type, and if they know that they can now disaggregate by source, whether this could be removed?

**Comment by mmpagani** [comment]
I don't have a clear picture of the group of users of the disaggregation calculator. I personally consider interesting and useful to have a disaggregation per tectonic region. This is convenient for example when you are doing sensitivity analyses. Removing one parameter will not solve the sparseness of the disaggregation matrix.

**Comment by micheles** [comment]
Just a note: the sparseness of the disaggregation matrix is not a big problem. We do not transfer the full disaggregation matrix, we transfer its sections obtained by applying the functions in `openquake.hazardlib.calc.disagg.pmf_map`, so a lot less than the full matrix. Once the case of the disaggregation by TRT is fixed, we are in a good shape, unless there are really a lot of bins.

**Comment by mmpagani** [comment]
One small additional note. For models where distributed seismicity is modelled using smoothed seismicity the disaggregation by source will be an overkill. We need to provide the user with a way to group sources (or a combination of source groups and individual sources).
