### ISSUE TITLE
Provide a quick introduction about the engine and its capabilites

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3266]
A quick introduction for users about what the OpenQuake Engine is capable of, fro the scientific point of view, available calculators ... maybe with some info-graphic

**Comment by pslh** [comment]
We could probably harvest existing material from:
- The manual
- The science book
- [(https://doi.org/10.1785/0220130087)]
- communication material (ask Jeph)

**Comment by rcgee** [comment]
We could expand on what's here:

- https://www.globalquakemodel.org/openquake-engine

**Comment by micheles** [comment]
I think what is in https://www.globalquakemodel.org/openquake-engine is fine, so I am closing the issue, unless there are clearer specs.
