### ISSUE TITLE
oq webui start should not open IE if Chrome/FF are available

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3267]
On many Windows systems (corporate i.e.) IE9 (!!) is still the default browser. IPT does not work with it, for example.

We should see if there's a way to check if Chrome or FF are installed and open one of them even if they are not the default ones.

**Comment by micheles** [comment]
https://docs.python.org/3/library/webbrowser.html says that the module honors the environment variable BROWSER

**Comment by daniviga** [comment]
It's more easy, I'm opening a PR.

**Comment by daniviga** [comment]
No, this is not easy to implement because OS different from Linux do not put the browser executables in `$PATH', so even if I do

```python
            try:
                wb = webbrowser.get('chrome-browser')
            except webbrowser.Error:
                try:
                    wb = webbrowser.get('firefox')
                except webbrowser.Error:
                    wb = webbrowser.get()
            finally:
                wb.open(url)
```
or I user `BROWSER` env var script will use always the default set in Windows/macOS.
