### ISSUE TITLE
Wrong MFD from SourceConverter

### ISSUE THREAD

**Issue by klunk386** [gem/oq-engine#3298]
When parsing a MultiPoint source file using:
```
  conv = SourceConverter(width_of_mfd_bin=0.1)
  source_group = nrml.parse(xml_input, conv)
```
the mfd of the single sources is set to arbitrary, instead of a truncatedGR as it should be.
`(<class 'openquake.hazardlib.mfd.evenly_discretized.EvenlyDiscretizedMFD'>, 'min_mag', 'bin_width', 'occurRates')`
This prevents the use of this method to modify the mfd when dealing with this type of sources.
For other source types it works just fine, as I tested.

**Comment by micheles** [comment]
I need the NRML file containing multiPointSources that you are using.

**Comment by klunk386** [comment]
Here is the file. Indeed, it contains the "truncGutenbergRichterMFD".

[GridMultiSources_S10.xml.zip](https://github.com/gem/oq-engine/files/1563041/GridMultiSources_S10.xml.zip)

**Comment by micheles** [comment]
I cannot reproduce the problem Valerio.

**Comment by micheles** [comment]
At the end, it was not a bug.
