### ISSUE TITLE
Introduce a minimum_distance

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3369]
There are GMPEs which are not valid for distances below a certain threshold, but sometimes we have to use them anyway. Vitor asked to introduce a `minimum_distance` concept: if the distance if below the minimum, use the minimum instead. Technically we will have to operate on the DistanceContext in hazardlib.

**Comment by micheles** [comment]
Marco Pagani says that the clean way to implement this is via a "Meta" GMPE.

**Comment by micheles** [comment]
Vitor says that he needs this feature only for scenario/event_based calculators.

**Comment by g-weatherill** [comment]
Is it possible to give an example of when/why one shouldn't use a GMPE below a certain distance? There are some GMPEs that probably shouldn't be used above a certain distance too? If it is the case that the GMPE isn't valid for certain distances (as indicated by the GMPE's author) this should either be something hard-coded into the GMPE (such as an attribute of a min/max distance range) or should be something the modeller takes into account in the model building. Adding the ability to "fix" a minimum distance seems somewhat open to abuse (if I "fix" my minimum distance to 30 km and my hazard will reduce considerably!).

**Comment by mmpagani** [comment]
Ciao @g-weatherill. This is an example already implemented in https://github.com/gem/oq-engine/pull/3271. As you might recall, I've been always in favour of hardcoding the range of distances for which GMPEs are considered valid. Regarding the possible abuse, perhaps it is true but I don't think it is superior to other options already available. In general, I think it's hard to prevent possible misuses.

**Comment by micheles** [comment]
I am in agreement with @g-weatherill, the minumum_distance should be hardcoded in the GSIM, so that the user does not have to tweak the gsim_logic_tree file. Still the ability of tweaking the gsim_logic_tree_file is useful, since it does not require access to the source code and does not require a new release of the engine just to change a parameter. So I would implement the following:

1) if the GSIM class has a nonzero minimum_distance attribute, use it
2) if the user has set a minimum_distance in the gsim_logic_tree file, that one has the precedence
