### ISSUE TITLE
HDF5 format for disaggregation output

### ISSUE THREAD

**Issue by klunk386** [gem/oq-engine#3381]
Some fields, which were important to compute mean disaggregation, have been removed from the HDF5 file structure, such as ['realizations']->['weight']
Without this information, the code we implemented to produce scenarios for Tanzania does not work anymore. Would it be possible to re-discuss the output structure together?

**Comment by micheles** [comment]
This was done here: https://github.com/gem/oq-engine/pull/3343

@klunk386 the pull requests are public, the only way we can avoid such issues is if you guys keep on eye on them and raise a hand if you see something that could break your scripts, before the merge. I cannot know what you are doing in your scripts.

**Comment by micheles** [comment]
There are two other options to mitigate the breakage (not exclusive). 

1. put all of your important scripts under CI so if there is breakage we notice it immediately
2. do not access directly the datastore. We have an API to access the datastore which is
guaranteed to work even if the datastore changes. The API is tested by the QGIS plugin,
is good, but it is no complete, and actually it is at the early stages of developement.

In this case, the safe way to extract the realizations from the datastore would be

```python
from openquake.baselib.datastore import read
from openquake.calculators.extract import extract
dstore = read('../calc_42.hdf5')
extract(dstore, 'realizations')
```
