### ISSUE TITLE
Event-Based Random Seed not working

### ISSUE THREAD

**Issue by alejocalde01** [gem/oq-engine#3415]
Ciao Team,

While running an specially large event-based risk calculation for Haiti I found out that using smaller SES and changing the random seed is producing the same ruptures and same losses on the output files. Seems that the random seed is not being changed. 

Thanks a lot for adressing the problem,

Alejandro

**Comment by micheles** [comment]
The seed relevant for event based hazard is called `ses_seed`. `random_seed` is used for sampling, but you are using full enumeration.
