### ISSUE TITLE
 Make it possible to run calculations from a pre-imported exposure

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3466]
This is useful in a lot of situations, and also for the Aristotle project. We need a method to extract
a reduced AssetCollection from the full exposure, given a region_constraint.

**Comment by mmpagani** [comment]
rtree is your friend :)

**Comment by micheles** [comment]
Actually I am convinced that `shapely.geometry.Point.within(region)` (the one we are already using) is fast enough.
