### ISSUE TITLE
Upgrading dependencies

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3571]
For engine 3.1 I would like to upgrade

- [x] numpy to 1.14
- [x] scipy to 1.01
- [x] h5py to 2.8 (now there is only a release candidate)

Make a run on travis and one on the cluster. I have already tried the libraries on my machine: I do not see any significant speedup, but there is no regression either. The motivation is that we are using very old versions, the scientists have moved on, and it best to check early if there are problems in upgrading.
For instance there is an ugly warning coming from h5py 2.7.x:
```
/home/michele/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

PS: I checked that with h5py 2.8rc1 the ugly warning disappear indeed.

TODO:
- [ ] Update oq-libs (https://github.com/gem/oq-libs/pull/31)
- [ ] Archive old wheels
- [ ] Update requirements of old releases
- [ ] Put new wheels in main repos

**Comment by daniviga** [comment]
I would like also to align all the dependencies to Ubuntu 18.04 plus what you said.

**Comment by daniviga** [comment]
Several tests are breaking with the new stack:

https://travis-ci.org/gem/oq-engine/builds/361595749

the deployment part is implemented in https://github.com/gem/oq-engine/tree/bump-deps

**Comment by daniviga** [comment]
> PS: I checked that with h5py 2.8rc1 the ugly warning disappear indeed.

Please check https://travis-ci.org/gem/oq-engine/jobs/361610079#L481

**Comment by daniviga** [comment]
TODO:
- [ ] Update oq-libs
- [ ] Archive old wheels
- [ ] Update requirements of old releases
- [ ] Put new wheels in main repos
