### ISSUE TITLE
Trap SIGHUP signal and mark computation failed

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3605]
We should trap the `SIGHUP` signal, revoke the tasks and mark the computation failed (like a `SIGTERM`). When a calculation is launched via CLI without using `byobu`/`screen`/`tmux` or `nohup` it depends on the availability of the controlling terminal. This can disappear when it's allocated via ssh and the connection is then closed.

**Comment by micheles** [comment]
I am not sure if the calculation should fail. I can just continue, right? The logs are stored in the database and visible in the WebUI and the calculation can be killed with `oq abort` if wanted.

**Comment by daniviga** [comment]
No, if the control terminal is lost and not log redirection is in place the computation will freeze waiting for a buffer screen where to push logs
