### ISSUE TITLE
Delete calc does not work properly when `multi_user = True`

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3649]
```bash
$ oq engine --dc 5
Are you sure you want to (abort and) delete this calculation and all associated outputs?
This action cannot be undone. (y/n): y
Job 5 is complete
Could not remove /home/daniele/oqdata/calc_5.hdf5: [Errno 13] Permission denied: '/home/daniele/oqdata/calc_5.hdf5'
```

This is probably caused by the fact that the deletion of hdf5 file is performed by the DbServer, thus by the `openquake` user, instead of the actual owner of the file (the user that runs `oq`).

**Comment by micheles** [comment]
Moreover `oq reset` does not clean up the database, only the datastore, as discovered by Catalina, even on a single machine like gemmicro.
