### ISSUE TITLE
Make it sure that the global hazard mosaic will keep working with future versions of the engine

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3734]
@mmpagani is preparing a repository with the models of the global hazard mosaic. In order to make it sure that the models will keep working in the future, we need to set up a procedure running all of them before a new release of the engine. Since the models are very large and we cannot afford to waste weeks of cluster computation time to re-rerun them, we must be creative. We need to find a way to run a model that requires 10 hours on a cluster in 10 minutes on a workstation, or better, *without changing the input files*. Fortunately, there is an easy way to do that, by simply sampling the sites (i.e. 1 site over 10) and the sources (i.e. 1 source over 100). The results will not be realistic but this is not an issue, since the goal here is making sure that the models run, not to check the results. For that, there are already the tests in place. The other thing to do is to setup a procedure to run the models on demand (could be on Jenkins or in some other way).

- [x] prepare the global hazard mosaic
- [x] add a turbo-mode to run hazard models fast in the engine
- [x] set up a procedure to run the global hazard mosaic

Once this is implemented, the ancient project of the so-called "long running tests" will be essentially done, at least for the hazard part.

**Comment by daniviga** [comment]
This has been implemented in GitLab via GitLab-ci and using the OQ Engine 'latest' Docker image.
