### ISSUE TITLE
GmfComputer python

### ISSUE THREAD

**Issue by gposada** [gem/oq-engine#3750]
Hello!

I try to calculate PGA with GmfComputer on python script, but I have a doubt with gsims.

My script is: 

**`pga = GmfComputer(rupture = rup, sites = SiteCollection([Site(location=Point(-75.566, 6.167), vs30=406, vs30measured=True, z1pt0=100., z2pt5=5.)]), imts = {'PGA': imts}, gsims = {'Active Shallow Crust': AkkarEtAlRhyp2014(), 'Subduction IntraSlab': YoungsEtAl1997SInter()}, truncation_level = None)`**

gsims are a set of GSIM instances, How do I write this parameter? 

I have: `gsims = {'Active Shallow Crust': AkkarEtAlRhyp2014(), 'Subduction IntraSlab': YoungsEtAl1997SInter()}`. but is not funtional. 

Thanks!

**Comment by micheles** [comment]
Use a list!

```python
gsims = [AkkarEtAlRhyp2014(), YoungsEtAl1997SInter()]
```
