### ISSUE TITLE
Memory leak in version 3.1.

### ISSUE THREAD

**Issue by sjacob90** [gem/oq-engine#3820]
Hi all,
Firstly, thank you for making this great piece of software. 

I am using oq to do a classical PSHA. I ran a calculation with all realizations in the logic tree and it
ran successfully in OQ 2.7 on my Windows 7, 8Gb RAM PC (Laptop). The calculation took around 6 days.

I ran the same calculation using OQ 3.1 on another PC with Windows 7, 16Gb RAM (Desktop) expecting a performance boost due to the Desktop version of hardware, however in the course of the calculation the python processes utilized memory as great as 15.57 Gb until the Windows OS itself terminated the process.

Please note that I did run it successfully on the Desktop for a little less than half the realization and it had completed successfully.

Since there was no such memory issue in the 8Gb Laptop, I believe the memory increase has to do with the OQ version. 

I am considering to roll back to 2.7. Any suggestions or advice is highly appreciated?

**Comment by daniviga** [comment]
Hi @sjacob90 

thanks for your feedback. I would suggest you to use our support forum for this kind of support requests instead of GitHub. Anyway, are you able to send your input files to engine.support@openquake.org so we can make a complete inspection of your `job.ini` and your input data?

Thanks

**Comment by micheles** [comment]
The memory occupation with v3.1 should be less than with v2.7. It is possible that it is a problem specific to Windows (we usually run calculations on linux). As @daniviga suggested, the only way we can investigate the issue is if you send us the files you used.

**Comment by sjacob90** [comment]
@daniviga @micheles Thank you. I will forward the files to the mentioned email id.
