### ISSUE TITLE
Add test for get_stddevs() in GMPEs

### ISSUE THREAD

**Issue by rcgee** [gem/oq-engine#3839]
We need a test to check that the standard deviations of all GMPEs are returned in a consistent manner. For example in Kanno 2006, the number of sites was not originally passed to the method _get_stddevs(). This caused issues when using this GMPE in the strong motion toolkit. 
See the fix in https://github.com/gem/oq-engine/pull/3838

**Comment by micheles** [comment]
I do not see a general way to protect against this kind of errors (`_get_stddevs` is not defined always and has different signatures in different GSIMs), so let's do nothing until the next time something bad happens.
