### ISSUE TITLE
Raise reference Python to 3.6

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3864]
Meta-issue for Python 3.6 migration

| ITEM | PR | STATUS | MERGE ORDER |
| ----------------|--------|-----|---|
| oq-python-deb | https://github.com/gem/oq-python-deb/pull/14 | merged | 1 |
| oq-python-rpm | https://github.com/gem/oq-python-rpm/pull/6  | merged | 1 |
| oq-libs | https://github.com/gem/oq-libs/pull/40 | merged | 2  |
| env | https://github.com/gem/oq-builders/pull/102 | merged |  |
| Windows | https://github.com/gem/oq-builders/pull/102  | merged |  |
| opt | https://github.com/gem/oq-builders/pull/102| merged |  |
| env | https://github.com/gem/oq-builders/pull/102 | merged |  |
| Docker | https://github.com/gem/oq-builders/pull/103 | merged  | 3 |
| Engine | #3868 | merged | 4 |
| VM | na | pending | 5 |

### Changes in oq-engine  (#3868)

- [x] ~Add deprecation warning for Python 3.5 in `setup.py`~
- [x] Add deprecation warning for Python 3.5 in `openquake/commands/__main__.py`

### Documentation  (#3868)

- [x] Development install
- [x] Other references to Python 3.5 and snippets

### Other business

- [x] oq-engine-celery

**Comment by micheles** [comment]
Note: one should remember to change `openquake/commands/__main__.py`.

**Comment by daniviga** [comment]
Good catch @micheles

**Comment by daniviga** [comment]
Closing
