### ISSUE TITLE
Unusual high oq-dbserver CPU load

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3877]
The CPU load of the `oq-dbserver` process is > 100% of a 2.2GHz Xeon E5 (Wilson) when just two console logs are opened via the WebUI.

![screenshot from 2018-07-23 16-50-02](https://user-images.githubusercontent.com/1818657/43084509-1d362c50-8e99-11e8-91fb-83e09787d3b3.png)

This is higher that I would expect and may be a problem with multiple users running the WebUI, taking into account how much powerful is that machine.

I was not fully able to reproduce the issue locally: my suspect is that the load is caused by the size of the SQLite3 database and the amount of record in the `log` table (1'408'494 records as writing).

**Comment by micheles** [comment]
Well, since the sqlite db is so large I do not see anything bad in removing old calculations; then we can see if the problem disappear. Probably it is enough to purge the log table rather than the job table.

**Comment by daniviga** [comment]
On tests made on my local machine (much less powerful) with the full DB I found that adding an index to the `job_id` column of `log` reduces the CPU load to less then 1/4.

```SQL
CREATE INDEX log_job_id on log (job_id)
```

@micheles there's any reason why we don't have any index in our DB?

**Comment by daniviga** [comment]
It also looks like that the auto indexing feature of SQLite was not used on our tables:

```sql
SELECT * FROM sqlite_master WHERE type = 'index' and name LIKE 'sqlite_auto%';
type|name|tbl_name|rootpage|sql
index|sqlite_autoindex_revision_info_1|revision_info|10|
index|sqlite_autoindex_auth_group_1|auth_group|18|
index|sqlite_autoindex_auth_group_permissions_1|auth_group_permissions|21|
index|sqlite_autoindex_auth_user_groups_1|auth_user_groups|26|
index|sqlite_autoindex_auth_user_user_permissions_1|auth_user_user_permissions|28|
index|sqlite_autoindex_django_content_type_1|django_content_type|15|
index|sqlite_autoindex_auth_permission_1|auth_permission|43|
index|sqlite_autoindex_django_session_1|django_session|23|
index|sqlite_autoindex_auth_user_1|auth_user|211312|
```
