### ISSUE TITLE
New IMTs and corresponding GMPEs

### ISSUE THREAD

**Issue by pheresi** [gem/oq-engine#3883]
Different authors have proposed novel IMTs that are better correlated with damage and collapse. Specifically, these are SDI (inelastic displacement ordinate), SAAVG (average Sa) and FIV3 (filtered incremental velocity 3). Ground motion prediction models have been implemented and I'll include them in separate pull requests:

- [x] Changes in openquake/hazardlib/imt.py, including the definitions of the new IMTs

- [x] Changes in openquake/hazardlib/tests/gsim/check_gsim.py, in order to be able to read test tables for GMPEs of these new IMs

- [x] Changes in openquake/commonlib/oqvalidation.py, in order to check new IMTs 

- [ ] New gsim and gsim_test files for the GMPM of SDI

- [ ] New gsim and gsim_test files for the GMPM of SAAVG

- [ ] New gsim and gsim_test files for the GMPM of FIV3

**Comment by micheles** [comment]
Nothing is happening here, so I am closing the ticket.
