### ISSUE TITLE
Files with '__main__' that are not scripts

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3892]
```
openquake/baselib/runtests.py
openquake/baselib/workerpool.py
openquake/commonlib/writers.py
openquake/engine/tools/correct_complex_sources.py
openquake/engine/tools/viewlog.py
openquake/hazardlib/calc/hazard_curve.py
openquake/hazardlib/nrml.py
openquake/server/dbserver.py
openquake/server/db/upgrade_manager.py
```

these files contain a `__main__` but are not marked executable on the FS and do not provide a `#!`.

We need to check them.

**Comment by micheles** [comment]
There is no rule that a file with a `__main__` must be executable. So I would do nothing, these files are meant to be called with a `python` in front, not as standalone scripts.
