### ISSUE TITLE
Python 3 shebangs

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3893]
New scripts added must have a shebang pointing to python3:

`#!/usr/bin/env python3`

1. we are not compatible with python2 anymore
2. packaging systems like `rpm` check the shebangs and add dependencies automatically, so having wrong shebangs will add unwanted dependencies

Existing shebangs are fixed by #3889 but we need to be careful with new scripts!

**Comment by micheles** [comment]
I think we should add a travis check: if a script with the wrong shebang is added, travis should complain.
