### ISSUE TITLE
Cache outputs generated by the WebUI

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3899]
Exporting outputs via the WebUI is an expensive operation: i.e. an hmap for a national wide computation takes, on Wilson, 10 minutes.

With the current workflow the output is dumped to `/tmp` and then sent via HTTP.
Files in `/tmp` are created with a random name, so a new export is always performed even if a copy of it already exists on the filesystem. This is very inefficient from both the CPU and disk space usage.

We should generate outputs with a known name and before asking the engine to export an output we can check if the file already exists on the filesystem.

I don't see issues with cache invalidation, in the sense that if we use a combination of ID and checksum we can be sure that the output on fs is always the right one (once a calculation is complete it should be immutable).

**Comment by daniviga** [comment]
A real example workflow (/cc @pslh):

- open the QGIS plugin, select a job and select 'load layer' for hmaps
- wait 10 minutes
- select a IMT/PoE/rlz: the layer is loaded in QGIS in a second
- I need a different PoE
- open the QGIS plugin, select a job and select 'load layer' for hmaps
- wait 10 minutes
- select the wanted PoE: layer is loaded in QGIS in a second

**Total time: 20' 2'**

Having the output cache it would be:

- open the QGIS plugin, select a job and select 'load layer' for hmaps
- wait 10 minutes
- select a IMT/PoE/rlz: the layer is loaded in QGIS in a second (total time 10' 1")
- I need a different PoE
- open the QGIS plugin, select a job and select 'load layer' for hmaps

**Total time: 10' 2'**
- select the wanted PoE: layer is loaded in QGIS in a second

Indeed with 5 layers the difference will be 50' 5" vs 10' 4"

**Comment by daniviga** [comment]
Another solution would be caching the outputs on the QGIS side.

**Comment by micheles** [comment]
I do not like caching the outputs on the QGIS side. Consider for instance an output generated by Julio that must be seen by 3-4 other people in the hazard group (+ other people in Colombia). If we cache it server-side we can do the work only once. To start, we could store the outputs in some subdirectory of /tmp (assuming we have enough space there). We could use the following logic:

1. If the calculation was started with `oq engine` do nothing, the export will be done later only if the user calls `oq engine --export-output`, without any cache.
2. If the calculation was started from the webui at the end of it runs an `oq extract hcurves/all`; then the outputs will be available in the cache until the cache is cleared.

I have to figure out how to make the export work for different export types (i.e. XML, CSV) but probably we can produce all of them from an intermediate representation in HDF5 stored in the cache.

**Comment by micheles** [comment]
After some more reflection and analysis I changed my mind. There is a way we can reduce the current 10 minutes generation time to virtually 0: just store the hazard curves/maps in the datastore in exactly the same way the QGIS plugin is expecting them. Currently the storage is different for space sake (it is more compact, not storing the zeros) but then at each call it has be converted. It is best to perform the conversion only once during the calculation runtime and to save a larger datastore file: then the extract/export will become ultra-fast, essentially making caching the outputs on the file system unneeded.
