### ISSUE TITLE
Investigate limits on the number of columns in a QGIS layer

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3906]
According to @daniviga, if a QGIS layer has more than 1000 columns it becomes very slow. Check how bad is the situation in real calculations with hazard curves and maps. I need a calculation ID. Solving this may require major changes on the engine side, since the whole approach to exporting hazard curves and maps was designed under the assumption that we never had cases with thousands of columns and/or this was not a problem on the QGIS side. Instead it seems that Julio's calculations are in this range.

**Comment by daniviga** [comment]
Anyway, Paolo in working on the filtering on QGIS side (like we do with
uhs), which will remove or at least mitigate most of the issues on the QGIS
side. In the specific case cited by Michele we had thousand of colums
(something like 6poes*13imt on 96k points) but only 5poes*3imt where
actually needed in QGIS.

---
Daniele Viganò
http://daniele.vigano.me

On mobile, please excuse my brevity.

**Comment by micheles** [comment]
While the work that Paolo is doing is useful, it will not solve the issue without help from the server side.
I want to make the extraction on the server fast, so that the original design can be followed: get everything in a single call (but fast) and then have QGIS select what IMTs/PoEs to visualize.
If this is not enough we will have to change the extract API, make it possible to pass to it filtering parameters and also change the way the hazard maps are stored, i.e. use different datasets for different IMT/PoE. This is a lot of work that I would prefer to avoid. Notice that e 6 poes * 13 imt on 96k points with 3 statistics means ~86 MB of data for the hazard maps, not so difficult to transfer. For the hazard curves it can be worse, we will have to see the performance in the real case and then decide.

**Comment by micheles** [comment]
After the work done by Paolo here https://github.com/gem/oq-irmt-qgis/pull/491 there should be no problem  anymore. Closing for the moment.
