### ISSUE TITLE
Include update of BC Hydro Subduction Model

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#3911]
An update of the BC Hydro Subduction model (Abrahamson et al. 2016 - implemented in `abrahamson_2015.py`) using the new NGA Subduction data has recently been published (https://peer.berkeley.edu/sites/default/files/2018_02_final.pdf). Add to OQ, including regional calibrations.

**Comment by micheles** [comment]
Implemented in https://github.com/gem/oq-engine/pull/4664

**Comment by g-weatherill** [comment]
Sorry, Michele this issue is different from the one closed in #4664. There is a new GMPE waiting to be implemented which is an actual update to the BC Hydro model, not the adjusted version that was implemented for SERA. I'm blocked on that particular implementation because of problems sourcing correct implementations of that particular model for the tests, so if you want to close it anyway then I'm OK with it, it should just be closed for the correct reason.

**Comment by micheles** [comment]
Ops! I have reopened the issue then.

**Comment by cvanhoutte** [comment]
Hi both, I'm starting to think along similar lines. Did the issue with finding the correct implementation for tests get resolved? Just wondering if there are any roadblocks if I quickly scrape something together from the report.

**Comment by g-weatherill** [comment]
I still don't have a complete independent implementation to build the test tables for the different regionalisations, but as I already have the model implemented in an OQ format I can put together a simpler test table for the Cascadia coefficient set (which is the only one the model is recommended for) and open a PR with that.

**Comment by cvanhoutte** [comment]
Sounds good to me. Thanks @g-weatherill
