### ISSUE TITLE
GSIM Deprecation warning - choose model to suggest as replacement

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#3927]
When adding a deprecation warning to a GSIM one may wish to direct the user to a different GSIM than the class inherited by the GMPE. Add possibility of choosing the suggested GSIM to be indicated in the deprecation message.

**Comment by micheles** [comment]
More in detail now we get
```
DeprecationWarning: MontalvaEtAl2016SSlab is deprecated - use AbrahamsonEtAl2015SSlab instead
```
while it should point out to `MontalvaEtAl2017SSlab`, so we have a bug.
