### ISSUE TITLE
Set mult_node = true in engine-master and engine-worker

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3950]
`engine-master` and `engine-worker` packages should set `mult_node = true` in `openquake.cfg`.

This could be not so easy since the `/etc/openquake/openquake.cfg` package is owned by `python-oq-engine` and:

- it cannot be easily replaced by another package
- if it's changed on the fly (i.e. using sed) it will cause issues during the next upgrade

**Comment by micheles** [comment]
I think it should be `multi_node = true` (lowercase) for compatibility with the other flags.

**Comment by micheles** [comment]
This is not a release blocker, everything will work even if multi_node is incorrectly set to false, cluster users will just get an (annoying but correct) warning.

**Comment by daniviga** [comment]
> This is not a release blocker, everything will work even if multi_node is incorrectly set to false, cluster users will just get an (annoying but correct) warning.

it's set for 3.3.0

**Comment by micheles** [comment]
If it is easy I would do it for 3.2, if it is difficult for 3.3.

**Comment by daniviga** [comment]
Not easy and I'm lacking the time required for it, that's why I marked it for 3.3.0

**Comment by daniviga** [comment]
I would close this for now: the admin needs anyway to change the network configuration, so...
