### ISSUE TITLE
missing link in Eventbased output

### ISSUE THREAD

**Issue by patriceTsch** [gem/oq-engine#4046]
In the csv files there is a missing link between the rupture file and the gmfdata file. 
The link is there in the xml ruptures file. The link (rupid*multiplicity) is missing in the csv files. Can you please output one more additional csv file to generate the link? 
thank you

**Comment by micheles** [comment]
In the gmf_data file there is a field called `eid`, short for event ID. If the question is "how do you get the rupture that generated the GMF associate to a given event?" in current master (and in the next version of the engine) there is a clear answer: one can extract the rup_id from the eid with the formula
```
rup_id = eid // 2 ** 32
```
Is this what you are asking?

**Comment by micheles** [comment]
Notice that this formula works only in master and not the released versions of the engine.

**Comment by micheles** [comment]
This has changed again with respect to a week ago. The formula `rup_id = eid // (2 ** 32)` is still correct, but only for the eid stored in the `events` table, not for the one stored in the `gmf_data` table. All those things are implementation details subject to change.
