### ISSUE TITLE
Make the tag names and occupancies lowercase

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4047]
Otherwise the risk team will make me go crazy.

**Comment by micheles** [comment]
The idea is that user can write the tag names in any case (to avoid breaking old calculations), but when stored they become lowercase. Lowercase is the recommended way.

**Comment by CatalinaYepes** [comment]
I don't agree that the tags should be forced to be lower case. That will break future joins or matches for which the tags are intended for.
