### ISSUE TITLE
missing meta data in realizationIDs

### ISSUE THREAD

**Issue by patriceTsch** [gem/oq-engine#4048]
I miss the (in my view crucial) information about which eps_inter sample was chosen for a given eventID (in the EventBasedPSHA as well as the Scenario engine). Can you kindly add that do all the outputs?

**Comment by mmpagani** [comment]
Dear Patrice thanks for the note. We will certainly add this information.

**Comment by micheles** [comment]
We need to return the $\sigma$ and the $\epsilon$ from the GmfComputer.

There are three cases:
1. truncation_level == 0, the GmfComputer must return 0, 0
2. gsim.DEFINED_FOR_STANDARD_DEVIATION_TYPES == {StdDev.TOTAL}, must return NaN, NaN
3.must return `stddev_inter`  and `rvs(distribution, num_events)`
