### ISSUE TITLE
ZMQ endpoint is not read from the `openquake.cfg` on workers

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4089]
The `host =` setting in the `[dbserver]` section is not read by the workers which are instead using the value coming from the master node (where it could be `localhost`).

We should either properly read that setting in the workers (which is the URI where to send back results) or document the behavior better.

**Comment by micheles** [comment]
I would document that, but where?

**Comment by daniviga** [comment]
I will add a comment in the 

> I would document that, but where?

See #4316
