### ISSUE TITLE
 The site term should not be hardcoded as a class method

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#4090]
I would then move BA08_AB06 in a separate file.

_Originally posted by @klunk386 in https://github.com/gem/oq-engine/pull/4088#issuecomment-430610563_

This would require a third level of nesting that would make the testing of this feature even more complex. I would stick with the current (simple) implementation and leave space for the future to extend it into something more flexible.

Moreover, in both cases, you need in the engine an implementation of the site term. Hence it's just a matter of deciding where you prefer to have the specific site term implementation.

**Comment by micheles** [comment]
Let's keep the status quo.
