### ISSUE TITLE
Running risk on top of hazard of another user does not work

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4113]
When passing an hazard computation (via `--hc`) ran by a different user to run the risk the calculation will fails because the engine is looking for the datastore in the wrong oqdata (i.e. the new user one instead of the real owner). 

I don't know if we want this feature anyway, but in such case we should report that the calculation ID is not valid otherwise we must (when using `oq engine`) look at the DB at take the real datastore path from there.

**Comment by micheles** [comment]
I fear the change in https://github.com/gem/oq-engine/issues/4114 broke this :-(
