### ISSUE TITLE
Make -1 relative to the user that is executing the command

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4114]
`-1` in calc_id is referring to the last calculation available on the cluster and *not* to the last calculation a user has run.

This makes `oq show` and `oq export` almost useless on a multi-user installation, since in batch operation it may happen that another user fires a calculation between `oq engine --run` and the following `oq` operation.

This change will not broke any script used in development/ci since we always work in a single user mode there. If we want to keep the feature of an absolute `-1` calc_id we should change the format (like `%-1`?).

This is actually preventing script made by @nastasi-oq for the GRM to work properly.
/cc @raoanirudh @CatalinaYepes

**Comment by micheles** [comment]
While I could fix the `-1` behavior for `oq engine`, I think you are much better off changing Matteo's script NOT to rely on the -1 behavior that was born as a hack for the single user mode. Just remove the `--hc` functionality and do something like
```
	oq1 engine --run Jobs/job_hazard_${country}.ini  Jobs/job_risk_${country}.ini 
```
BTW, there is no need to save the .log files, Jenkins is catching the log and the log is also stored in the database, so it can be easily retrieved.

NB: using `oq export` without an explicit calculation ID is a disaster. `oq export` DOES NOT RELY ON THE DB, so it cannot know the username and it cannot be fixed. It was born as a secret utility command for the single user mode, the perversion is to use it as if it was a production functionality. We need to think of a way to give back to bash the calculation ID, like for instance printing it on a know file and reading it from there. I am open to suggestions.

**Comment by micheles** [comment]
Or, even better, I will write a Python script that calls the engine as a library and does the right thing.
There is no reason to do everything in bash!

**Comment by micheles** [comment]
Looking at the issue more carefully, I see that there was actually a regression. The engine used to work correctly but while changing things so that `oq show` and `oq export` could show and exports the results of computations made by other people, unintentionally I broke `oq engine --hc`. So, it is a bug and should be fixed.
