### ISSUE TITLE
Include all hdf5 files used by tests in packages?

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4138]
We are not including all the hdf5 used by tests in the packaged version of OQ (i.e. files in `openquake/hazardlib/gsim/nga_east_tables`). Shall we include everything? This will increase the size of packages by some tents of MB.

**Comment by mmpagani** [comment]
In principle, those are also files that should be included. However, I wonder if they could be packaged separately into something called oq-engine-tests-data (or similar). In this way, we keep the engine light and the ones interested can have all is necessary to run all the tests.

**Comment by daniviga** [comment]
See #4139
