### ISSUE TITLE
Normalize the IMTs better

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4152]
I.e. SA(1) and SA(1.0) should be the same. This is already done, but it does not work in this situation: https://oq1.wilson.openquake.org/v1/calc/20349/log/:

The problem is that job_hazard has a section

[vulnerability]
structural_vulnerability_file = ../Vulnerability/vul_centralAsia_V06-11-2018-1014.xml

while the job_risk has

[vulnerability]
structural_vulnerability_file = ../Vulnerability/vul_centralAsia_V06-11-2018-1014.xml
occupants_vulnerability_file = ../Vulnerability/ftl_CentralAsia_V06-11-2018-1014.xml

This also happens for Ecuador, where the hazard has

intensity_measure_types = PGA, SA(0.3), SA(0.6), SA(1.0)

while the vulnerability functions have  PGA, SA(0.3), SA(0.6), SA(1).

**Comment by raoanirudh** [comment]
Same issue as before, but now while reading the `minimum_intensity` from the job file: 

`minimum_intensity = {"SA(0.20)": 0.05, "SA(0.3)": 0.05, "SA(0.5)": 0.05, "SA(0.75)": 0.05, "SA(1.0)": 0.05}`

SA(0.20) is not recognized to be the same as SA(0.2), which instead gets assigned a `minimum_intensity` of 0:

```
[#1 INFO] minimum_intensity={'SA(0.20)': 0.05, 'SA(0.3)': 0.05, 'SA(0.5)': 0.05, 'SA(0.75)': 0.05, 'SA(1.0)': 0.05, 'SA(0.2)': 0}
```

Sample job exhibiting the issue attached.

[min_iml_test.zip](https://github.com/gem/oq-engine/files/10861398/min_iml_test.zip)

Bug report and test files courtesy of Mohsen Kohrangi, as reported on the OpenQuake users' forum: https://groups.google.com/g/openquake-users/c/eFYb1_sXk7M/m/6peQ3aVhAwAJ
