### ISSUE TITLE
Add a check for missing occupants column in the exposure

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4176]
The error should appear at the beginning, not in the middle of the computation. This happened to Anirudh for Japan.

**Comment by micheles** [comment]
Blocked until somebody gives me an example exhibiting the problem.

**Comment by raoanirudh** [comment]
> .. an example exhibiting the problem.

[event_based_risk.zip](https://github.com/gem/oq-engine/files/2940537/event_based_risk.zip)
