### ISSUE TITLE
Job termination and cleanup

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4196]
It happens very often that when a job does not finish cleanly (i.e. out of memory, abort, generic error) processes aren't cleaned properly and are consuming resources until are killed via sigkill.

It looks to me that those kind of issues started when we moved from processpool to process spawn.

This issue requires lot of effort and a free cluster.

**Comment by micheles** [comment]
The issue should have disappeared because now the prefiltering is performed on the workers via celery (since https://github.com/gem/oq-engine/pull/4404) and we are not spawning a processpool anymore. We will reopen it if it will happen again.
