### ISSUE TITLE
Incorrect calculation ids displayed in the logfile

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#4211]
https://console.openquake.org/job/OQ2%20on%20Wilson/56/console

On the cluster, a calculation run via Jenkins that should have had an id of #21016 is shown in the log as #21011. The outputs are saved correctly to the datastore for #21016.

```sh
[2018-11-21 18:45:43,479 #21011 INFO] Exposing the outputs to the database
[2018-11-21 18:45:52,519 #21011 INFO] Calculation 21016 finished correctly in 676 seconds
```

**Comment by daniviga** [comment]
I see also that several calculation logs cannot be displayed on the webui and the mosaic CI failed because a unique constraints violation
