### ISSUE TITLE
characterstics earthqauke occuring in major active fault zones

### ISSUE THREAD

**Issue by SHIVAM2607** [gem/oq-engine#4282]
Hi,

can anyone suggest me that "characterstics earthqauke occuring in major active fault zones", this types of faults should be modelled as complex fault or characterstics faults in openquake. 

thanks

**Comment by SHIVAM2607** [comment]
Hi, @michele

can anyone suggest me that "characterstics earthqauke occuring in major active fault zones", this types of faults should be modelled as complex fault or characterstics faults in openquake.

thanks

**Comment by daniviga** [comment]
Please use the support forum for support requests: https://groups.google.com/forum/#!forum/openquake-users
