### ISSUE TITLE
In event based with sampling, should we go back to identical realization weights?

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4308]
Then we would not need to keep track of the realization weights when computing the stats. The line to change in in commonlib.source.CompositionInfo._get_rlzs:

```python
    def _get_rlzs(self, smodel, all_rlzs, seed):
        if self.num_samples:
            # NB: the weights are considered when combining the results, not
            # when sampling, therefore there are no weights in the function
            # numpy.random.choice below
            numpy.random.seed(seed)
            idxs = numpy.random.choice(len(all_rlzs), smodel.samples)
            rlzs = [all_rlzs[idx] for idx in idxs]
        ...
```
If we restore the weights in `numpy.random.choice`, then the realizations could have all the same weight.

Notice that we cannot do the change in the classical calculator otherwise we would lose the
IMT-dependent weights feature.

NB: this relevant for CatRisk applications, passing to third parties information about the realizations is hard, but if all the realization have the same weight it is easy. Then a CatRisk company would not need to distinguish the losses by event depending on the realization they belong to.

**Comment by raoanirudh** [comment]
Relevant discussion from earlier about computing the mean and quantiles for event based calculations using sampling instead of full enumeration: https://github.com/gem/oq-hazardlib/issues/577

**Comment by micheles** [comment]
You have a really good memory, @raoanirudh , but that PR is not relevant (it had to do with `None` weights instead of `1/R` weights and I am not proposing to go back to `None` weights). Anyway, after thinking a couple of months on the issue, I think we should keep the status quo. The change would be big and it would conflict with the recent new feature of IMT-dependent weights, so I am closing the issue.
