### ISSUE TITLE
Debian installation - What is the oq-python3.6 package for?

### ISSUE THREAD

**Issue by pini-gh** [gem/oq-engine#4333]
Hi,
I'm trying to understand the prerequisites for installing oq-engine on Debian boxes. What does the oq-python3.6 package bring over python3.5 from Debian Stretch?
Thanks.

**Comment by nastasi-oq** [comment]
``oq-python3.6`` package don't offer itself as system-wide ``python3`` and depends on some package like ``python3-sphinx`` that depends on it (``python3:any``) so it is an acceptable side-effect.
