### ISSUE TITLE
Remove restriction that all site depths must be zero for Mesh.get_distance_matrix()

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#4427]
The `get_distance_matrix` function is called when applying spatial correlation and currently has an assertion that all depths should be zero. This was OK when site depth/elevation was always considered to be 0, but now that more 3D distances for sites can be used then this check prevents one from running spatial correlation when sites are at depths different from zero. 

There are two options:
1. Given that the spatial correlation models have tended to ignore depths in their distance definitions then simply removing the `assert (self.depths==0).all()` would mean that 2D distances would still be used for the spatial correlation model and simply depth/elevation differences would still be ignored (probably the preferred/easiest option).

2. Modify `openquake.hazardlib.geo.geodetic.geodetic_distance` to account for depth\elevation (optionally) in order to account for 3D distance. This is not entirely faithful to the definition of the spatial correlation models but would very likely be inconsequential most of the time given that elevation differences would be substantially smaller than horizontal distances.

**Comment by mmpagani** [comment]
I am fine with option one. Perhaps if sites have a depth (i.e. elevation) different than 0 we can raise a warning.
