### ISSUE TITLE
hmtk tools error

### ISSUE THREAD

**Issue by NimaDolatabadi** [gem/oq-engine#4496]
I'm trying to decluster the catalogue but i'm experiencing some issues i wrote below:
`from openquake.hmtk.parsers.catalogue import CsvCatalogueParser
catalogue_filename = 'hmtk.csv'
#catalogue_filename = 'All-in-one.csv'
parser = CsvCatalogueParser(catalogue_filename)
catalogue = parser.read_file()
catalogue.data ['magnitude']
catalogue.load_to_array (['year', 'longitude', 'latitude',
				'depth', 'magnitude'])
#========================================================#
import numpy
data = numpy.genfromtxt('hmtk.csv', skip_header=0)
headers=['longitude', 'latitude', 'year', 'month',
	 'day', 'magnitude', 'depth', 'hour',
	 'minute', 'second']
from openquake.hmtk.seismicity.catalogue import Catalogue
catalogue = Catalogue()

catalogue.load_from_array(data, headers)

import numpy as np
import matplotlib.pyplot as plt

depth_bins = np.arange(0. , 110. , 10.)

depth_hist = catalogue.get_depth_distribution (depth_bins, normalisation=True)

from openquake.hmtk.plotting.seismicity.catalogue import\
				plotsplot_depth_histogram
depth_bin = 5.0
plot_depth_histogram (catalogue, depth_bin, filename = "dep-hist.eps", filetype = "eps")`

my code just to get a simple histogram of depth is this and my catalogue is about 5515 rows long. and i'm having the error below when I type `python3 <my-code.py>`:

```
Traceback (most recent call last):
  File "decluster.py", line 27, in <module>
    catalogue.load_from_array(data, headers)
  File "/opt/openquake/lib/python3/dist-packages/openquake/hmtk/seismicity/catalogue.py", line 248, in load_from_array
    if len(keys) != np.shape(data_array)[1]:
```

regards

**Comment by rcgee** [comment]
Hi Nima,

Thanks for getting in touch with us.

Please send an email to hazard@globalquakemodel.org

And we will provide you with an example that you can test to see if the
issue persists.

Best regards

**Comment by NimaDolatabadi** [comment]
I have sent many messages but no answer was replied. So I decided to post it in your forum.Regards






>> Nima Dolatabadi

>> MSc. Geophysics/seismology

>> Department Of Earth Physics

>> Institute of Geophysics

>> University of Tehran

>> Tehran Iran

T: +989106721789

E: syn_org939@rocketmail.com 
 
  On Tue, Mar 5, 2019 at 14:27, rcgee<notifications@github.com> wrote:   Hi Nima,

Thanks for getting in touch with us.

Please send an email to hazard@globalquakemodel.org

And we will provide you with an example that you can test to see if the
issue persists.

Best regards

**Comment by mmpagani** [comment]
Presumably your catalogue is badly formatted.


> I have sent many messages but no answer was replied. So I decided to 
> post it in your forum.Regards
>
>
>
>
>
>
>>> Nima Dolatabadi
>
>>>  MSc. Geophysics/seismology
>
>>>  Department Of Earth Physics
>
>>>  Institute of Geophysics
>
>>>  University of Tehran
>
>>>  Tehran Iran
>
> T: +989106721789
>
> E: syn_org939@rocketmail.com
>

**Comment by daniviga** [comment]
Please continue here https://groups.google.com/forum/#!topic/openquake-users/L6RxN29yiMs
