### ISSUE TITLE
Volcano scenario calculator

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#4519]
A new `volcano_scenario` calculator will be included into the OQ engine, as part of the milestones proposed in CRAVE project.

The attached _.zip_ file includes the required input files for a volcano scenario.
[volcano_input_files.zip](https://github.com/gem/oq-engine/files/2945492/volcano_input_files.zip)

The following steps will be followed:

1. The calculator will start from precomputed hazard footprints in csv format (units should be consistent with fragility/vulnerability inputs).
Four hazard perils will be considered:
- Lava flow (binary: 1 for affected, 0 for not affected)
- Lahars (binary: 1 for affected, 0 for not affected)
- Pyroclastic flow (binary: 1 for affected, 0 for not affected)
- Ash fall (continuous phenomena similar to ground shaking). The intensity is most commonly measured as thickness of ash fall (mm).

2. An exposure model will describe the asset location and characteristics of the structures, following the current OpenQuake format. It is mandatory to include the number of buildings per asset. Number of occupants is optional.

3. Fragility, consequence and vulnerability models can be assigned to ash_fall phenomena.
- Users can assign Fragility and Consequence models, or
- Users can assign Fragility and Vulnerability models
- It is not possible to assign at the same time Consequence and Vulnerability models

4. Fagility and Vulnerability for `lava_flow`, `lahars` and `pyroclastic_flow` is assumed to be binary: 
- 1 for total_damage → if the hazard footprint is close to the asset location (use param `asset_hazard_distance`)
- 0 for no_damage → if the hazard footprint is far from the asset location (use param `asset_hazard_distance`)

5. The outputs for this calculation will be:

- **Hazard footprints**
Possibility to visualize and download the hazard footprints in QGIS plugin

- **Asset hazard**
For each asset in the exposure model, identify the level of hazard.
The following image presents an example of the output format:
<img width="645" alt="volcano_asset_hazard" src="https://user-images.githubusercontent.com/6975363/54024743-d96acb80-4198-11e9-8e79-6d1dd0951a88.png">

- **Volcanic risk**
For each peril, present the number of affected buildings, occupants (if included in exposure model) and economic cost.
The following image presents an example of the output format:
<img width="1048" alt="volcano_risk" src="https://user-images.githubusercontent.com/6975363/54024751-e091d980-4198-11e9-86bc-757db2210d63.png">

**NOTE:** The affected occupants for `ash_fall` is missing

**Comment by CatalinaYepes** [comment]
The CRAVE collaborators in Colombia have asked to consider for `ash_fall` the possibility to estimate the losses for dry and humid conditions.

Therefore, a new parameter will be included in the `job.ini` file, called `humidity_amplification_factor`, which indicates the factor to multiply the dry density of the ash in humid conditions.

The outputs will include the resulting values as follow:

- *Asset Hazard*
Report the ash millimetres in: `ash_fall_dry` and `ash_fall_humid`

- *Volcanic Risk*
Split this outputs in two files: one file for ash_fall risk, and one file for other perils
Include results for ash_fall_dry and ash_fall_humid conditions

**Comment by CatalinaYepes** [comment]
The hazard input footprint will have the following format:

Possible volcano perils: LAVA, LAHARS, PYRO, ASH

| Volcano peril and units: | LAVA  | Binary |
| ------------- | ------------- | ------------- |
| lon | lat | intensity |
| ...  | ...  | ... |

**Comment by julgp** [comment]
Ok, that is possible, may be would be better is the perils is named as: LAVAFLOW to be consistent with the volcano hazard modellers

**Comment by CatalinaYepes** [comment]
After some discussions with @micheles and @ptormene, here is the new proposal for **volcano scenario calculation** outputs:

The user will see an output.csv file per peril:
- ash_risk.csv
- lahars_risk.csv
- lava_risk.csv
- pyroclastic_risk.csv

For the three binary perils (`lahars`, `lava` and `pyroclastic`) the output will be as follow:
<img width="877" alt="binary_perils_risk" src="https://user-images.githubusercontent.com/6975363/54989014-ef112b00-4fb7-11e9-81d3-58abdf1253bb.png">

For `ash fall`, the output will include dry and wet conditions:
<img width="1282" alt="ash_risk" src="https://user-images.githubusercontent.com/6975363/54989025-f6383900-4fb7-11e9-83e1-e32028efa1fe.png">

**Comment by CatalinaYepes** [comment]
For the QGIS plugin, @ptormene, the `Load layer` dialogue can have the following options:

1) Drop down: **Visualize**
	- Exposure
	- Risk (selected by default)

2) Drop down: **Category**
	- Buildings
	- Occupants (depends if specified in exposure or not)
	- Structural
	- Non structural (depends if specified in exposure or not)
	- ...

3) Drop down: **Taxonomy**
	Same as current option for earthquakes

**`If Peril == ASH`**

4) Drop down: **Damage state** 
	Get damage states from calculations params
	- no_damage
	- slight_damage
	- collapse

5) Future discussion: Aggregation by tags
