### ISSUE TITLE
Automatically import code in the input directory

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4536]
This is useful to run code that contains new GMPEs not in hazardlib. `oq zip` should be extended to zip all the .py files there, recursively. Having people posting untrusted code to the WebAPI is a security concern, so we could disable the feature in that case. Still, we already quite exposed, since is really easy to send a calculation that will put the cluster on its kneel, just by using a  small discretization parameter.
Right now, the feature is needed to run Murray's calculation that have their own GMPEs: copying the GMPEs in hazardlib is inconvenient and ugly, since it "pollutes" the repository.

**Comment by mmpagani** [comment]
While I understand the specific need I am not in favour of supporting this strategy as a general feature. The right way to add code is through a PR; if users wish to keep their own local code they must handle this.

**Comment by micheles** [comment]
After https://github.com/gem/oq-engine/pull/4647 the GMPETables for Canada are included in the engine code base, so the main cause for this feature request has disappeared.
