### ISSUE TITLE
Try to unify the losses_by_event exporters

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4541]
It should work the same in scenario_risk, event_based_risk and ebrisk.

**Comment by raoanirudh** [comment]
The `losses_by_event` output for the `event_based_risk` calculator includes the fields `event_id`, `rlz_id`, `rup_id`, and `year`, followed by the respective portfolio losses for each loss category. 

In comparison, the `losses_by_event` output for the `ebrisk` calculator is currently missing the `rlz_id`, `rup_id`, and `year` fields, which would be very useful to include in the output csv, as it is difficult for a user to obtain these fields through alternate means.
