### ISSUE TITLE
Ask Cata and Jamal why they need the agg_loss_table which is deprecated

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4542]
Probably they want an Extractor instead.

**Comment by raoanirudh** [comment]
The `agg_loss_table` output is essentially the same as the `losses_by_event` output, except that it has four additional columns that give the user some information about the rupture related to each loss event: `magnitude`, `centroid_lon`, `centroid_lat`, `centroid_depth`. If it can be made possible to get the rupture information for selected events in the event loss table through the QGIS plugin, it should be ok to remove the `agg_loss_table` output and keep only the `losses_by_event` output. The `losses_by_event` output should include the realization id, which is missing currently.

**Comment by CatalinaYepes** [comment]
It is important to include in the outputs the `rupture_id`, `year` of each event, and the `realization_id`. Currently the losses_by_event is only providing information about `eid, structural`.  For example, this information will be useful if a user is interested in computing the aggregated loss curves considering the losses per year and not per event, or if the user wants to make some statistics about losses per TRT, magnitude... (by later joining the losses_by_event with the ruptures.csv).
