### ISSUE TITLE
Add the ability to define dynamic IMTs in the job.ini

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4551]
Such IMTs would live outside of the code base. Their only purpose is to check the units used in the risk functions with the ones requested in the job.ini. We could use the parameter `intensity_measure_types` for that.

Requested by @pslh

**Comment by micheles** [comment]
Actually the change in https://github.com/gem/oq-engine/pull/4851/files proves that there is no need to define IMTs in hazardlib for the multi-risk calculator, so there is nothing to do.

**Comment by pslh** [comment]
0 change fixes - my favourite!
