### ISSUE TITLE
Should I remove the computation of individual loss curves and maps from event_based_risk?

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4594]
My understanding is that the individual curves are not interesting, the interesting curves are the aggregated ones (for instance aggregated on geographic regions). Since the aggregate curves cannot be extracted from the individual curves, what's the point of calculating them? Especially since the computation is expensive. Users wanting the aggregate curves should use the ebrisk calculator, not the event_based_risk calculator.

**Comment by raoanirudh** [comment]
No, we cannot remove these outputs. The individual asset loss curves and probabilistic loss maps are being used by several users.

**Comment by micheles** [comment]
I thought the only user was Murray.
