### ISSUE TITLE
Add a job status sanity check in the DbServer

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4606]
We should add a thread in the DbServer that perform a sanity check over jobs: when it founds calculation in `executing` or `submitted` without an existing `pid` associated it will mark them as `failed` (this happens when a job is `SIGKILL`ed)

**Comment by pslh** [comment]
We should consider using a separate "killed" status for jobs that have been killed; it might be useful to distinguish between a calculation which failed due to a syntax error in an .ini file as opposed to one which is valid but which was killed due to an OOM event.

**Comment by micheles** [comment]
We have two states 'failed' (there was an error) and 'aborted' (killed on purpose). When there is an out of memory the calculation stays in 'executing' and the sanity check should fix that. I think 'failed' is better than 'aborted' in that case, so I would keep Daniele's suggestion.

**Comment by micheles** [comment]
After thinking on this, I do not want to use another thread in the DbServer. It is enough to fix the status in engine/engine.py. before the check in `poll_queue`.
