### ISSUE TITLE
Average losses reported for event_based_risk with sampling are incorrect

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#4620]
The attached job has three sampled branches. The numbers in the `avg_losses-mean` output should be the (ordinary, non-weighted) averages of the corresponding numbers in the three branch outputs `avg_losses-rlz-000`, `avg_losses-rlz-001`, and `avg_losses-rlz-002`. However, in the current master, they are slightly different values.

[sampling.zip](https://github.com/gem/oq-engine/files/3068061/sampling.zip)

**Comment by raoanirudh** [comment]
The `avg_loss_mean` output for the attached calculation is the following table:

| asset_ref | city          | county       | state      | taxonomy | tract  | zip   | lon      | lat    | nonstructural | structural |
|-----------|---------------|--------------|------------|----------|--------|-------|----------|--------|---------------|------------|
| a3        | Novato        | Marin        | California | tax1     | 102203 | 94945 | -122.570 | 38.113 | 8.76E+00      | 4.90E-01   |
| a2        | Benicia       | Solano       | California | tax2     | 252102 | 94510 | -122.114 | 38.113 | 7.65E+01      | 5.69E+00   |
| a5        | Walnut Creek  | Contra Costa | California | tax1     | 338302 | 94598 | -122.000 | 37.910 | 2.20E+01      | 8.04E+00   |
| a4        | Concord       | Contra Costa | California | tax3     | 355200 | 94519 | -122.000 | 38.000 | 5.76E+01      | 1.38E+01   |
| a1        | Suisun        | Solano       | California | tax1     | 252702 | 94585 | -122.000 | 38.113 | 5.76E+01      | 2.86E+01   |
| a6        | Suisun        | Solano       | California | tax2     | 252702 | 94585 | -122.000 | 38.225 | 1.17E+02      | 1.00E+01   |
| a7        | Birds Landing | Solano       | California | tax1     | 253500 | 94512 | -121.886 | 38.113 | 2.05E+01      | 6.85E+00   |

Instead, the actual average nonstructural and structural losses should be the ones in the table below:

| asset_ref | city          | county       | state      | taxonomy | tract  | zip   | lon      | lat    | nonstructural | structural |
|-----------|---------------|--------------|------------|----------|--------|-------|----------|--------|---------------|------------|
| a3        | Novato        | Marin        | California | tax1     | 102203 | 94945 | -122.570 | 38.113 | 7.91E+00      | 1.14E+00   |
| a2        | Benicia       | Solano       | California | tax2     | 252102 | 94510 | -122.114 | 38.113 | 7.61E+01      | 4.34E+00   |
| a5        | Walnut Creek  | Contra Costa | California | tax1     | 338302 | 94598 | -122.000 | 37.910 | 1.71E+01      | 6.43E+00   |
| a4        | Concord       | Contra Costa | California | tax3     | 355200 | 94519 | -122.000 | 38.000 | 7.31E+01      | 1.03E+01   |
| a1        | Suisun        | Solano       | California | tax1     | 252702 | 94585 | -122.000 | 38.113 | 4.04E+01      | 2.04E+01   |
| a6        | Suisun        | Solano       | California | tax2     | 252702 | 94585 | -122.000 | 38.225 | 8.07E+01      | 6.63E+00   |
| a7        | Birds Landing | Solano       | California | tax1     | 253500 | 94512 | -121.886 | 38.113 | 1.56E+01      | 5.53E+00   |

**Comment by micheles** [comment]
After the change in https://github.com/gem/oq-engine/pull/3191 the weights in sampling are not identical anymore: after checking, the engine is using the expected weights. Also, with 10,000 years the convergency to full enumeration is a lot better.

**Comment by micheles** [comment]
We are restoring the old logic, see https://github.com/gem/oq-engine/pull/4631

**Comment by raoanirudh** [comment]
Verified that the results from the different outputs for the attached job are now consistent with each other.

Average asset losses reported in the `avg_losses-mean` output are ordinary averages of the corresponding numbers in the three branch outputs `avg_losses-rlz-000`, `avg_losses-rlz-001`, and `avg_losses-rlz-002`.

Average loss for the portfolio calculated as the sum of the average asset losses reported in the `avg_losses-mean` is exactly equal to the average loss for the portfolio calculated as the sum of the portfolio losses for each event reported in the `losses_by_event` divided by the effective investigation time, divided by the number of branches.
