### ISSUE TITLE
Allow a local file path to be passed to /v1/calc/run

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4630]
We should add the ability to pass a local path relative to the server to the API.

This will allow the WebUI to execute files (zip or ini) that are already existing on the server, without having users to upload files every time. This is very convenient for use cases like our cluster.

The WebUI will need also to be adapted: 'Run a calculation' should now open a modal with two options. One option would be a zip upload and a second option a text field where to put the file path relative to the server running the webui

**Comment by micheles** [comment]
I like more the idea of writing in the job.ini file something like `source_model_logic_tree_file = ftp:///cluster/dir/ssmLT.xml` or `source_model_logic_tree_file = http:///cluster/dir/ssmLT.xml` which is already possible.
