### ISSUE TITLE
Include an HTML version of the manual in the engine distribution

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4676]
We could also include the engine APi documentation (i.e. https://docs.openquake.org/oq-engine/master/) and the advanced manual (i..e https://docs.openquake.org/oq-engine/advanced/).
The WebUI could contains links to such documentation.

The big issue is the engine manual, which is in latex. We will have to convert it into sphinx. We will need to investigate how to keep the bibliography and the glossary. We will also need to convince @mmpagani (all the others are already convinced).

**Comment by micheles** [comment]
I have discovered that the glossary has been broken (i.e. empty) since right after release 3.1 :-(

**Comment by raoanirudh** [comment]
> I have discovered that the glossary has been broken (i.e. empty) since right after release 3.1 :-(

Glossary fixed in #6124

**Comment by CatalinaYepes** [comment]
Any plan for moving this issue forward?

An HTML of the manual will be much more searchable for users. For example, pages from the advance users manual appear in search engines, but no reference is provided to the basic manual.
In addition, this could reduce the number of questions in the user forum related to basic input parameters.

We should also consider moving to HTML format the OQ hazard and risk books

**Comment by micheles** [comment]
It is a huge work and we still need to convince Marco. Likely it will never be done.
