### ISSUE TITLE
Weichert.calculate() in the HMTK returns a sigma_rate which is not documented in Weichert (1980)

### ISSUE THREAD

**Issue by nackerley** [gem/oq-engine#4783]
I've been discussing this with my colleagues here at the Canadian Hazards Information Service, and we're not even sure it makes sense to compute a standard deviation on the best-fit a-value. Can someone provide documentation for these lines?
https://github.com/gem/oq-engine/blob/5b17406bf294964248c9f2ba50c5568f9d944ff8/openquake/hmtk/seismicity/occurrence/weichert.py#L158-L160

If not I would propose that siga_m and sigma_rate should be dropped as output arguments, or better document what they are.

Additionally it would be helpful if the Weichert() class could estimate error bounds on the individual observations in a cumulative distribution , as documented by Weichert (1980).

I would be happy to put together a pull request, including updating the test, but I'd like to see some agreement that there is a problem here, first.

[Weichert, D. H. (1980). Estimation of the earthquake recurrence parameters for unequal observation periods for different magnitudes. Bulletin of the Seismological Society of America, 70(4), 1337-1346.](http://www.resolutionmineeis.us/sites/default/files/references/weichert-1980.pdf)

**Comment by mmpagani** [comment]
Hi Nick, after a brief check this morning I haven't been able to find reference of where the sigma for the a-value has been defined. I do not know if @g-weatherill has any hints on this. Otherwise, from my side, we can remove it. I agree it would be important to have the error bounds. I am keen to help to the extent possible.

**Comment by micheles** [comment]
I am closing this, since it seems that you got your answer: you are welcome to open a PR.
