### ISSUE TITLE
Can we remove the XML exporters for the disaggregation outputs

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4792]
We have already the CSV exporters and would be good to have to maintain only those.
Do we have scripts/ipython notebooks still using the old XML format?

**Comment by mmpagani** [comment]
Michele, I am fine with a general reorganisation and simplification of the formats used to describe the output provided that we have a general strategy and we stabilise the formats. For this goal, I think we need to prepare a sort of white paper illustrating the general strategy that should be shared and accepted by most of our users.

**Comment by micheles** [comment]
There is some documentation of the CSV outputs here: https://github.com/gem/oq-engine/blob/master/doc/Csv-outputs.md

**Comment by micheles** [comment]
I have no need to remove the XML exporters for the moment, I will just deprecate them.
