### ISSUE TITLE
Improve cluster packaging

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4800]
- [ ]  Make `python3-oq-engine-master` depends on NFS server (this should be already the case, due to `shared_dir`)
- [ ]  Make `python3-oq-engine-worker` a standalone package that just contains init scripts for celery and add dependency on NFS client  (this should be already the case, due to `shared_dir`)
- [x]  Init scripts installed by `python3-oq-engine-worker` should not be `enabled` at boot (https://github.com/gem/oq-engine/pull/4827)
- [ ]  Provide NFS4 sample configuration on both master and workers
- [ ]  Update documentation: setup NFS4 on master and mount `/opr/openquake` on workers

At the end: OpenQuake Engine code will be installed only on master and exported via NFS to the workers. Workers will have only init scripts for celery. This will also definitely solve #4799

**Comment by micheles** [comment]
This is obsolete now. To install on cluster that best solution by far is to now install via packages. Instead, one should perform a git installation on the shared_dir. The universal installer has an option for that since v3.12.
