### ISSUE TITLE
Bump python dependencies to v3

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4860]
So that Python 3.7 can be used.

**Comment by daniviga** [comment]
The only pending issue is GDAL that needs to be rebuilt following the upgrade of numpy to `1.16.5`

**Comment by daniviga** [comment]
We do not have any open issue anymore. Still need to build packages for Python 3.7

**Comment by micheles** [comment]
Closing, at the end we decided to skip Python 3.7 and build the packages directly fro Python 3.8
