### ISSUE TITLE
consider cleaning git history

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [gem/oq-engine#4883]
Hey,

After cloning the repo is bloating to 1.1 GB in volume (`.git` is more than 660 MB). I think it would be a good idea to cleanup the history to reduce this volume. I scrutinized the history a little as described [here](https://github.com/18F/C2/issues/439) and found a couple of static files:
```
opengem/db/seismic_source_admin/seismicsources/data/seismicsource.dbf
smoketests/nshmp-california-fault/LA_county_exposure_portfolio_w_VF_code.xml
tests/data/large.xml
openquake/qa_tests_data/ucerf/UCERF_REDUX_MODEL_v4.hdf5
qa_tests/risk/event_based/qatest_1/fixtures/hzrdr.ses_rupture.csv.gz
```
After clearing them from the history the total volume shrank to 700 MB. I think further cleanup would be required but this is a good tendency.
Also, consider hosting static files, especially those which are meant to be used for testing (`oq-engine/openquake/hazardlib/tests/`: 233 MB), on a server or another git data repo and let the code download those on demand. Or is the `hazardlib/tests` content used also in other cases than testing?

Another option would be to drop a couple of years of the git history. Maybe that's even simpler as the history dates back to 2010. 

Best regards
Marius

**Comment by micheles** [comment]
This is an issue we are aware of. I personally would mind removing the history before engine 1.0 i.e. before Decembre 2014. If you open a PR removing it we will consider it.

**Comment by daniviga** [comment]
Why you don't also do a shallow clone?

**Comment by HerrMuellerluedenscheid** [comment]
Sure, that would be a workaround. But if there is a better way to get rid of the load once and for all I'd advocate for that one. I'll try with a truncated history and keep you updated if that's a way to go.

**Comment by mmpagani** [comment]
If your goal is to have a local compact repository, Daniele's solution is
your one. Since we do not guarantee back compatibility the only way to
provide the ability to compute hazard and risk is to keep old versions.
Thanks
Marco

**Comment by HerrMuellerluedenscheid** [comment]
I am aware of that solution but as I said, that would be a workaround. My goal is to provide feedback from an experienced user point of view that the huge size of this repository can be frustrating when cloning/branching with a slow internet connection or simply storing this repo on a harddrive with rather limited capacity (which I am currently facing). And further to provide a couple of possible solutions how to overcome that flaw.
This article might shed some more light onto that issue: https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/

**Comment by micheles** [comment]
I tried in various way to reduce the history truncating everything before engine 1.0 but it is too difficult for me, I run into hundreds of conflicts to solve manually, so I am closing this. If you want clean the history you need to open a PR doing the job and I will approve it, since we can always keep a copy of the full repo for archiving purposes.

**Comment by HerrMuellerluedenscheid** [comment]
Ok, thanks for the effort. I'll give it a shot too if I find the time. But good to be know that there will be bumps ahead!
