### ISSUE TITLE
Inappropriate filename for Hazard Curve output in XML

### ISSUE THREAD

**Issue by guyomd** [gem/oq-engine#4885]
I am currently using OQ engine, version 3.2.

I required to store individual hazard curves at each frequency in my job.ini file. (individual_curves=True)

When I extract these curves in my output folder (./OUTPUTS), I get the following list of filenames :
OUTPUTS/hazard_curve-mean_102-PGA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/hazard_curve-mean_102-SA.xml
OUTPUTS/quantile_curve-0.05_102-PGA.xml
OUTPUTS/quantile_curve-0.05_102-SA.xml
OUTPUTS/quantile_curve-0.05_102-SA.xml
OUTPUTS/quantile_curve-0.05_102-SA.xml
OUTPUTS/quantile_curve-0.05_102-SA.xml
...

As you can notice, apart from hazard curves calculated for the PGA frequency, all other curves have the same name...
So, in the end, each output with a duplicated name ovewrite the preexisting one, and I end up with only two output files (for each quantile) at frequencies PGA and at the longest period.

NOTE: This behavior does not occur when outputing hazard curves in CSV format:
OUTPUTS/hazard_curve-mean-PGA_102.csv
OUTPUTS/hazard_curve-mean-SA(0.03)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.05)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.1)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.15)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.2)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.25)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.3)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.4)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.5)_102.csv
OUTPUTS/hazard_curve-mean-SA(0.75)_102.csv
OUTPUTS/hazard_curve-mean-SA(1.0)_102.csv
OUTPUTS/hazard_curve-mean-SA(1.5)_102.csv
OUTPUTS/hazard_curve-mean-SA(2.0)_102.csv
OUTPUTS/hazard_curve-mean-SA(3.0)_102.csv
OUTPUTS/quantile_curve-0.05-PGA_102.csv
OUTPUTS/quantile_curve-0.05-SA(0.03)_102.csv
OUTPUTS/quantile_curve-0.05-SA(0.05)_102.csv
OUTPUTS/quantile_curve-0.05-SA(0.1)_102.csv
OUTPUTS/quantile_curve-0.05-SA(0.15)_102.csv
OUTPUTS/quantile_curve-0.05-SA(0.2)_102.csv
OUTPUTS/quantile_curve-0.05-SA(0.25)_102.csv
...

**Comment by micheles** [comment]
Yes, this is known bug of engine 3.2 that was fixed in engine 3.3.
