### ISSUE TITLE
Restore the ability to show the performance info while a calculation is running

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4901]
We lost this features 2 years ago due to internal changes in the HDF5 library :-(
Enormous efforts to get this working again with the SWMR model failed :-(
But now I think it can be done by storing the information in a temporary file different from the datastore.

**Comment by daniviga** [comment]
Why we don't store them in the DB and dump them in the hdf5 file at the end?

**Comment by micheles** [comment]
It is not efficient to write on the DB. We are talking about tens of thousands of rows per each calculation, because this the raw performance data, not the summary printed by `oq show performance`.

**Comment by daniviga** [comment]
Understood
