### ISSUE TITLE
Cleanup NRML example files

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#4904]
Several of the example NRML files in [risklib/nrml_examples](https://github.com/gem/oq-engine/tree/engine-3.6/openquake/risklib/nrml_examples) are outdated, deprecated, or extinct. These need to be updated or removed accordingly.

- [x] Remove obsolete files
- [x] Update outdated files (if any)

**Comment by micheles** [comment]
Please go on on that, @raoanirudh

**Comment by raoanirudh** [comment]
Closed via #4921
