### ISSUE TITLE
Raise en error when ZMQ cannot connect to its endpoint

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4906]
Currently if a ZMQ clients tries to connect to an endpoint which is not ready it waits forever.

This makes this kind of issues very hard to debug and leave computations / jobs stuck forever.

We should find a way to raise en exception when this condition happens (i.e. easy example: when we try to connect to push data to a DbServer that is not started, when workers are not able to send back data)

**Comment by micheles** [comment]
Perhaps it is enough to add some call to `openquake.baselib.general.socket_ready` in the critical places?
We are already using it in `dbserver.get_status`

**Comment by daniviga** [comment]
That's a good hint

**Comment by micheles** [comment]
I am closing this ticket since it seems to me that we did enough for the moment being.
