### ISSUE TITLE
404 Error for Wheel in Requirements.txt

### ISSUE THREAD

**Issue by dhowell-sed** [gem/oq-engine#4954]
Hi OpenQuake Team,

It appears that some of the wheels included in the Linux-Python 3.7 Requirements.txt file have an invalid url. For example, in oq-engine/requirements-py37-linux64.txt:

http://wheelhouse.openquake.org/v3/linux/py/pytz-2019.1-py2.py3-none-any.whl returns a 404 error. I think the correct address is http://wheelhouse.openquake.org/v3/py/pytz-2019.1-py2.py3-none-any.whl.

Thanks,
Dorran

**Comment by daniviga** [comment]
Dear Dorran,
it should work by now.

**Comment by dhowell-sed** [comment]
Okay perfect, looks like it's working again. Thanks!
