### ISSUE TITLE
NGA East GMPEs not instantiating correctly

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#4979]
It seems as though as change in the instantiation of the `GMPETable` class hasn't made it's way into the NGA East GMPEs that inherit from it. The NGAEast base class runs `__init__` from the superclass (GMPETable), which now calls `init(fle=None)` instead. This means that the required attributes are not read from the hdf5 tables.

The following change to lines 429-467 seems to make this work on my machine:
```python
    def __init__(self, gmpe_table, tau_model="global", phi_model="global",
                 phi_s2ss_model=None, tau_quantile=None,
                 phi_ss_quantile=None, phi_s2ss_quantile=None):
        """
        ...
        """
        self.kwargs = {"gmpe_table": gmpe_table}
        self.tau_model = tau_model
        self.phi_model = phi_model
        self.phi_s2ss_model = phi_s2ss_model
        self.TAU = None
        self.PHI_SS = None
        self.PHI_S2SS = None
        if self.phi_s2ss_model:
            self.ergodic = True
        else:
            self.ergodic = False
        self.tau_quantile = tau_quantile
        self.phi_ss_quantile = phi_ss_quantile
        self.phi_s2ss_quantile = phi_s2ss_quantile
        self._setup_standard_deviations(fle=None)
        super().init(fle=None)
```

If this fix is correct then I can open a PR with it.

**Comment by micheles** [comment]
It it is broken while all the tests in hazardlib are green, it means that they are bad tests not testing the real use case. Please include a good test in your PR, @g-weatherill
