### ISSUE TITLE
v.3.6: logicTree verification conflicts with branching levels containing more than 1 branch sets

### ISSUE THREAD

**Issue by guyomd** [gem/oq-engine#5067]
The Openquake v.3.6 User Manual states that "There are no restrictions on the number of branch sets that can be defined inside a branching level" (see . p53).

However, in the logictree.py file, the function _bsnodes()  (l.466) raises an error when a BranchingLevel has more than 1 branch set, see below:

```python
def _bsnodes(fname, `branchinglevel):
    if branchinglevel.tag.endswith('logicTreeBranchingLevel'):        
        **if len(branchinglevel) > 1**:
            raise InvalidLogicTree(
                '%s: Branching level %s has multiple branchsets'
                % (fname, branchinglevel['branchingLevelID']))
        return branchinglevel.nodes
    elif branchinglevel.tag.endswith('logicTreeBranchSet'):
        return [branchinglevel]
    else:
        raise ValueError('Expected BranchingLevel/BranchSet, got %s' %
                         branchinglevel)
```

**Comment by micheles** [comment]
Good catch, @guyomd . We forgot to update the manual, but now it is fixed. As documented in https://github.com/gem/oq-engine/blob/engine-3.6/doc/whats-new.md the branchingLevel concept is no more:
