### ISSUE TITLE
Document and clarify param individual_curves

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5135]
Currently the parameter `individual_curves` is not documented in the manual.

The parameter is needed to compute the curves per realization, but the name is ambiguous.
I suggest to rename it, for example, to `curves_per_realization`

**Comment by raoanirudh** [comment]
Added to the open issue on documentation #3460, to both the hazard and risk sections

Not sure if we need to rename the parameter if it's well documented – it's been around for five years: see #1516

**Comment by micheles** [comment]
I am also in favor of keeping the old name, since it is mostly used by the hazard guys who are used to this name.
