### ISSUE TITLE
'calc_X_tmp.hdf5' files are not deleted by 'oq reset'

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#5192]
```bash
$ ls ~/oqdata
calc_1.hdf5
calc_1_tmp.hdf5
db.sqlite3

$ oq reset -y

$ ls ~/oqdata
calc_1_tmp.hdf5
```

**Comment by daniviga** [comment]
And also by the delete command

**Comment by daniviga** [comment]
Actually,  I think that the `tmp` file should be removed as soon as the job is completed (on in a cleanup phase when it's failed)

**Comment by micheles** [comment]
Actually the removal of the `tmp` file is already in the cleanup phase but it is not working. Presumably it is because of out of memory errors or `kill -9` situations. So I will need to update the delete and reset commands.
