### ISSUE TITLE
DbServer is using too much memory

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#5197]
On OQ1 and OQ2 the DbServer is using far too much memory:
- on OQ1 it has almost 9GB RAM allocated
- on OQ2 it has 1.5GB RAM allocated and almost 3GB reserved

We need to understand where this memory is allocated and if it happens only on clusters (via ZMQ) or on a single node too.

**Comment by daniviga** [comment]
DbServer restarted on `oq1`

**Comment by micheles** [comment]
It could be caused by `oversubmit=true`

**Comment by daniviga** [comment]
The memory is used by the "Task streamer", so that's fine with very large calculations.
