### ISSUE TITLE
Again issues linking event_id and rupture_id

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5199]
Using the outputs from the event based Nepal demo, it is not possible to associate the losses from the `losses_by_event.csv` with the ruptures from `ruptures.csv`.

For example, the `losses_by_event.csv` has an output like:

event_id | nonstructural | structural | rlz_id | rup_id | year
-- | -- | -- | -- | -- | --
64 | 38,135 | 60,858 | 1 | 31 | 274
70 | 10,373,700 | 16,659,900 | 1 | 34 | 777
71 | 41,329 | 65,821 | 0 | 34 | 346

However the `ruptures.csv` file doesn't have ruptures with a `rupid=31 or 34`. The file `events.csv` does not help with the association either.

This is also related with:
https://github.com/gem/oq-engine/issues/5041
https://github.com/gem/oq-engine/issues/4973

**Comment by micheles** [comment]
The issue is that when I changed from long IDs to short IDs I also renamed a field called `.serial` into `.rup_id` and this cause overriding the datastore rupture IDs with the serials, which are not at all the same thing :-( Since all the IDs changed at the same time the issue was masked.
