### ISSUE TITLE
Make sure the ruptures boundaries are exported correctly

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5227]
And also add an /extract/ API which can be used by the plugin.

**Comment by micheles** [comment]
We still need to understand the invalid bounding boxes generated by the tests case_3 and case_5.

**Comment by micheles** [comment]
Julio says that he really needs the 3D boundaries, not the bounding box.

**Comment by julgp** [comment]
yes, I apologised for the delayed checking. Unfortunately, the bbox is not a good representation of a rupture geometry,( see map attached). What are the bboxs useful for? Is it someone using them from the hazard and/or risk team? If we are exporting a geometry, it should be 3d and correctly oriented, if possible, I think.
![mex_eb_10Kses_inter_rup_v37_vs_bbox_v38](https://user-images.githubusercontent.com/4562050/68202091-4d2cd480-ffc3-11e9-92c7-0354d6edd67c.png)

**Comment by micheles** [comment]
The full information about the geometry can be extracted from the rupture_info API, but it will require work to make it usable from matplotlib or a similar tool. I am closing this ticket but we will probably need to open another one for the visualization part.
