### ISSUE TITLE
Opinion: Do not deprecate XML export !

### ISSUE THREAD

**Issue by guyomd** [gem/oq-engine#5254]
I would like to kindly argue against the planned deprecation of hazard curve/uhs exports in XML format...
To my opinion, this format provide the advantage of:
- being directly human-readable and interpretable (for rapid QC of results at least), and 
- Ensuring and preserving a strict hierarchical organization of output data and related metadata.

In particular, I am not very convinced by the CSV alternative, that organizes all metadata associated with each output (source-model and gsim-model realization) into a concatenated header string. 
I don't think that the current CSV format is more useful or practical to develop scripts aimed at post-processing Openquake results...

Best regards,

G.

**Comment by micheles** [comment]
The right place for this kind of comments is the mailing list, not github.
Anyway, there are no plans to remove the XML for hazard outputs.

**Comment by guyomd** [comment]
Yes, apologies, I agree....

This is due to the repeated message going up each time I use "oq engine -e xml" command...

G.


De: notifications@github.com
Envoyé: 29 octobre 2019 10:21 AM
À: oq-engine@noreply.github.com
Répondre à: reply@reply.github.com
Cc: guillaume.daniel@outlook.com; author@noreply.github.com
Objet: Re: [gem/oq-engine] Opinion: Do not deprecate XML export ! (#5254)


Closed #5254<https://github.com/gem/oq-engine/issues/5254>.
