### ISSUE TITLE
Automatically import .py files in the job.ini directory

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5262]
This can be really useful for debugging purposes and in general for trying code that should not go in the repository.

**Comment by micheles** [comment]
Unfortunately, I do not see how the code can be seen in the workers unless it is saved in `/home/openquake/oqdata`, which is a completely different thing.

**Comment by daniviga** [comment]
Actually we are exporting `/home` at whole, since `oqdata` is in the user's home folder (see https://github.com/gem/oq-engine/blob/master/docker/celery/openquake.cfg#L81), so if the file stays enclosed in a home it should be fine from the workers side.
