### ISSUE TITLE
Optimize the classical calculator for the single site situation

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5287]
This has now become essential.

**Comment by micheles** [comment]
The serious way to get this done is to vectorize by ruptures, not by sites. In other words, the RuptureContext should contain arrays of parameters and the DistancesContext arrays of distances, with one distance for each rupture. We need a `ContextMaker.make_contexts2(site, ruptures)` method returning `rctx` and `dctx`.

**Comment by g-weatherill** [comment]
This would be a useful feature but most GMPEs are built around the vectorisation of sites and distances, with the rupture properties given as scalars. I would expect it to require a drastic re-write of the majority of GMPEs in the library to adapt them to a vector of rupture properties.

**Comment by micheles** [comment]
I am well aware of that, Graeme, this is why I wrote `the **serious* way to get this done`. It seems to me that all other ways are not likely to give substantial speedups, while the serious way is a lot of work :-(

**Comment by micheles** [comment]
After analysis, the major bottleneck seems to be `.iter_ruptures()` in point sources. Then we must think of ways of simplifying it for ruptures far away from the sites, without calling `_get_rupture_surface()`.

**Comment by micheles** [comment]
After the recent spectacular improvements with the rupture collapsing within the pointsource_distance approximation (both with spinning/floating and without) I think that the ticket can be closed for the time being. Vectorization by ruptures is probably possible without touching hazardlib at all but it will go in another ticket. For the moment the collapsing approach has saved us.
