### ISSUE TITLE
Bug in scenario calculations using precomputed gmfs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5337]
Same issue as the one reported in https://github.com/gem/oq-engine/pull/5028 is happening.

When creating the site mesh from the site coordinates read from the csv file, the coordinates always get sorted and are assigned new site ids (if the input coordinates were not in sorted order), breaking the link with the user-specified site_ids and thus also with the gmf data.

**Comment by micheles** [comment]
After 6 months this has not happened again, so I am closing it.
