### ISSUE TITLE
Add the ability to collapse the GSIM logic tree

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5354]
This was requested by Crescenzo and it is actually trivial to implement on our side. The way I envision the feature, the user will be able to write in the job.ini something like

```
collapse_gsim_logic_tree = bs1 bs2
```
and then the branchset bs1 and bs2 of th full GSIM logic tree will be collapsed, i.e. the multiple gsims for the corresponding tectonic region type will be replaced by a single average gsim.
The use case is event based: a model like the one for Pakistan would change from 800 realizations for source_model_1 + 800 realizations for source_model_2 (or something like that) to 1 + 1 realizations, thus saving 800 times more disk space in the GMFs and making it possible the ingestion into a financial software.

**Comment by mmpagani** [comment]
I think it's key to specify what you mean by 'single average gsim'

**Comment by micheles** [comment]
It will be implemented as a geometric mean, similarly to what we did for the AvgSA GMPE.
