### ISSUE TITLE
Add NGA East site amplification model and USGS NSHMP tables

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#5361]
OQ currently has the NGA East "seed" GMPEs implemented, with the common aleatory uncertainty model of Al Atik (2015). The tables of these GMPEs refer to a reference rock condition of Vs30 3000 m/s. Recently, a corresponding site amplification model has been published (Stewart et al., 2019; Hashash et al. 2019) as well as a further set of 17 tables describing the epistemic uncertainty model to be used in the current National Seismic Hazard models. These should be added for the purposes of running current (and possibly future) generations of the NSHMP in OQ. Suggest the following steps:

- [x] Add site amplification model to the NGA East base classes

- [x] Add 17 tables for the USGS epistemic uncertainty model

- [x] Update SERA craton model to utilise new NGA East site amplification model

After the first step is achieved,  a user could actually accomplish the second step by parsing the tables themselves as arguments to the GMPE. However, we can see the benefit of having the GMPEs themselves coded.

To run the GMPEs within the USGS NSHM it is necessary to adopt period-dependent weights. Clarification is needed as to how this could be achieved with the current calculator.

This feature request is made jointly by myself and @emthompson-usgs on behalf of the USGS Shakemap team.

(This task can be assigned to me)

**Comment by micheles** [comment]
Period-dependent weights are documented here: https://github.com/gem/oq-engine/blob/master/doc/adv-manual/special-features.rst#gmpe-logic-trees-with-weighted-imts

**Comment by g-weatherill** [comment]
OK, then no additional effort is needed in the implementation to support period-dependent weights and as long as the main GMPEs are there then the user can implement the US NSHM requirements with the current structure. Thanks!

**Comment by micheles** [comment]
Can this ticket be closed or we are still missing something, @g-weatherill ?

**Comment by g-weatherill** [comment]
The third point regarding the update of the SERA craton model in light of these changes still needs to be done. I hope to get it done this week.

**Comment by g-weatherill** [comment]
All done (hopefully). Thanks for your help Michele!
