### ISSUE TITLE
See if we can improve the aggregation per multi-tag in ebrisk

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5448]
For instance, if there is an `aggregate_by=region,taxonomy` then it would be useful to be able to get the  curves aggregate by `region` only (or by `taxonomy` only) without having to change the `aggregate_by` and repeat the whole calculation. See if this is possible now with some postprocessing (it was impossible in the past). Requested by @CatalinaYepes and @danciul, see also the comment in https://github.com/gem/oq-engine/issues/5051 about the increase of the number of the outputs with N tags (*2^N*).

**Comment by raoanirudh** [comment]
Related, and probably a minor bug: if the `aggregate_by` parameter is not used in the job file or is blank, the aggregate loss curves outputs should not be generated or exposed to the user, because they will be empty in such cases. The required loss curves for such cases are now provided in the total loss curves outputs instead.

**Comment by micheles** [comment]
It is possible now because the event loss tables for each combination of tags are stored, so it is enough to aggregate them. But we have to think of an API (perhaps an `oq aggregate_by` command?)

**Comment by raoanirudh** [comment]
cf. #5733

**Comment by micheles** [comment]
I found out a decent API, a command `oq recompute_losses <calc_id> <aggregate_by>`:
```
$ cd openquake/qa_tests_data/event_based_risk/recompute
$ oq run job.ini
$ oq recompute_losses -1 NAME_1,NAME_2
$ oq recompute_losses -2 NAME_1,taxonomy
$ oq recompute_losses -3 NAME_2,taxonomy
$ oq recompute_losses -4 NAME_1
$ oq recompute_losses -5 NAME_2
$ oq recompute_losses -6 taxonomy
```

**Comment by micheles** [comment]
The command has been renamed to `oq reaggregate`
