### ISSUE TITLE
Fix the global risk model files

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5451]
Due to the new checks in the engine it is not guaranteed that the global risk model calculations will run anymore. Also, it is now advisable to remove the split job_hazard.ini/job_risk.ini and use a single job.ini with calculation_mode=ebrisk.  Somebody in the risk team has to be maintain the files and we will need to put the models under continuous integration to keep the calculations working, as we did for the hazard mosaic one year ago. This is a nontrivial project to implement.

**Comment by raoanirudh** [comment]
This issue might be more relevant for the global risk model repos than for the engine – shall we move the issue there?

**Comment by micheles** [comment]
You are right, please copy the issue there, but I would leave the one here open, because it is possible that to make the models run again some fixes on the engine side will be needed too.

**Comment by micheles** [comment]
Closing it has become obsolete (in particular keeping the split job_hazard.ini/job_risk.ini is now good again and the ebrisk calculator is deprecated).
