### ISSUE TITLE
"investigation time" error message when sites are outside the integration distance in event-based calculation mode

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#5516]
A user recently found that when all the sites in an event-based calculation are outside the integration distance, OQ gives [this error](https://github.com/gem/oq-engine/blob/495d863b1ecd12d4ab62371c95d6ad906805f3d4/openquake/calculators/event_based.py#L173): 

RuntimeError('No ruptures were generated, perhaps the investigation time is too short')

Does the error message need to be improved (e.g., "perhaps the investigation time is too short or your site is too far"), or is the wrong error message being raised? 

An example is [here](https://groups.google.com/forum/#!topic/openquake-users/NY5kRMEFhp8).

**Comment by micheles** [comment]
We should compute the enlarged bounding box for all the sources (using min(mins) and max(maxs)) and check the intersection with the site collection.
