### ISSUE TITLE
Encoding issue on Windows

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5533]
@hascar discovered that the description for the AreaSource demo is displayed incorrectly by the WebUI on windows: the encoding is UTF8, but probably Windows does not understand that. It is also interesting to check what happens QGIS side.

**Comment by daniviga** [comment]
That was a know issue, due to the fact that for Windows OQ relies on CMD which has its own encoding which btw does not match 100% with UTF-8.

You could consider to switch to powershell now that only Win 10+ is supported (and migrating from `.bat` to `.ps`

**Comment by ptormene** [comment]
ConfigParser.read changed in version 3.2, accepting also the encoding parameter. Previously, all files were read using the default encoding for open().
