### ISSUE TITLE
Scenario Hazard Calculator - Support for multiple ruptures and TRs

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#5603]
Malcom would like to use the scenario hazard calculator for a set of ruptures belonging to different tectonic regions.  This requires, at least, the following:
- Add the TR parameter to ruptures
- Extend the scenario hazard calculator to support a set of ruptures from different TRs (making sure that this is seamlessly integrated into the corresponding risk calculator)

**Comment by micheles** [comment]
If the ruptures are all planar it looks the same as https://github.com/gem/oq-engine/issues/5603

**Comment by raoanirudh** [comment]
Another related application could be to allow for the consideration of uncertainties in the rupture parameters for a given scenario, such as the magnitude, hypocenter, and rupture geometry. For instance, the [BSSC2014 scenario catalog](https://earthquake.usgs.gov/scenarios/catalog/bssc2014/) contains 66 rupture variations for a M7.0 Charlevoix RLME scenario earthquake (images below). It would be nice to be able to consider these within a single job.

![Charlevoix](https://user-images.githubusercontent.com/1707414/85112885-a7a73800-b216-11ea-92e2-e09495be202d.png)
![Charlevoix1](https://user-images.githubusercontent.com/1707414/85112901-abd35580-b216-11ea-8a2a-ad81ac8067d7.png)
Images from https://usgs.maps.arcgis.com/apps/webappviewer/index.html?id=14d2f75c7c4f4619936dac0d14e1e468
