### ISSUE TITLE
Add SES id and year of event to the events table

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#5629]
For an event based (hazard only) calculation, the current csv outputs do not contain sufficient information to link an individual event (and the corresponding rupture) with the particular SES in which it was generated. This link was available in the (now deprecated) ruptures.xml output, which has been replaced primarily by the ruptures.csv and events.csv outputs. The SES id should ideally be listed in the events.csv output.

Related to the above, the event loss tables from an event based risk calculation list the (simulated) year of event for all events. The same information is absent, however, if a user runs an event based hazard calculation, and should also ideally be listed in the events.csv output.

**Comment by mmpagani** [comment]
We've been changing the format of the EB output a number of times. We need to come up with one stable solution since our users get confused by these changes. So I suggest to get a consensual view on the required outputs and their format and solidify them for at least a couple of years (it not more).

**Comment by micheles** [comment]
The controversial issue is how to replace the ruptures XML output with something efficient enough to export a million of ruptures and that can be imported to run a subsequent multi-rupture calculation (see https://github.com/gem/oq-engine/issues/5603). Adding two columns to the events table instead is trivial and it is enough for this ticket.
