### ISSUE TITLE
Bug in openquake.hazardlib.calc.hazard_curve.calc_hazard_curves function

### ISSUE THREAD

**Issue by krisvanneste** [gem/oq-engine#5736]
Dear developers,

I discovered a bug in the calc_hazard_curves function at this line: https://github.com/gem/oq-engine/blob/35bef7b3937cf1f030936088173303d60642c4a7/openquake/hazardlib/calc/hazard_curve.py#L193

In this function, sources are grouped by tectonic region type, but all groups are computed with the same gsim!

The line should be replaced with:
`      gsim = gsim_by_trt[group[0].tectonic_region_type]`
and be moved inside the loop over the groups just below.

Thank you for looking into this issue,
Kris Vanneste

**Comment by micheles** [comment]
You are right, we will fix this after Easter. Fortunately that function is not used by the engine, so the bug does not affect any calculation.

**Comment by krisvanneste** [comment]
Thank you very much and have a nice Easter!
Kris
