### ISSUE TITLE
OQ Repository 404 Not Found

### ISSUE THREAD

**Issue by NimaDolatabadi** [gem/oq-engine#5772]
on Ubuntu 20.04 LTS, when I do `sudo add-apt-repository -y ppa:openquake/ppa` it gives me the following error:

```
Err:13 http://ppa.launchpad.net/openquake/ppa/ubuntu focal Release
404  Not Found [IP: 91.189.95.83 80]
E: The repository 'http://ppa.launchpad.net/openquake/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Please Help Me on this Issue
Nima
Regards

**Comment by micheles** [comment]
This is not the right place to ask questions about installation problems, github is for reporting bugs and code-related issues. The right place is the mailing list.

Having said that, officially we do not support Ubuntu 20.04 that was released yesterday, but the engine works fine on it. Just use another installation method, not the packages.

See https://github.com/gem/oq-engine/blob/master/doc/installing/README.md
