### ISSUE TITLE
boundary conditions on the imls when using amplify_gmfs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5815]
The amplification factors are sometimes defined based on existing studies, where limited information is available. The example below shows amplification factors available for a few intensity levels, that might not cover all the range of values required for hazard and risk analyses.

| ampcode | level | PGA | SA(0.3) | sigma_PGA | sigma_SA(0.3) |
| ----- | ----- | ----- | ----- | ----- | ----- |
| zone_1 | 0.05 | 1.45 | 2.22 | 0.4 | 0.4 |
| zone_1 | 0.1 | 1.78 | 1.87 | 0.4 | 0.4 |
| zone_1 | 0.2 | 2.11 | 2.66 | 0.4 | 0.4 |
| zone_1 | 0.3 | 1.55 | 1.59 | 0.4 | 0.4 |
| zone_2 | 0.075 | 1.33 | 1.79 | 0.4 | 0.4 |
| zone_2 | 0.15 | 1.69 | 2.42 | 0.4 | 0.4 |
| zone_2 | 0.25 | 1.98 | 2.58 | 0.4 | 0.4 |
| zone_2 | 0.35 | 1.76 | 1.8 | 0.4 | 0.4 |

Currently the engine is raising errors like:

`File "/opt/openquake/oq-engine/openquake/hazardlib/site_amplification.py", line 71, in digitize
    f'The {name} {min(values)} is outside the edges {edges}')
ValueError: The level 0.029020259117920055 is outside the edges [0.0357 0.0849 0.134  0.1966 5.    ]`

**A better error message can be raised requesting users to include boundary conditions.**

However, even if the user extend the coefficients to cover all the range of requested imls, the following error appears:
`File "/opt/openquake/oq-engine/openquake/commonlib/readinput.py", line 738, in get_amplification
    records['level'], imls))
openquake.baselib.InvalidFile: /home/cyepes/scenarios_colombia/Inputs/Amp_factors_Bog_760.csv: levels for b'10' [1.700e-03 3.570e-02 8.490e-02 1.340e-01 1.966e-01 5.000e+00] instead of [1.000e-04 3.570e-0
2 8.490e-02 1.340e-01 1.966e-01 5.000e+00]`

**Comment by micheles** [comment]
The engine is assuming that the levels for zone1 as the same as for zone2 (actually they must all be the same for all amplification functions). This assumption is clearly too strong and I will have to relax it.
