### ISSUE TITLE
Error when extracting ruptures in TOML format

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5821]
Currently the [documentation](https://github.com/gem/oq-engine/blob/01360dd1f5ef7f6e7655f800d44a18d23840c30b/doc/adv-manual/special-features.rst#ruptures-in-toml-format) indicates that the command `oq extract rupture/<rup_id>` will export a .txt file with the specified rupture. The idea is to open that file with any text editor, but the format is actually TOML. More importantly, it should be possible to run scenario calculations starting from that rupture file.

However the engine is extracting the rupture file in `.npz` which is difficult to read for many users, and it is not supported as an input file format in OQ.

**Comment by CatalinaYepes** [comment]
Thanks to @raoanirudh for pointing this out https://github.com/gem/oq-engine/pull/5807

I keep the comment that `.npz` is difficult to read for many users, and it is not supported as an input file format in OQ.

**Comment by micheles** [comment]
This a bug Cata, an unintentional consequence of https://github.com/gem/oq-engine/commit/7e4a8290215858345ff87d69cc0d4cd8e39f7310. It looks like I accidentally removed some line of codes and unfortunately the TOML extraction that we have does not use `oq extract`, so it is green even if `oq extract` does not work :-(
