### ISSUE TITLE
Bug in scenario dmg_by_event outputs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5854]
The output `dmg_by_event` is reporting the wrong realization id.

The `avg_damage` results show different mean values, when compared with the `dmg_by_event`. The error seems to be in the association of `rlz_id` in the `dmg_by_event` file. I think the engine is assuming the `rlz_id` as the index of the sorted list of GMPEs instead of the appropriate `rlz_id` reported in the realizations file.

To replicate the bug, run the `qa_tests_data/scenario_damage/case_9` modifying the `gmpe.xml` file with as follow (considering three unsorted gmpes) :

```xml
<?xml version='1.0' encoding='utf-8'?>
<nrml xmlns:gml='http://www.opengis.net/gml'
      xmlns='http://openquake.org/xmlns/nrml/0.5'>

<logicTree logicTreeID='lt1'>
  <logicTreeBranchingLevel branchingLevelID='bl1'>
    <logicTreeBranchSet uncertaintyType='gmpeModel'
                        branchSetID='bs1' 
                        applyToTectonicRegionType='Active Shallow Crust'>
      <logicTreeBranch branchID='b0'>
        <uncertaintyModel>ClimentEtAl1994</uncertaintyModel>
        <uncertaintyWeight>0.25</uncertaintyWeight>
      </logicTreeBranch>
      <logicTreeBranch branchID='b1'>
        <uncertaintyModel>BooreAtkinson2008</uncertaintyModel>
        <uncertaintyWeight>0.500</uncertaintyWeight>
      </logicTreeBranch>
      <logicTreeBranch branchID='b2'>
        <uncertaintyModel>AbrahamsonEtAl2014</uncertaintyModel>
        <uncertaintyWeight>0.2500</uncertaintyWeight>
      </logicTreeBranch>
    </logicTreeBranchSet>
  </logicTreeBranchingLevel>
</logicTree>
</nrml>
```

The mean results obtained with this modified calculation are:
|	rlz_id	|	Average structural~no_damage	|	Average structural~slight	|	Average structural~moderate	|	Average structural~extensive	|	Average structural~complete	|
|	---	|	---	|	---	|	---	|	---	|	---	|
|	0	|	9.40E+02	|	1.14E+02	|	3.26E+01	|	1.25E+01	|	1.24E+01	|
|	1	|	9.32E+02	|	1.14E+02	|	3.70E+01	|	1.44E+01	|	1.38E+01	|
|	2	|	1.04E+03	|	5.90E+01	|	7.21E+00	|	2.10E+00	|	1.43E+00	|

However, the results for `rlz_id = 2` are the ones reporte for ClimentEtAl1994, according to the `avg_damages-000_calcID.csv`

**Comment by micheles** [comment]
It is an exporter bug. The data are correct in the datastore, but associated to the wrong realization in the CSV.
