### ISSUE TITLE
Restore `disagg_by_src`

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5869]
It was working before engine 3.9, even if only experimentally. Now it must be turned into an official feature. My proposal is to store a dataset `disagg_by_src` with 4 dimensions, containing mean PoEs:

N = number of sites
Ns = number of sources
M = number of IMTs
L = number of levels per IMT

In theory the dataset could be 5 dimensional, the fifth dimension being the realizations, however it would immediately become to big to fit in memory and there would be performance issues.
Currently there is a limit of 1000 sources (otherwise setting `disagg_by_src=true` in the job.ini raises an error); with N=1000, Ns=1000, M=10, L=50 and 8 bytes per element the array will take 3.8 GB, which is already quite big.

**Comment by mmpagani** [comment]
This is a site-specific analysis hence it should be limited to a few sites. The results should cover all the realisations created in order to permit a thorough analysis of the contributions to hazard.

**Comment by micheles** [comment]
Then I will store a matrix of shape (N, R, M, L, Ns) and I will raise an error if it becomes larger than say 4 GB.
