### ISSUE TITLE
oq to_shapefile missing trt value 

### ISSUE THREAD

**Issue by rcgee** [gem/oq-engine#5913]
The "trt" fields are "NULL" after running `oq to_shapefile`. In the example below, I ran `oq to_shapefile` on the source file EUR/in/ssm/ssm01.xml and obtain the following when I plot in QGIS:

Edit: Other fields are also NULL, but I happened to notice the trt field first because it is of interest for the current project.

<img width="977" alt="Screenshot 2020-06-10 at 18 06 12" src="https://user-images.githubusercontent.com/9217451/84291786-dbfb6400-ab45-11ea-8cc1-a339be365b32.png">

**Comment by micheles** [comment]
The plan is to remove the shapefiles, @rcgee 
I wonder why this error is happening now, I did not touch anything for 5 years in `oq to_shapefile`, are these special sources?

**Comment by rcgee** [comment]
ok, thank you Michele. I will try using nrml_to_csv
