### ISSUE TITLE
Improve mac OS installation instructions

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#6082]
Below description of improvements for Mac OS installation instructions:

1. Once the user has completed the installation, the following message appears:
```
Installation completed. The 'oq' command is now available opening a new terminal (see 'oq --help' for more commands)
but 
```
However, if the user types the oq command, the following error appears:
`oq: error: unrecognized arguments: --help`

The user still needs to activate the venv, so the message should be
```
Installation completed. 
To make the 'oq' command available you must enable the environment first running 'source ${FDEST}/env.sh
```
https://github.com/gem/oq-builders/blob/master/installers/unix/env/install.sh#L164-L171

2. The demo folder for mac installation is located in `openquake/share/demos`, and it doesn't have the manual in pdf. We should create the same structure as for Windows version: demos located inside openquake folder (not a share folder) and include the pdf manual.

3. I will be useful to mention the location of the demos folders for all OS.

**Comment by raoanirudh** [comment]
Just guessing here, but the issue could simply be the change of the default shell from bash to [zsh starting from Catalina](https://support.apple.com/en-gb/HT208050). The alias is probably being created correctly, but it gets added to .bash_profile, whereas the shell is now reading .zshenv or .zshrc. Thus, this line may need to be updated: https://github.com/gem/oq-builders/blob/engine-3.9/installers/unix/env/install.sh#L65

**Comment by CatalinaYepes** [comment]
Yes, I confirm that the `oq` command is saved in the .bash_profile.

**Comment by nastasi-oq** [comment]
Is required to improve the installation process to manage zsh shell case.

**Comment by nastasi-oq** [comment]
Fix for zsh added and backported to new release 3.10.1.

**Comment by nastasi-oq** [comment]
> Below description of improvements for Mac OS installation instructions:
> 
> 1. Once the user has completed the installation, the following message appears:
> ```
> Installation completed. The 'oq' command is now available opening a new terminal (see 'oq --help' for more commands)
> but 
> ```
> However, if the user types the oq command, the following error appears:
> `oq: error: unrecognized arguments: --help`
> 
> The user still needs to activate the venv, so the message should be
> ```
> Installation completed. 
> To make the 'oq' command available you must enable the environment first running 'source ${FDEST}/env.sh
> ```
> https://github.com/gem/oq-builders/blob/master/installers/unix/env/install.sh#L164-L171

Installation on   MacOS with zsh as shell is fixed here:
  https://github.com/gem/oq-builders/pull/137

> 2. The demo folder for mac installation is located in `openquake/share/demos`, and it doesn't have the manual in pdf. We should create the same structure as for Windows version: demos located inside openquake folder (not a share folder) and include the pdf manual.

Demos path is not changed  but now is correctly cited insthe documtation
> 
> 3. I will be useful to mention the location of the demos folders for all OS.
