### ISSUE TITLE
The extract api still returns some bytes instead of strings

### ISSUE THREAD

**Issue by ptormene** [gem/oq-engine#6095]
- [ ] Extracting `realizations`, branches are returned as bytes
- [ ] Extracting `asset_tags`, all items (taxonomies and tags) are returned as arrays of bytes
- [ ] Boundaries of `ruptures` are returned as bytes
- [ ] Extracting `agg_curves`, units are returned as bytes

Also see https://github.com/gem/oq-irmt-qgis/issues/743

**Comment by micheles** [comment]
Is this a problem, @ptormene ?

**Comment by ptormene** [comment]
It is not an urgent matter and it is not necessary.

**Comment by micheles** [comment]
This will come hot again due to https://github.com/gem/oq-engine/issues/6668: h5py 3.1 returns bytes instead of strings, so it may break the plugin even more.

**Comment by micheles** [comment]
We already switched to h5py 3.1 without big issues; let's keep the status quo.
