### ISSUE TITLE
Bring back asset_loss_table or `aggregate_by = id`

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#6106]
The `asset_loss_table` parameter was removed in #5186 in favor of the `aggregate_by = id` mechanism for storing the asset-level event loss table. The latter mechanism was later invalidated in #5755 after the removal of the asset 'id'. This leaves the user with no straightforward way to ask the engine to store the asset loss table in either event_based_risk or ebrisk. These tables are needed when custom insured loss calculations are performed downstream of the risk calculation. This feature could be added to either event_based_risk or ebrisk, whichever is more convenient from an implementational standpoint.

**Comment by micheles** [comment]
Performing insured loss calculations downstream of the risk calculation will never work for the kind of calculations we do (i.e. large). The only way forward is to compute the insured losses while the losses are computed. This is akin to what we implemented for the secondary perils: a plugin system where secondary quantities are computed while the GMFs are being computed, not in postprocessing. See for instance https://github.com/gem/oq-engine/blob/master/openquake/sep/classes.py#L154. We need to discuss the required API. It it is too user-specific and we have no idea about what to do, let's abandon this for the moment. I do not want people expecting that an asset_loss_table will be there.

**Comment by raoanirudh** [comment]
Agreed, after discussion with @micheles. Closing this issue.
