### ISSUE TITLE
write_source_model in `openquake.hazardlib.sourcewriter`

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#6118]
The function `write_source_model` requires an area source to have the `area_discretization` attribute and creates an .xml as follows:
```
                <areaGeometry discretization="10.0">
``` 
While this can be useful in some cases it can also produce unexpected behaviours since this setting overrides the parameters defined in the `job.ini` file. I suggest to make the `area_discretization` attribute optional; when this is missing the resulting .xml will simply be:
```
                <areaGeometry>
```

**Comment by micheles** [comment]
Notice that the function `write_source_model` does not requires an `area_source_discretization`, its signature is
`write_source_model(dest, sources_or_groups, name=None, investigation_time=None)`. Are you talking about another function?

**Comment by mmpagani** [comment]
You're right Michele I was referring to the `SourceConverter`.
