### ISSUE TITLE
Site parameters "backarc_distance" and "xvf" refer to the same thing - should be merged

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#6135]
Two different GMPE sets require the definition of the site property "distance to the volcanic front":

1. BCHydroSERAS#### - refer to this as `backarc_distance` and it takes a negative value in the forearc and positive in the backarc.

2. MorikawaFujiwara2013#### - refer to this as `xvf` and it takes a positive value in the forearc and negative in the backarc. 

A single definition should be used. As the BCHydroSERA#### is not yet published, I think it is better that it adopts the `xvf` definition rather than vice-versa. 

If agreed, then assign this issue to me.

**Comment by mmpagani** [comment]
Thanks for this summary. Note that we also have something similar in the 
Si and Midorikawa. See

https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/si_midorikawa_1999.py#L46

and

https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/si_midorikawa_1999.py#L96

**Comment by g-weatherill** [comment]
The Si and Midorikawa case is a bit more complicated because the Japanese volcanic front is hard-coded there. One option could be to set `xvf` as an optional site parameter for Si and Midorikawa (thus making it operate more like MorikawaFujiwara2013) but it would retrieve the existing hard-coded values if `xvf` is not provided, hopefully maintaining backward compatibility.

**Comment by mmpagani** [comment]
That's fine with me. Indeed, as discussed during the call, the geometry of the volcanic arc (line, polygon?) should be an input provided in the the GMC logic-tree.
