### ISSUE TITLE
to_shapefile doesn't export trt

### ISSUE THREAD

**Issue by matsmithlondon1** [gem/oq-engine#6237]
Hi there,
there's a minor bug on oq engine 3.10.0-git9d4ed7e - to_shp doesn't currently export trt but leaves it blank (testing using SHARE area source model). Apologies if you may have fixed this already in the latest release.

Thanks,
Matt

**Comment by micheles** [comment]
`to_shapefile` is going to be abandoned. You can convert in CSV format or in geopackage format with the command `oq nrml_to`:
```
$ oq nrml_to --help
usage: oq nrml_to [-h] [-c] {csv,gpkg} fnames [fnames ...] [outdir]

Convert source models into CSV files or a geopackage.

positional arguments:
  {csv,gpkg}    csv or gpkg
  fnames        source model files in XML
  outdir        output directory [default: '.']

optional arguments:
  -h, --help    show this help message and exit
  -c, --chatty  display sources in progress
```
