### ISSUE TITLE
openquake.risklib.riskmodels.ValidationError can be improved to throw error only for taxonomy used in analysis

### ISSUE THREAD

**Issue by nicolepaul** [gem/oq-engine#6242]
I ran into an issue where the `openquake.risklib.riskmodels.ValidationError` was thrown because a building class was defined in the `structural_vulnerability_file` and not the `occupants_vulnerability_file`. However, this building class was not referenced in the `exposure_file` or the `taxonomy_mapping_csv`, and the analysis should have been able to complete successfully without this validation check.

While this is generally desirable behavior, it would be better to run the check _only_ for building classes actually referenced in the `exposure_file` or the `taxonomy_mapping_csv`.

**Comment by mchoyos** [comment]
I ran into the same issue while working with Colombia. At the end, to run the analysis, I had to format every single file (structural, contents and BI) in exactly the same manner and get rid of all the typologies that were not included in the taxonomy_mapping. As stated by nicole the check should only be done for building classes within the taxonomy_mapping or exposure_file if this last one is not available.

**Comment by CatalinaYepes** [comment]
Example of this issue in

**Comment by micheles** [comment]
I cannot work on this unless you give me an example.

**Comment by nicolepaul** [comment]
The validation error will be raised in the ScenarioRisk demo if you insert the following lines within the **structural_vulnerability_model.xml** file.

```
    <vulnerabilityFunction dist="LN" id="Unknown">
      <imls imt="PGA"> 0.0001 0.2 0.4 0.6 0.8 1.0 1.2 1.4 </imls>
      <meanLRs> 0.0001 0.05 0.21 0.4 0.56 0.67 0.76 0.82 </meanLRs>
      <covLRs> 0.3 0.3 0.3 0.1 0.1 0.1 0.1 0.1 </covLRs>
    </vulnerabilityFunction>
```

Full model attached: [taxonomy_mismatch.zip](https://github.com/gem/oq-engine/files/5814663/taxonomy_mismatch.zip)
