### ISSUE TITLE
An idea for optimizing single-site calculations

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6260]
There is a solution that is very simple: just add a method `gsim.get_mean_std1(ctx, imts)` where `ctx` is a context object describing an array of `U` ruptures and with attributes like `.mag` (an array of `U` values) and `.rrup` (an array of `U` values) and `imts` is a list of `M` intensity measure type objects, returning an array of shape `(2, U, M)` containing means and total stddevs.
This is very inconvenient because in principle one would need to reimplement all the GSIMs and keep two implementations (one optimized for many sites, the other for a single site). In practice however, consider a very slow calculation (i.e. Popoyan): then one can implement `gsim.get_mean_std1(ctx, imts)`  only for the GSIMs relevant to that calculation and get a big speedup. In practice, we could implement the method only on demand and when really needed, with a fall back with the old behavior
if the method is missing.

**Comment by mmpagani** [comment]
I am not worried by the fact that this needs tailored implementation for each gsim. As you suggest, we can do this on demand. Let's build a first working case.
