### ISSUE TITLE
Proposal: gridding the point sources

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6263]
This is an idea from @mmpagani : we could improve the performance for distributed seismicity by using a raw grid of point sources that would be seen by far away sites, while close sites would see the original sources. The plot below shows a raw grid of 50 km superimposed to the original grid of 10 km for some area sources in Europe:
![gridding2](https://user-images.githubusercontent.com/2463856/99215396-04614b80-27d3-11eb-9420-ecdad9769a98.png)
In practice we would need to define a class `CollapsedPointSource` corresponding to a cluster of point sources in the same square of the grid. For distant sites (say more distant than the `pointsource_distance`) each `CollapsedPointSource` would act as an effective point source with occurrence rate obtained by summing the occurrence rates of the underlying point sources. That would drastically reduce the number of sources and ruptures; assuming that most sites will be distant, going from a 10 km grid to a 50 km effective grid will give a potential speedup of 25 times. The idea is good, but the impact on the final numbers has to be assessed.

There is also some preliminary work to be done.

1. We will need to split and filter the sources in the preclassical phase, so that we it will be possible to build the
    CollapsedPointSources *before* starting the real calculation. This has an impact on memory and data transfer.
2. We will need to implement a gridding algorithm to define the raw grid and some glue code to manage
    the sources. Notice that there will be a different grid for each different tectonic region type since the engine splits the
    sources by TRT (actually by `grp_id`).

**Comment by mmpagani** [comment]
Thanks Michele! I like what you did. In parallel, I wonder if we should/could put the sites into a spatial-index structure to improve the efficiency in retrieving them.
