### ISSUE TITLE
How to prepare an input files for Windows version?

### ISSUE THREAD

**Issue by rameshpudi** [gem/oq-engine#6266]
Dear All,
I hope all are doing well.
Can someone help me out to prepare an inputs for OpenQuake in windows version? I'm going through manual of OpenQuake but I couldn't understand how to prepare a .xml input file which they have given in demo files.
Your kind help shall be highly appreciated.
Thanks in advance
regards,
Ramesh

**Comment by micheles** [comment]
For this kind of questions the appropriate forum is the mailing list: https://groups.google.com/u/1/g/openquake-users
