### ISSUE TITLE
implement the "minimum_asset_loss" parameter for scenario calculators

### ISSUE THREAD

**Issue by hcrowley** [gem/oq-engine#6320]
I would like to request that the "minimum_asset_loss" parameter (currently implemented in the "ebrisk" calculator) also be added to the following scenario calculators: damage, risk and ShakeMap. 

I am currently running scenarios to test the European Seismic Risk Model (ESRM20), and I would like to be able to compare the mean and standard deviation of loss for these scenarios against the reported losses, under the same assumptions as those used in the probabilistic risk model. Whilst I could implement the "minimum_asset_loss" myself in post-processing to get the mean loss, I cannot see a way to do so for the standard deviation of loss (based on the current set of outputs).

**Comment by micheles** [comment]
It is already done for scenario_risk and shakemap. For scenario_damage with economic losses is more difficult. Do you really need that feature or can it wait?

**Comment by hcrowley** [comment]
Thanks Michele. Sorry, you're right, I only need it for scenario risk and ShakeMap (not damage).
