### ISSUE TITLE
Possibility of using multiple taxonomy_mapping files within a risk calculation (one per vulnerability file used)

### ISSUE THREAD

**Issue by mchoyos** [gem/oq-engine#6324]
While running a full risk analysis for Colombia (considering structural, contents and BI), it was seen that the vulnerability file for each of these was considering different vulnerability_function_ids, even for the same typology in the exposure. (Exposure: MUR/LWAL+DNO/H:2/COM2, Structural_vulnerability: MUR_LWAL-DNO_H2, contents_vulnerability: MUR_LWAL-DNO_H1_COM2, BI_vulnerability: MUR/LWAL+DNO/H:1/COM2)

For example, for structural losses the COMX or INDX code may not be needed as only the structural characteristics are of interest, but for contents or BI this code will be the one that will be used as the basis for assigning a specific vulnerability curve. This is why it may be easier to provide a different taxonomy_mapping for each type of vulnerability file to be used (structural, contents or BI) than trying to homogenize all the vulnerability curves and taxonomies.

Right now this is the process that is being followed (trying to homogenize every file) but in the case of structural that means repeating multiple times the same vulnerability, when this process is not really needed.

**Comment by nicolepaul** [comment]
I had the same thought and experience a similar challenge, also due to incorporation of refined occupancy classes for business interruption (which do not impose any difference in the structural or contents vulnerability curves). The ability to take in different taxonomy mapping files for the different loss types would be much easier for the analyst.

However, I'll also note that implementing a fix for this challenge using multiply taxonomy mapping files could result in an error thrown during a check of the risk/vulnerability inputs. In the past, I've experienced that you need the same vulnerabilityFunction id's across all loss types, otherwise an error is thrown. A solution for that could be to check that all vulnerability curve id's mentioned within the taxonomy mapping file exist within the respective vulnerability xml, rather than checking consistency of id's across vulnerability xmls.

**Comment by nicolepaul** [comment]
A proposed change would be to allow additional job configuration commands such as:

```
[taxonomy mapping]
taxonomy_mapping_structural = taxonomy_map_structural.csv
taxonomy_mapping_business_interruption = taxonomy_map_business_interruption.csv
```

This could allow the taxonomy maps for the different loss types to differ. Here is a simple example to demonstrate what those files might look like.

**taxonomy_map_structural.csv**
```
taxonomy,conversion,weight
Wood/Res,Wood,1
Adobe/Res,Adobe,1
Wood/Com,Wood,1
Adobe/Com,Adobe,1
```

**taxonomy_map_business_interruption.csv**
```
taxonomy,conversion,weight
Wood/Res,Wood/Res,1
Adobe/Res,Adobe/Res,1
Wood/Com,Wood/Com,1
Adobe/Com,Adobe/Com,1
```

This would allow the taxonomy id's in the corresponding vulnerability xml files to differ. An example that would correspond to this case is as follows

**job_eb.ini**
```
[vulnerability]
structural_vulnerability_file = structural_vulnerability_model.xml
business_interruption_vulnerability_file = business_vulnerability_model.xml
```

**structural_vulnerability_model.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<nrml xmlns="http://openquake.org/xmlns/nrml/0.5">
<vulnerabilityModel id="Nepal" assetCategory="buildings" lossCategory="structural">
	<vulnerabilityFunction dist="LN" id="Wood">
		<imls imt="PGA"> 0.0001 0.2 0.4 0.6 0.8 1.0 1.2 1.4 </imls>
		<meanLRs> 0.0001 0.05 0.21 0.4 0.56 0.67 0.76 0.82 </meanLRs>
		<covLRs> 0.3 0.3 0.3 0.1 0.1 0.1 0.1 0.1 </covLRs>
	</vulnerabilityFunction>
	<vulnerabilityFunction dist="LN" id="Adobe">
		<imls imt="PGA"> 0.0001 0.2 0.4 0.6 0.8 1.0 1.2 1.4 </imls>
		<meanLRs> 0.0001 0.28 0.67 0.85 0.93 0.96 0.98 0.99 </meanLRs>
		<covLRs> 0.3 0.3 0.1 0.1 0.1 0.1 0.1 0.1 </covLRs>
	</vulnerabilityFunction>
</vulnerabilityModel>
</nrml>
```

**business_vulnerability_model.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<nrml xmlns="http://openquake.org/xmlns/nrml/0.5">
<vulnerabilityModel id="Nepal" assetCategory="buildings" lossCategory="business_interruption">
    <vulnerabilityFunction dist="LN" id="Wood/Res">
        <imls imt="PGA">0.0001 0.2 0.4 0.6 0.8 1.0 1.2 1.4</imls>
        <meanLRs>0.0001 0.08 0.23 0.38 0.51 0.62 0.7 0.76</meanLRs>
        <covLRs>0.3 0.3 0.3 0.3 0.1 0.1 0.1 0.1</covLRs>
    </vulnerabilityFunction>
    <vulnerabilityFunction dist="LN" id="Adobe/Res">
        <imls imt="PGA">0.0001 0.2 0.4 0.6 0.8 1.0 1.2 1.4</imls>
        <meanLRs>0.0001 0.07 0.22 0.38 0.51 0.62 0.7 0.76</meanLRs>
        <covLRs>0.3 0.3 0.3 0.3 0.1 0.1 0.1 0.1</covLRs>
    </vulnerabilityFunction>
    <vulnerabilityFunction dist="LN" id="Wood/Com">
        <imls imt="PGA">0.0001 0.2 0.4 0.6 0.8 1.0 1.2 1.4</imls>
        <meanLRs>0.0001 0.08 0.23 0.38 0.51 0.62 0.7 0.76</meanLRs>
        <covLRs>0.3 0.3 0.3 0.3 0.1 0.1 0.1 0.1</covLRs>
    </vulnerabilityFunction>
    <vulnerabilityFunction dist="LN" id="Adobe/Com">
        <imls imt="PGA">0.0001 0.2 0.4 0.6 0.8 1.0 1.2 1.4</imls>
        <meanLRs>0.0001 0.07 0.22 0.38 0.51 0.62 0.7 0.76</meanLRs>
        <covLRs>0.3 0.3 0.3 0.3 0.1 0.1 0.1 0.1</covLRs>
    </vulnerabilityFunction>
</vulnerabilityModel>
</nrml>
```

A full example model to test this case is attached: [multi_taxonomy_map.zip](https://github.com/gem/oq-engine/files/5819768/multi_taxonomy_map.zip)

**Comment by CatalinaYepes** [comment]
We should also extend the taxonomy mapping to the secondary perils, which should be different for liquefaction and landslides:
```[taxonomy mapping]
...
taxonomy_mapping_liquefaction = taxonomy_map_liquefaction.csv
taxonomy_mapping_landslides = taxonomy_map_landslides.csv```

**Comment by micheles** [comment]
I would prefer to keep everything in a single file, so I could use pandas to read it:
```csv
taxonomy,conversion,loss_type,weight
Wood/Res,Wood,structural,1
Adobe/Res,Adobe,structural,1
Wood/Com,Wood,structural,1
Adobe/Com,Adobe,structural,1
taxonomy,conversion,business_interruption,weight
Wood/Res,Wood/Res,business_interruption,1
Adobe/Res,Adobe/Res,business_interruption,1
Wood/Com,Wood/Com,business_interruption,1
Adobe/Com,Adobe/Com,business_interruption,1
```
Do you see any problem with that?

**Comment by nicolepaul** [comment]
From the standpoint of accommodating different weight schemes for different loss types within a given peril, I don't see any problem using a single file for the taxonomy map. I imagine it would be nice to have different perils separated, as @CatalinaYepes suggests, but will defer to her input on that.

**Comment by micheles** [comment]
Actually we already have a format for multiple CSV files keyed by the loss type, used in multirisk calculations, so I will use that format:
```
taxonomy_mapping_csv = {
  "structural": "taxonomy_map_structural.csv",
  "business_interruption": "taxonomy_map_business_interruption.csv"}
```
