### ISSUE TITLE
Invalid character name (for Windows)

### ISSUE THREAD

**Issue by emthompson-usgs** [gem/oq-engine#6347]
In trying to install on windows, I got an error that appears to be because a file name contains a character that is not valid for  Windows (`site-packages/openquake/qa_tests_data/classical_risk/case_5/èxposure_model.xml`). The full issue is described here: 
https://github.com/conda-forge/openquake.engine-feedstock/issues/27
This does not happen if I install via pip, but I thought it would be an easy thing to fix.

**Comment by micheles** [comment]
Ah, interesting. It could be that that test case is there on purpose, because we had users using non-ASCII filenames. We should probably forbid some filenames for maximum portability, but we risk breaking things for our users. Let us think a bit about that.

**Comment by emthompson-usgs** [comment]
Thanks @micheles. I think I may have hastily jumped to an inaccurate conclusion when I saw the unusual character. The actual error message is:
```
CondaVerificationError: The package for openquake.engine located at D:\miniconda\pkgs\openquake.engine-3.8.1-py_1
appears to be corrupted. The path 'site-packages/openquake/qa_tests_data/classical_risk/case_5/èxposure_model.xml'
specified in the package manifest cannot be found.
```
So if the reason that this file is not in the manifest is because of the special character, then the character is the underlying problem. But I don't actually know that. The thing that is perplexing to me is that the package installs fine via pip, and the conda package is built from the pip package. I'll continue to experiment with the installation process and try to understand this issue better.

**Comment by micheles** [comment]
I did not hear anything. Can I close the issue?

**Comment by emthompson-usgs** [comment]
Yes, please close the issue.
