### ISSUE TITLE
Support aggregations with thousands of tags in ebrisk

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6357]
There is the need to store the asset loss table in small calculations (i.e. for Baloise) and in general big aggregated event loss tables in large calculations (i.e. for Canada, Europe). As it is now the performance is terrible if there are more than 10,000 tags because the approach used was design to manage efficiently the case of few tags. Since most of the aggregations are zero, the solution is to store an `agg_loss_table` with fields event_id, agg_id, structural, nonstructural, ... akin to the GMF table.

**Comment by micheles** [comment]
The really hard part is changing the `agg_curves` and `agg_losses` dataset dimensionalities from PRLT... and LRT... to PRLT and LRT. This break the exporters and all the extractors.

**Comment by raoanirudh** [comment]
> The really hard part is changing the `agg_curves` and `agg_losses` dataset dimensionalities from PRLT... and LRT... to PRLT and LRT. This break the exporters and the extractors.

What do PRLT and LRT stand for?

**Comment by micheles** [comment]
P = number of return periods
R = number of realizations
L = number of loss types
T = number of aggregations to perform
