### ISSUE TITLE
bindi_2011 missing DEFINED_FOR_REFERENCE_VELOCITY

### ISSUE THREAD

**Issue by hcrowley** [gem/oq-engine#6430]
The ground motion model "bindi_2011.py" does not have the term "DEFINED_FOR_REFERENCE_VELOCITY" and so it cannot be used with custom amplification functions. Can this definition be added?

**Comment by rcgee** [comment]
Hi Helen, 

The DEFINED_FOR_REFERENCE_VELOCITY parameter was originally added only to GMPEs in the global mosaic, specifically those derived for rock conditions without built-in amplification functions/factors. This was needed to compute a global hazard map with uniform site conditions.

We haven’t yet worked on applying this parameter to the others GMPEs. We can certainly add this improvement to the list of things to do. Note that in many cases a reference velocity was not used in the development of the GMPEs, so I’m not sure it would always make sense to add it.

**Comment by micheles** [comment]
Closing since nobody protested for nearly 3 years.
