### ISSUE TITLE
Case with multiple exposure xmls and business interruption vulnerability throws ValueError

### ISSUE THREAD

**Issue by nicolepaul** [gem/oq-engine#6465]
In general, we can supply multiple exposure model xmls into one risk job. For example:

```
[exposure]
exposure_file =
 exposure_model_1.xml
 exposure_model_2.xml
```

This format works well with structural, nonstructural, and fatality vulnerability models, but throws the following error when using a business interruption vulnerability model:

`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

The desired behavior would be for the exposure models to be combined and the analysis to perform as usual, just like it does for the case without business interruption.

An example model to replicate this behavior is attached: [multi_exposure_bi.zip](https://github.com/gem/oq-engine/files/5819647/multi_exposure_bi.zip)

The desired behavior (which does not throw the error) can be demonstrated by commenting out line 19 of the **job_eb.ini** file.

**Comment by micheles** [comment]
This is surprising but looks easy to fix.
