### ISSUE TITLE
unclear error when hypocentral depth PMF includes probability = 0 

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#6475]
This comes from the forum post [Occurrence Rates Error](https://groups.google.com/g/openquake-users/c/NE3uUIlKFbM).

The user reports getting "ValueError: occurrence rate must be positive" despite using MFDs with reasonable parameters. I think the issue is actually in the depth distribution for some sources that have depths for which probability="0.0":

<hypoDepthDist>
<hypoDepth depth="125.0" probability="0.36"/>
<hypoDepth depth="175.0" probability="0.64"/>
<hypoDepth depth="225.0" probability="0.0"/>
<hypoDepth depth="275.0" probability="0.0"/>
<hypoDepth depth="325.0" probability="0.0"/>
<hypoDepth depth="375.0" probability="0.0"/>
<hypoDepth depth="425.0" probability="0.0"/>
<hypoDepth depth="475.0" probability="0.0"/>
<hypoDepth depth="525.0" probability="0.0"/>
<hypoDepth depth="575.0" probability="0.0"/>
<hypoDepth depth="625.0" probability="0.0"/>
<hypoDepth depth="675.0" probability="0.0"/>
<hypoDepth depth="725.0" probability="0.0"/>
<hypoDepth depth="775.0" probability="0.0"/>
</hypoDepthDist>

The error no longer occurs when these extra rows are removed. The error message could instead indicate the issue with the probabilities, or give a warning that these depths have no impact. 

See example job.zip. 
[job.zip](https://github.com/gem/oq-engine/files/5838188/job.zip)

**Comment by micheles** [comment]
Thanks for the analysis Kendra, the problem is now solved. The user will get an error while reading the source model:
```python
ValueError: node hypoDepthDist: Zero probability for 97.5, line 50 of /home/michele/Downloads/Source_Model_small.xml
```
