### ISSUE TITLE
Plotting declustering

### ISSUE THREAD

**Issue by Enjoyproyect** [gem/oq-engine#6529]
Hi, I'm using the tool in python, and I was trying to implement a plot for my decluster catalogue, but It appears the method is not developed yet. Could you explain if this is something in develop at immediate future?

**Comment by micheles** [comment]
Please these questions should go in the mailing list, not in GitHub: https://groups.google.com/u/1/g/openquake-users

**Comment by mmpagani** [comment]
To which type of plot are you referring to?
