### ISSUE TITLE
Fix some risk outputs

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6536]
The ones listed here: https://gitlab.openquake.org/openquake/oq-risk-outputs/-/merge_requests/24

**Comment by raoanirudh** [comment]
Porting the issue from GitLab

## Scenario Damage
### Display names
![scenario_damage_display](https://user-images.githubusercontent.com/1707414/108527156-3c949080-72d2-11eb-8615-4ba3cbd5f5ab.png)

### File names
![scenario_damage_filenames](https://user-images.githubusercontent.com/1707414/108527172-41594480-72d2-11eb-8722-ba5ffea74579.png)

### Comments
1. avg_damages files renamed to damages, borrowing the name from classical_damage: rollback to avoid inconsistency with the avg_losses name choice
2. Average Asset Damages renamed to Asset Damage Distribution, borrowing the name from classical_damage: rollback to avoid inconsistency with the Average Asset Losses name choice

## Scenario Risk
### Display names
![scenario_risk_display](https://user-images.githubusercontent.com/1707414/108527198-4c13d980-72d2-11eb-8b49-f59a05ae2268.png)

### File names
![scenario_risk_filenames](https://user-images.githubusercontent.com/1707414/108527213-51712400-72d2-11eb-80e6-68db7a9f6ccd.png)

### Comments
1. aggregate_by added to scenario_risk: great!
2. total losses (was called agglosses) output replaced by agg_losses: ok
   - scenario_risk/agglosses_1.csv removed
   - scenario_risk/agg_losses-rlz-000_1.csv new output
   - scenario_risk/agg_losses-mean_1.csv new output
3. Aggregate Event Losses aka losses_by_event output missing: can we bring it back?


## Event Based Damage
### Display names
![event_based_damage_display](https://user-images.githubusercontent.com/1707414/108527227-57ff9b80-72d2-11eb-9a00-53312d4f05e4.png)

### File names
![event_based_damage_filenames](https://user-images.githubusercontent.com/1707414/108527249-5d5ce600-72d2-11eb-82ec-8fe7b54f337d.png)

### Comments
1. avg_damages files renamed to damages, borrowing the name from classical_damage: rollback to avoid inconsistency with the avg_losses name choice
2. Average Asset Damages renamed to Asset Damage Distribution, borrowing the name from classical_damage: rollback to avoid inconsistency with the Average Asset Losses name choice

## Event Based Risk
### Display names
![event_based_risk_display](https://user-images.githubusercontent.com/1707414/108527275-6352c700-72d2-11eb-8711-11d696c0f665.png)

### File names
![event_based_risk_filenames](https://user-images.githubusercontent.com/1707414/108527295-6948a800-72d2-11eb-92ed-ca1f2dcc9fd8.png)

### Comments
1. aggregate_by added to event_based_risk: great!
2. Asset Loss Maps / loss_maps outputs removed: ok
3. total loss curves merged into the new output agg loss curves: ok
   - tot_curves-rlzs_1.csv removed
   - tot_curves-stats_1.csv removed
   - tot_losses-mean_1.csv removed
   - tot_losses-quantile-0.5_1.csv removed
   - tot_losses-rlz-000_1.csv removed
4. Aggregate Event Losses aka losses_by_event output missing: can we bring it back?
5. Individual asset loss curves output replaced by agg loss curves: I guess the idea is that if the user needs the asset loss curves they must now set `aggregate_by = id`? Seems reasonable.
6. New outputs Aggregate Losses / agg_losses added: need to check what these outputs are showing.
5. agg_losses zero rows removed?
   - event_based_risk/agg_losses-mean_1.csv is shorter
   - event_based_risk/agg_losses-quantile-0.5_1.csv is shorter
6. src_loss_table_1.csv 
   - 2 → 2;0 and 2;1

## EB Risk
### Display names
![ebrisk_display](https://user-images.githubusercontent.com/1707414/108527328-71084c80-72d2-11eb-9b65-a25e5c46a59b.png)

### File names
![ebrisk_filenames](https://user-images.githubusercontent.com/1707414/108527342-75cd0080-72d2-11eb-95f0-fa771062f11e.png)


### Comments
1. ebrisk total loss curves merged into agg loss curves
   - ebrisk/tot_curves-rlzs_1.csv removed
   - ebrisk/tot_curves-stats_1.csv removed
   - ebrisk/tot_losses-mean_1.csv removed
   - ebrisk/tot_losses-quantile-0.5_1.csv removed
   - ebrisk/tot_losses-rlz-000_1.csv removed
2. ebrisk agg_curves-stats output split into separate files for mean and quantile
   - ebrisk/agg_curves-stats_1.csv removed
   - ebrisk/agg_curves-mean_1.csv new output
   - ebrisk/agg_curves-quantile-0.5_1.csv new output
3. ebrisk agg_curves-rlzs file renamed
   - ebrisk/agg_curves-rlzs_1.csv removed
   - ebrisk/agg_curves_1.csv new file
4. ebrisk agg_losses zero rows removed?
   - ebrisk/agg_losses-mean_1.csv is shorter
   - ebrisk/agg_losses-quantile-0.5_1.csv is shorter
5. ebrisk/src_loss_table_1.csv 
   - 2 → 2;0 and 2;1

**Comment by CatalinaYepes** [comment]
Adding to the list of improvements for the risk-outputs:

- [ ] Include in the log file of scenario_risk (or scenario_damage with consequence) the standard deviation in the summary of the portfolio loss.
- [ ] To be consistent with the outputs of `scenario_damage`, we should organise the order of the columns in the losses_by_event as:
`[event_id, rlz_id, loss_types, ...]`
instead of 
`[event_id, loss_types, ..., rlz_id]`
- [ ] The following risk outputs are missing the OQ stamp at the beginning of the output (`#,,,,"generated_by='OpenQuake engine ...`):
 - dmg_by_event_X.csv
 - events_X.csv
 - realizations_X.csv
 - sigma_epsilon_X.csv
 - sitemesh_X.csv
