### ISSUE TITLE
Flexible Exposure input file

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#6587]
It is frequent to have exposure models with more information than the one required for running a risk calculation in OpenQuake. Moreover, exposure files format usually have headers that change based on the modeller's preference and language (e.g. the field `night` could be called `occupants_night` or `population at night`).
_`This is applicable for input models in .csv format`_

The idea is that OpenQuake accepts an `exposure.xml` with a more flexible structure, allowing mapping between the OQ required fields and the exposure `csv` files.

- The example below presents an example typical for the GRM model (2018)
- Columns do not need to follow a given order
- The headers can include spaces. Raise a clear error if the headers include not accepted characters.
- Follow a similar structure for exposure files that include `business interruption` and insured losses (`insuranceLimit` and `deductible`)

### Example exposure file in `xml`
```
<?xml version='1.0' encoding='UTF-8'?>
<nrml xmlns:gml="http://www.opengis.net/gml" 
      xmlns="http://openquake.org/xmlns/nrml/0.5">

<exposureModel id="exposure1" category="buildings">
  <description>Here is the description of a flexible exposure model</description>

  <conversions>
    <area type="per_asset" unit="SQM" />
    <costTypes>
      <costType name="structural" type="per_area" unit="USD" />
      <costType name="nonstructural" type="per_asset" unit="USD" />
      <costType name="contents" type="per_asset" unit="USD" />
      <costType name="business_interruption" type="per_asset" unit="USD/month" />
    </costTypes>
  </conversions>

  <exposureFields>
    <field oq="id" input="ASSET_ID" />
    <field oq="lon" input="LONGITUDE" />
    <field oq="lat" input="LATITUDE" />
    <field oq="taxonomy" input="TAXONOMY" />
    <field oq="number" input="BUILDINGS" />
    <field oq="area" input="AREA_PER_DWELLING_SQM" />
    <field oq="value" type="structural" input="COST_PER_AREA_USD" />
    <field oq="value" type="nonstructural" input="COST_NONSTRUCTURAL_USD" />
    <field oq="value" type="contents" input="COST_CONTENTS_USD" />

    <field oq="night" input="OCCUPANTS_PER_ASSET" />

  </exposureFields>

  <occupancyPeriods>night</occupancyPeriods>
  <tagNames>OCCUPANCY NAME_1 ID_1 NAME_2 ID_2</tagNames>
  <assets>Exposure_File_1.csv Exposure_File_2.csv Exposure_File_3.csv </assets>
    
</exposureModel>

</nrml>
```

### Example exposure file in `csv`
[Example_Exposure.csv.zip](https://github.com/gem/oq-engine/files/6100877/Example_Exposure.csv.zip)

ASSET_ID | NAME_1 | ID_1 | NAME_2 | ID_2 | LONGITUDE | LATITUDE | TAXONOMY | DWELLINGS | OCCUPANTS_PER_ASSET | SETTLEMENT_TYPE | DWELLINGS_PER_BUILDING | AREA_PER_DWELLING_SQM | COST_PER_AREA_USD | BUILDINGS | TOTAL_REPL_COST_USD | COST_STRUCTURAL_USD | COST_NONSTRUCTURAL_USD | COST_CONTENTS_USD | OCCUPANCY
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Res_1 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | EU/LWAL+DNO/H:1 | 136 | 518.9 | Rural | 1 | 63 | 322 | 136 | 3448620 | 1034586 | 1724310 | 689724 | Res
Res_2 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | MCF/LWAL+DUL/H:1 | 2527 | 9641.3 | Rural | 1 | 85 | 430 | 2527 | 115452313 | 34635693.8 | 57726156.3 | 23090462.5 | Res
Res_3 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | MCF/LWAL+DUL/H:2 | 2527 | 9641.3 | Rural | 1 | 127.5 | 430 | 2527 | 173178469 | 51953540.6 | 86589234.4 | 34635693.8 | Res
Res_4 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | ME+MEO/LN/H:1+HFAPP:1 | 104 | 396.8 | Rural | 1 | 63 | 322 | 104 | 2637180 | 791154 | 1318590 | 527436 | Res
Res_5 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | ME+MEO/LN/HBET:1-2 | 156 | 595.2 | Rural | 1.5 | 63 | 322 | 104 | 3955770 | 1186731 | 1977885 | 791154 | Res
Res_26 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | UNK/H:1 | 304 | 1159.6 | Urban | 1 | 63 | 322 | 304 | 7708680 | 2312604 | 3854340 | 1541736 | Res
Res_27 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | W+WBB/LPB+DNO/H:1 | 15460 | 58973.7 | Urban | 1 | 63 | 322 | 15460 | 392026950 | 117608085 | 196013475 | 78405390 | Res
Res_28 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | W+WBB/LPB+DNO/H:1+HFAPP:1 | 15460 | 58973.7 | Urban | 1 | 63 | 322 | 15460 | 392026950 | 117608085 | 196013475 | 78405390 | Res
Res_29 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | W+WLI/LWAL+DUL/H:1 | 3638 | 13877.5 | Urban | 1 | 85 | 430 | 3638 | 166211125 | 49863337.5 | 83105562.5 | 33242225 | Res
Res_30 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | W+WO/LN/H:1 | 3638 | 13877.5 | Urban | 1 | 63 | 322 | 3638 | 92250585 | 27675175.5 | 46125292.5 | 18450117 | Res
Res_31 | Ayeyawady | MMR.1 | Hinthada | MMR.1.2 | 95.19 | 17.88 | W+WO/LN/H:1+HFAPP:1 | 1819 | 6938.7 | Urban | 1 | 63 | 322 | 1819 | 46125292.5 | 13837587.8 | 23062646.3 | 9225058.5 | Res
Res_88 | Ayeyawady | MMR.1 | Maubin | MMR.1.3 | 95.57 | 16.95 | MUR/LWAL+DNO/H:1 | 228 | 973.3 | Urban | 1 | 63 | 322 | 228 | 5781510 | 1734453 | 2890755 | 1156302 | Res
Res_89 | Ayeyawady | MMR.1 | Maubin | MMR.1.3 | 95.57 | 16.95 | MUR/LWAL+DNO/H:2 | 228 | 973.3 | Urban | 1 | 94.5 | 322 | 228 | 8672265 | 2601679.5 | 4336132.5 | 1734453 | Res
Res_90 | Ayeyawady | MMR.1 | Maubin | MMR.1.3 | 95.57 | 16.95 | UNK/H:1 | 1104 | 4712.7 | Urban | 1 | 63 | 322 | 1104 | 27994680 | 8398404 | 13997340 | 5598936 | Res

**Comment by pslh** [comment]
It occurs to me that we might use the same or a similar approach to make it possible to read OED format exposure data for use with the oq-engine. We would still need to either map the OED codes to a GEM Taxonomy or perhaps construct a composite taxonomy value (maybe something like "taxonomy=OccupancyCode:ConstructionCode") but I could see value in making it easier for people already using OASIS to use their files with the oq-engine.
