### ISSUE TITLE
Adjustment for LanzanoEtAl2016 gmm

### ISSUE THREAD

**Issue by mascandola** [gem/oq-engine#6665]
Hi,
in the gmm LanzanoEtAl2016 there are 4 parameters for site:
 REQUIRES_SITES_PARAMETERS = {'vs30', 'lon', 'lat', 'bas'} 

When I use this gmm for hazard calculations I get an error in .".../openquake/hazardlib/site.py", line 236.
I think this is due to the lack of  -> 'bas': numpy.bool, <- between the list of valid site parameters
Can you please correct this in site.py? 
Since the 'bas' term is boolean, probably you need also to correct the gmm file Lanzano_2016.py at line 201, to sobstitute "sites.bas == 1.0" with "sites.bas == 1".

Let me know,
thank you
claudia

**Comment by micheles** [comment]
You need to provide a job.zip archive providing an example calculation using a site model with the "bas" term. The example calculation must be small and run in less than 5 seconds.

**Comment by mascandola** [comment]
Here you are, in the attachment. The example calculation is small but it runs in 10 seconds. I was not able to reduce the time of calculation, are you able to reduce it? I use just one site and one area source. 
[TEST_NI15_1.zip](https://github.com/gem/oq-engine/files/6270520/TEST_NI15_1.zip)

**Comment by mascandola** [comment]
Well, It would run in 10 seconds, but if you try this example (with the LanzanoEtAl2016 gmm) it crashes after few seconds for the problem I have mentioned..

**Comment by micheles** [comment]
The test is fine and the issue fixed now
