### ISSUE TITLE
scenario_risk + aggregation errors

### ISSUE THREAD

**Issue by schmidni** [gem/oq-engine#6671]
3 minor things, none of them major but I'd like to report them:

1. there is a limit on the aggregation keys which can be stored, it would be nice to be able to increase that limit from the config file.
2. when running the same calculation with and without "aggregate_by", the calculation with "aggregate_by" returns 0 avg loss and a warning "agg_losses != sum(avg_losses)" while the calculation without aggregate_by runs normally
[calc_noagg.txt](https://github.com/gem/oq-engine/files/6269762/calc_noagg.txt)
[calc_agg.txt](https://github.com/gem/oq-engine/files/6269763/calc_agg.txt)
3. running automatic export for a calculation with aggregate_by returns an error
[error_export_output.txt](https://github.com/gem/oq-engine/files/6269800/error_export_output.txt)

**Comment by micheles** [comment]
I need a small calculation that I can run to reproduce the export error.

**Comment by schmidni** [comment]
hi michele, I'm sorry, I think I just figured out the cause of the problem - it actually is my own fault.

I raised the aggregation key limit in `risklib/asset.py` by setting `TWO16=2**32`. If I then make a calculation with >= 2^16  aggregation keys, the two errors described above occur.
I therefore guess, that I didn't make necessary changes elsewhere to deal with that many aggregation keys? So basically my 1st point, to be able to increase the limit, is the final request ^^

Just tell me in case you still need a calulation to reproduce the problem and I'll send you the files by mail.

**Comment by micheles** [comment]
The limit is there to stop users from trying to create the full asset loss table (I assuming you are aggregating by asset ID), which sends the engine out of memory for large calculations. What do you want to obtain at the end? It has to be implemented as a plugin without requiring storing the full asset loss table.

**Comment by schmidni** [comment]
I have no problems doing calculations with 2^16 keys on my laptop, and also no problems running a calculation with 167000 keys on a larger machine (haven't tried on my laptop). I can also access the agg_loss_table aftewards directly on the datastore - so no problems there.

We would like to have not only average values but also be able calculate some statistics on the results, eg. poe

**Comment by micheles** [comment]
I tried to raise the limit but as I expected it has disastrous effects on our calculations, so I cannot implement that feature. What you can do is to split the exposure so that you are below the limit. The full asset loss table is accessible to the engine during the calculation, in the function https://github.com/gem/oq-engine/blob/master/openquake/calculators/event_based_risk.py#L72
so any additional logic processing the losses and computing statistics could be put there, but that part of the code is hairy and frequently changed (it changed yesterday; it will likely change again today or tomorrow) so I would not recommend to touch it.

**Comment by schmidni** [comment]
Thank you very much for trying!

Out of curiosity tough: What were the "disastrous effects"? Did you run even larger calculations? Or are the results for larger calculations not correct anymore?

**Comment by micheles** [comment]
Or you run out of memory, or you do not run out of memory, but the performance characteristic of the calculation as completely different than before, lots of time in spent in places that before where fast, and things like that. The postprocessing step can also become ultra-slow.
