### ISSUE TITLE
Give some support for multiple vulnerability functions?

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6765]
The use case is the one of Murray or Helen: run a calculation with the original vulnerability functions, then with the retrofitted ones and compare. Right now people are not reusing the hazard. This should be easy to implement, even if there are a few choices
open:

1. run multiple calculations by using the sensitivity_analysis trick (easier to implement, less efficient)?
2. run a single calculation by implementing a new specific calculator (more efficient, less easy to implement)?

**Comment by raoanirudh** [comment]
The second choice existed before in the form of the [event_based_bcr](https://github.com/gem/oq-engine/pull/990) calculator, which was eventually deprecated

**Comment by micheles** [comment]
I had completely removed from my memory the existence of that calculator!

**Comment by micheles** [comment]
There is no need to spend much time on this, since
```
$ oq engine --run job_orig.ini job_retro.ini
```
works already and it is good enough.
