### ISSUE TITLE
Remove the XML exporter for the ruptures

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6781]
Reasons:

1. it is broken for the new source typologies introduced by M. Pagani (KiteSources, MultiFaultSources)
2. it would be a lot of work to fix it for the new sources
3. it has been deprecated for years and years
4. we have already a perfect replacement that works out of the box for all kind of sources, included the ones not yet invented (see https://docs.openquake.org/oq-engine/advanced/special-features.html#ruptures-in-csv-format)
5. the replacement (i.e. ruptures in CSV with JSON fields) allows what the risk people wants, i.e. to run scenarios from exported ruptures, while the old XML exporter is not able to do that and never will be, since it is missing crucial information
6. it should have been removed years ago, anyway.

The manual must be updated.

**Comment by raoanirudh** [comment]
For historical context, see: #3601, #4339, #5277, #5379, #5603, #5942, #6547
