### ISSUE TITLE
Add an option to ignore encoding errors

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6838]
As a matter of life, we have exposures with an unknown encoding, where it is very difficult or even impossible (if the CSV files was obtained by merging together files with different encodings) to find the right encoding. While it is correct to raise an error in such cases, we must be pragmatic and allow the user to continue the calculation anyway, at the cost of having descriptions/locations missing some characters (see also @CatalinaYepes  comment to https://github.com/gem/oq-engine/pull/6826). Therefore I propose to introduce a flag in the job.ini called `ignore_encoding_errors` which by default is false.

For instance, for a tag of kind NAME_1 with value "REGIÓN DE TARAPACÁ" (if one were able to convert to the correct encoding) one would get "REGIN DE TARAPAC", but the calculation would run to completion.

**Comment by CatalinaYepes** [comment]
Great suggestion!

**Comment by raoanirudh** [comment]
I also second the suggestion.

Meanwhile, for files that are simply in an encoding other than utf-8 and don't necessarily have encoding errors, is it worth adding an attribute `encoding` to the `<assets>` tag in the exposure xml file? Note that we already have an `encoding` attribute specifying the encoding used for the xml itself, so this would be an additional one. If this attribute is absent, the default assumption would be utf-8.


```xml
<?xml version="1.0" encoding="utf-8"?>
<nrml xmlns="http://openquake.org/xmlns/nrml/0.5" xmlns:gml="http://www.opengis.net/gml">
  <exposureModel category="buildings" id="ex1" taxonomySource="GEM taxonomy">
    <description/>
    <conversions>
      <costTypes>
        <costType name="structural" type="per_asset" unit="USD"/>
      </costTypes>
    </conversions>
    ⋮
    <assets encoding="latin1">
        assets.csv
    </assets>
  </exposureModel>
</nrml>
```

**Comment by micheles** [comment]
It is possible but I do not like it, I prefer to force people to use UTF-8 everywhere. The error message already tells people how to convert latin1 to utf8 with a single command.
