### ISSUE TITLE
CoeffsTable called with unsupported scalar IM is now returning AttributeError rather than KeyError

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#6873]
Possibly a recent change in the behaviour of `openquake.hazardlib.gsim.base.CoeffsTable` has meant that a different error is now raised in the case that a scalar intensity measure is input for which the coefficients are not defined, e.g.:

```python
from openquake.hazardlib.imt import PGV
from openquake.hazardlib.gsim.abrahamson_2015 import AbrahamsonEtAl2015SInter
AbrahamsonEtAl2015SInter.COEFFS[PGV()]
```
now raises:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-7-8111979cc445> in <module>
----> 1 AbrahamsonEtAl2015SInter.COEFFS[PGV()]

~/Documents/OQ/dev/oq-engine/openquake/hazardlib/gsim/base.py in __getitem__(self, imt)
    811         max_below = min_above = None
    812         for unscaled_imt in list(self.sa_coeffs):
--> 813             if unscaled_imt.damping != imt.damping:
    814                 continue
    815             if unscaled_imt.period > imt.period:

AttributeError: 'PGV' object has no attribute 'damping'
```
Previously such a case would have raised a `KeyError`, as is done when inputting SA(T) for T outside the range of supported values. A `KeyError` would be preferable here.

**Comment by micheles** [comment]
Yes, I am aware of the change. I can easily restore the previous behavior, thanks for pointing this out.
