### ISSUE TITLE
BooreEtAl2014 is broken

### ISSUE THREAD

**Issue by cbworden** [gem/oq-engine#6975]
When requesting ```const.StdDev.INTER_EVENT``` the module now returns a scalar rather than the expected array.

In https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/boore_2014.py line 258 is:

```
stddevs.append(tau)
```

it should be something like:

```
stddevs.append(np.full_like(dists.rjb, tau))
```

The other two types of stddev are okay.

**Comment by micheles** [comment]
Looks like a leftover from the recent huge refactoring of hazardlib. See https://groups.google.com/g/openquake-users/c/Tj5t1rJ7MX0/m/BHLrOPt6AQAJ for reasons behind the change.
