### ISSUE TITLE
Why move AtkinsonBoore2006 to boore_atkinson_2008 module?

### ISSUE THREAD

**Issue by cbworden** [gem/oq-engine#7002]
While I understand that they may be superficially similar (mathematically, same two names, similar years, etc.) they are for completely different **applications**. AB06 was designed for eastern North America (i.e., stable cratonic environments), whereas BA08 was part of the NGA-West project, which dealt with active tectonic environments. Further, BA08 has been supplanted by Boore, Stewart, Seyhan, and Atkinson (2014), part of the NGA-West2 project, whereas AB06 remains valid and useful. This is likely why the original designers had them in separate modules in the first place.

**Comment by micheles** [comment]
The AtkinsonBoore2006 was implemented as subclass of AtkinsonBoore2008 in the engine (see for instance
https://github.com/gem/oq-engine/blob/engine-3.11/openquake/hazardlib/gsim/atkinson_boore_2006.py#L46) so for easy of refactoring it was easier to have it in the same module, at least temporarily. Now the AtkinsonBoore2006 is NOT a subclass of 
AtkinsonBoore2008 anymore, so I can restore it to its own module.
