### ISSUE TITLE
Comment about SiteCollection

### ISSUE THREAD

**Issue by cbworden** [gem/oq-engine#7011]
My comment is about the design philosophy of the SitesCollection class. In particular, I’m puzzled about the use of a structured array for the “array” variable. My understanding is that you are refactoring the hazardlib to use numpy arrays as much as possible to allow for vectorization, and possibly the use of Numba, Cython, and/or C. Thus, for instance, you would want (say) the Vs30 data stored as a contiguous array in memory for efficiency. But the structured array keeps each element of Vs30 data associated with its associated latitude, longitude, depth, and any other site parameters maintained in the structure, making memory access inefficient since those things are seldom used together.

From the NumPy documentation (https://numpy.org/doc/stable/user/basics.rec.html):

>Users looking to manipulate tabular data, such as stored in csv files, may find other pydata projects more suitable... **For instance, the C-struct-like memory layout of structured arrays in numpy can lead to poor cache behavior in comparison.** [Emphasis mine.]

You can easily test this yourself by multiplying two large numpy arrays, and then multiplying the same arrays when they are part of a large structured array, timing the results in both cases. I did, and I found the structured array to be about 40% slower.

It seems like a simple dictionary holding pure numpy arrays would be not only more efficient, but simpler to code and maintain. For instance your `add_col()` member function could be reduced to two lines:

```
self.array[colname] = values.copy()
self.array[colname].flags.writeable = False
```

And the `_set()` function could be eliminated completely. Further, you would not have to pre-define the data type of every possible site parameter. If and when the type of an array became important, like when passing it to a C function, you could get it from the array itself and do any necessary conversions then.

**Comment by micheles** [comment]
You are totally right and I am perfectly aware of the issue. Actually, I wanted to change the SiteCollection along the lines you suggest for a long time. Still, the impact on the performance due to the SiteCollection is marginal, so this is very low on my list of priorities. The idea here is to refactor only the parts that have a strong impact on performance. The rest will be left for the future.

**Comment by cbworden** [comment]
Cool. Glad we're thinking about it the same way.
