### ISSUE TITLE
OQ Engine installation on Ubuntu 20.04 as developer

### ISSUE THREAD

**Issue by didnotwork** [gem/oq-engine#7012]
I want to install OQ Engine with Ubuntu 20.04. I tried to install (devel installation) according to[ universal installation script](https://github.com/gem/oq-engine/blob/master/doc/installing/universal.md). 
$ git clone https://github.com/gem/oq-engine.git
The above command works without problem. 
But second command:
cd oq-engine && /usr/bin/python3 install.py devel
doesn't work. Below is the massage I received:
/home/salim/openquake/bin/python: No module named pip
Traceback (most recent call last):
  File "install.py", line 401, in <module>
    install(inst, args.version)
  File "install.py", line 269, in install
    subprocess.check_call([pycmd, '-m', 'pip', 'install', '--upgrade', 
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/salim/openquake/bin/python', '-m', 'pip', 'install', '--upgrade', 'pip', 'wheel']' returned non-zero exit status 1.

How can I go on to install the OQ Engine?

**Comment by micheles** [comment]
Apparently pip is not installed. ``sudo apt install python3-pip`` and then try again.

**Comment by didnotwork** [comment]
pip is installed. Below is the message when I try the command you sent: 
python3-pip is already the newest version (20.0.2-5ubuntu1.5).

**Comment by micheles** [comment]
Then perhaps python3-venv is not installed. You should use the mailing list for this kind of questions. Also our sysadmin is on vacation these days.
