### ISSUE TITLE
reduce_sm does not work for geometryModel with kiteSurface 

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#7063]
The command **oq reduce_sm** does not work for source models with the multiFaultSource typology if the geometry model uses kiteSurfaces. 

Firstly, in order to debug this issue, the kiteSurface code must be added to tag2code:

tag2code = {'ar': b'A',
            'mu': b'M',
            'po': b'P',
            'si': b'S',
            'co': b'C',
            'ch': b'X',
            'no': b'N',
            **'ki': b'K'**}

The problem occurs [here](https://github.com/gem/oq-engine/blob/master/openquake/commonlib/readinput.py#L1127), where src_node.tag returns  ‘{http://openquake.org/xmlns/nrml/0.5}kiteSurface’

This has a different result than for other source typologies because the kiteSurface is inside the geometryModel **section**. The **id** attribute is defined for the section rather than the kiteSurface, so when the next lines of code try to obtain the id, the command fails. 

I'm unable to further resolve this because I don't understand how src_node is defined for use in line 1127.

**Comment by micheles** [comment]
You should send to me the examples you have, @kejohnso 
This is certainly going to be fixed.
