### ISSUE TITLE
Bug in the Abrahamson and Gulerce

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#7067]
In a test hazard calculation I got the following error:
```
File "/Users/mpagani/Repos/venv/src/oq-engine/openquake/hazardlib/gsim/abrahamson_gulerce_2020.py", line 234, in get_rupture_depth_scaling_term
    f_dep[ctx.ztor > 200.0] = C["a11"] * 150.0
TypeError: 'numpy.float64' object does not support item assignment
```
Also, @rcgee experienced problems when creating trellis plots with this model.

**Comment by micheles** [comment]
I do not think it is a bug. Since the signature is
```python
    def compute(self, ctx: np.recarray, imts, mean, sig, tau, phi):
```
it means Abrahamson and Gulerce has been ported to [phase 3](https://github.com/gem/oq-engine/issues/6973) already, so you must pass a recarray, not a normal context. To create a recarray there is the method `ContextMaker.recarray`.
