### ISSUE TITLE
The meaning of DEFINED_FOR_REFERENCE_VELOCITY

### ISSUE THREAD

**Issue by rcgee** [gem/oq-engine#7069]
The `DEFINED_FOR_REFERENCE_VELOCITY` parameter is currently required by GMPEs if we want to use them with with custom amplification functions (e.g., via the convolution approach). This parameter is used to check the compatibility between the reference velocity of the GMPE and the `vs30_ref` value provided in the amplification.csv header before the hazard calculation even starts. This is to prevent users from applying amplification factors on top of GMPEs where the reference condition is not the same. The specific check is that the `DEFINED_FOR_REFERENCE_VELOCITY` must be greater than the `vs30_ref`  in the amplification.csv header.

The issue is that we do not have have a standard definition of `DEFINED_FOR_REFERENCE_VELOCITY` and how it should be determined for each of the GMPEs. There is some ambiguity because many GMPEs don't explicit state (or even have) a reference velocity, and GMPEs have been developed in different ways.

Three different cases are described below:

1. GMPEs that have been derived for only one site condition. This typically includes GMPEs derived for hard rock sites (e.g. `DrouetAlpes2015RjbHR`, applicable for only for Vs30=2000 m/s) or those adjusted for national or regional hazard calculations (e.g. `Campbell2003SHARE`, applicable for only for Vs30=800 m/s). In these cases, should `DEFINED_FOR_REFERENCE_VELOCITY` equal the exact Vs30 values for which the GMPEs have been derived?
2. GMPEs that have been derived for discrete site classes. For example, `LinLee2008SInter` has been derived for two site categories (soil and rock) and uses a different set of coefficients for each of them. Hence there is no clear reference velocity. One option is to set `DEFINED_FOR_REFERENCE_VELOCITY` equal to the largest Vs value supported by the GMPE (in this case NEHRP site class B according to the publication), but then this would not be consistent with (3).
3. GMPEs with built-in site amplification models. These GMPEs compute ground motion for a specific reference rock condition, then amplify/deamplify the ground motion on soil with respect to that reference rock condition (e.g., `AbrahamsonEtAl2014` , which amplifies with respect to the reference condition of Vs30=1180 m/s). In this case it is more clear what the `DEFINED_FOR_REFERENCE_VELOCITY` value is (1180 m/s).

Open to other comments/thoughts on this issue.

**Comment by rcgee** [comment]
Another case:

4. GMPEs that have built-in site amplification models but do not explicitly state the reference velocity used (e.g. Kanno et al., 2006). However Figure 6 in the publication indicates the range of Vs30 used to develop the model. In this case the  DEFINED_FOR_REFERENCE_VELOCITY could be the largest Vs30 value included in the dateset used to derived GMPE.

**Comment by mmpagani** [comment]
I would be in favour of just excluding them since there is too much speculation behind and most of these GMMs will be soon superseded.
