### ISSUE TITLE
AssertionError not informative

### ISSUE THREAD

**Issue by rcgee** [gem/oq-engine#7137]
I ran the new TEM model (oq1 calc 42418) which gave the error message below:

[error.txt](https://github.com/gem/oq-engine/files/7077273/error.txt)

The solution was simple - I just needed to decrease the `complex_fault_mesh_spacing` and `area_source_discretization` both from 10km to 5km, but I only new this from guessing correctly, not because of the error message.

Wondering if this is something that should be improved before the Engine 3.12 release

**Comment by micheles** [comment]
Actually this happened to Marco too. I will think of something.
