### ISSUE TITLE
`fpeak` and `f0` are the same thing so can they be unified?

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#7337]
Two new site parameters have appeared in recent GMPEs, namely the `fpeak` term in `HassaniAtkinson2020` (https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/hassani_atkinson_2020.py#L244) and `f0` in `ManeaEtAl2021`  (https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/manea_2021.py#L143). Neither of these terms is adequately documented in the source code, but Hassani & Atkinson (2020) describe fpeak as the "peak frequency of the horizontal‐to‐vertical spectral ratio", while Manea et al. refer to it as the "fundamental frequency of resonance" that is "extracted from the horizontal-to-vertical ratio (e.g. Nakamura, 1989) on ambient vibration". To my knowledge, these are referring to the same site attribute (albeit they may _potentially_ have been derived differently). 

I would therefore suggest unifying these into one parameter, which I propose keeping as `fpeak`, defined as "The peak [or fundamental] frequency (in Hz) of the horizontal-to-vertical spectral ratio".

**Comment by mmpagani** [comment]
Graeme, thanks, it seems to see that in both cases they are using the fundamental frequency of the site, inferred using H/V. Given this, I would have a preference for using `f0`, but as long as it is clear, also the other one works.

**Comment by ElenaManea** [comment]
The methodologies behind the two site parameters (fpeak term in HassaniAtkinson2020 and f0 in ManeaEtAl2021) are different as they are retrieved by performing the horizontal‐to‐vertical (H/V) spectral ratio using pseudo-spectral acceleration (PSA) on ground-motion (entire earthquake record, HassaniAtkinson2020) and Fourier Amplitude Spectrum (FAS) on ambient vibration (ManeaEtAl2021). 
While f0 term is a robust proxy for characterizing the local site response and is correlated with bedrock depth(e.g. Bard, 1998; SESAME(2005); Puglia et al., 2021), the fpeak can be different depending on the seismic input (e.g. earthquake magnitude, depth), path (distance from the source, directivity effects) and of course local site response. 
As no explanation of these terms are present in the OQ documentation, I suggest that the standard site evaluation methodology should be applied:
F0 – fundamental frequency of resonance extracted from H/V FAS ambient vibration (SESAME,2005)
Fpeak – predominant frequency extracted using the entire earthquake, that can differ from the predominant frequency extracted from applying H/V FAS on coda waves(should also be considered as a site parameter).
Please, @vpoggi, @mascandola (or others) send your feedback.

Thanks,
Elena

**Comment by ElenaManea** [comment]
@micheles, could you add the reference of the HassaniAtkinson2020 gmpe in the code(https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/hassani_atkinson_2020.py#L244)?  I coudn't find the paper of Hassani Atkinson (2020) but this one: Hassani, B., & Atkinson, G. M. (2021). Equivalent Point‐Source Ground‐Motion Model for Subduction Earthquakes in Japan. Bulletin of the Seismological Society of America, 111(2), 951-974. Also, if my reference is correct, maybe the gsim should also be renamed as HassaniAtkinson2021.

**Comment by mmpagani** [comment]
Elena, it's impractical to keep one parameter for every method used to infer it, Graeme is right in this. In your 2021 paper you define in several parts as f0 as *the fundamental frequency of resonance (f0)*. Hassani and Atkinson (2016; https://doi.org/10.1785/0120150259) explains that "The new proxy is the site fundamental frequency (fpeak), measured from the horizontal‐to‐vertical (H/V) spectral ratios of recorded ground motion (or ambient noise)". So their definition of the fpeak encompasses both cases. 
Please consider also that in most of the analyses the user will not have for the site an f0 (or fpeak) computed from the H/V. If you think that the model can be used only when this parameter is available (and measured with a given methodology though relatively expedite) I think that its applicability will be quite limited.

**Comment by ElenaManea** [comment]
hi Marco,
Unfortunatelly, it is not about the method but on what we apply it and what do we extract from that. Please, check the H/V calculation section on HA16, where they say: "In this study, we use the response spectra to calculate the H/V spectral ratios" and it means that they use only ground motion. Reading their paper, I saw that they remove stations located on the sedimentary structures and in this case fpeak can be approximated as f0. Unfortunately, this approach is not valid anymore for complex sedimentary basins.
Yes, the applicability is quite limited for some models, but a lot of papers were published lately on deriving relationships between f0 with different parameters, on testing which site parameters perform better, and this shows that the community is getting ready to implement it and use it for hazard. 
To overcome this limitation, in our gmpe we implemented a reference f0 to make it possible to use even without setting this parameter.
It's great that you are thinking to use f0 instead of fpeak, considering SESAME guidelines, and this eliminates any possible confusion.

**Comment by g-weatherill** [comment]
Thanks @mmpagani  and @ElenaManea for the feedback on this, and for clarifying the specific differences between f0 and fpeak. Though I understand that there are some significant differences that can emerge between fpeak and f0, and certainly some limitations in certain conditions, they are both aiming at characterising the same property of the site albeit in very different (and not necessarily compatible) ways and on different types of seismic data. I would still be in favour of adopting only one term to represent the property. We could draw analogy with Vs30 here in the sense that it can be derived for a site in several different ways, each of which may give different results or be less or more accurate depending on the specifics of the site. Nevertheless we use Vs30 as a single term across ground motion models and it is left of the modeller to determine whether the differences in definitions may or may not make the GMPE suitable for application in their case. I would argue the same applies here, in the sense that it is up to the seismic hazard modeller to determine whether the definition of f0 (or fpeak) within the model makes it appropriate for the application context. 

I would also add that on a practical level retaining both f0 and fpeak would require that both terms are defined in the site model inputs if one wished to adopt both the Manea et al. (2021) and Hassani & Atkinson (2021) models in a ground motion logic tree. This would require that both f0 and fpeak would need to be specified in the input file, and I would expect that in the vast majority of cases the same values will be input for both regardless of the differences in the definitions. This can create a nuisance for the user and requires holding both values in the context object. 

It seems that the prevailing view is that f0 is appropriate, so it makes sense then to use that term in place of fpeak if there is an already established recommendation on terminology. 

Regarding applicability of ground motion models with f0 or fpeak, I understand the concern though it seems we are now finally seeing some sorts of H/V terms appear in them regardless. I think the applicability is something that will need to be assessed once users start adopting them in practice. For site-specific or urban scale applications I can see it being feasible to define all the necessary inputs. For regional scale models that question is still open and this term will almost certainly have to be inferred from proxies.

**Comment by micheles** [comment]
We have finally a user for the Manea GMPE: https://groups.google.com/g/openquake-users/c/zFQXf5Otl7w/m/JU5XYo7wAAAJ
Of course, it does not work because we have `fpeak` in the parameters and `f0` in the GMPE. I will just use `f0` everywhere.

**Comment by ElenaManea** [comment]
that's great Michele! thank you so much! I didn't check lately if the GMPE is running successfully using the latest version of the oq-engine. I did some trellis plots using the GMPE on an earlier engine and even computed hazard, and everything was fine. I will also update my machine and see if I encounter any issues and let you know.

**Comment by micheles** [comment]
The GMPE works, but it does not mean that the engine can use it. In particular, if the site model parameter is "f0" and it is not recognized as a valid parameter (since the engine uses the name "peak") any engine calculation will fail. So it is NOT enough to test the GMPE at the Python level, you need to try to run a full engine calculation with a job.ini and a site_model.csv file.
