### ISSUE TITLE
relax the firm 10k branch limit for single-site jobs 

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#7346]
As part of the METIS project, we are investigating new ways to propagate uncertainty. As we test different methods, we compare the results we get to those computed using the methods currently available in OpenQuake. We are building up to using source models with 10s of thousands of branches (maybe more), and are currently being limited by the firm 10k-branch maximum imposed by the OQ Engine. We are hoping that we can relax this limit for single-site jobs in order to better understand the results of our tests. 

A primary motivation for this part of METIS is to find approaches to evaluating the full epistemic uncertainty for a source model, without being hindered by computational factors. The input model we are currently testing has ~23k branches (divided between two sources). Optimally, we would compare the results of our approach to the hazard computed using full path enumeration, but instead must use only 10k logic tree samples. 

To better understand how the sampling was impacting our comparisons, we tested how the hazard curves computed using 10k branches change given three different random seeds. The results are in the image below, and show that the mean varies by up to ~3.5%, and the difference is even larger for some percentiles. It's true that the absolute (and even relative) difference is pretty small, but it's on the same order as the differences we're seeing when we compare our approaches to the results from the OQ Engine. Our assessments would be much clearer if we could compare to true full path enumeration.

![compare_means_3rs](https://user-images.githubusercontent.com/13698182/140519533-f4775f1d-2f2a-4262-99e1-cfe506eff72d.png)

**Comment by micheles** [comment]
Kendra, where is the limit to 10k samples? To my knowledge there is only a warning that you can safely ignore and run full enumeration anyway. The proof is that we can run the Canada model which has 13,000+ realizations.

**Comment by kejohnso** [comment]
Ciao Michele, I see now there is a second part to the error message: instead of using sampling I can set hazard_curves=false. So, this would only be an issue if I wanted to look at each realization (but I can understand the argument against exporting all the realizations).

**Comment by micheles** [comment]
Even it that case you can raise `max_potential_paths` and do the calculation anyway.
