### ISSUE TITLE
Losses in scenario_damage when using discrete_damage_distribution are incorrect

### ISSUE THREAD

**Issue by catarinaqmcosta** [gem/oq-engine#7380]
When we use the parameter `discrete_damage_distribution = true` in the scenario_damage calculator, the losses are being computed using the damage state distribution instead of using the sampled number of buildings in each damage state. In the example attached, we get non-zero loss values even when the number of buildings in the 4 DSs=0.
[scenario_damage.zip](https://github.com/gem/oq-engine/files/7555582/scenario_damage.zip)

**Comment by micheles** [comment]
@catarinaqmcosta, damage is a risk concept. Setting  `discrete_damage_distribution` in the hazard file is useless, since it is going to be ignored, the hazard only computes GMFs, not damages. Did you try to set it in the risk file? Does the problem disappear?

**Comment by catarinaqmcosta** [comment]
Yes, if we set it in the risk file the behaviour is the same - we get non zero losses even if the sampled number of buildings = 0 for the 4 DSs
