### ISSUE TITLE
`noDamageLimit` parameter is not working for continuous fragility functions

### ISSUE THREAD

**Issue by catarinaqmcosta** [gem/oq-engine#7381]
The parameter `noDamageLimit` in continuous fragility functions is not affecting the losses. In the example attached, we have many events with gm values<0.05, and still have losses in these events.
For discrete functions however, the parameter seems to be working properly.
[files_noDamageLimit.zip](https://github.com/gem/oq-engine/files/7555750/files_noDamageLimit.zip)

**Comment by micheles** [comment]
The issue is that the fragility functions contain noDamageLimit == minIML:
```xml
   <imls imt="PGA" noDamageLimit="0.05" minIML="0.05" maxIML="15"/>
```
This is a corner case not covered by any test, since in the tests that I have `noDamageLimit < minIML`. Perhaps for continuous fragility functions setting `noDamageLimit` should be an error since there is `minIML` instead?
