### ISSUE TITLE
HMTKBaseMap function can not be found

### ISSUE THREAD

**Issue by Siglab-code** [gem/oq-engine#7490]
Thanks for the great work first of all. 

Recently I tried to run 'Catelogue_Basics' notebook tutorial. However, 'from openquake.plt.mapping import HMTKBaseMap' does not work properly. This is the error message:  ModuleNotFoundError: No module named 'openquake.plt' 

Thanks for your help in advance.

**Comment by micheles** [comment]
basemap has been dismissed since it is an unmaintained third party library. Where did you find that notebook? We are trying to remove all obsolete notebooks but is hard to find all copies of them living around in the internet.

**Comment by Siglab-code** [comment]
Sorry for the late response. I found the notebooks in this link: https://www.training.openquake.org/eq-scenarios

**Comment by kejohnso** [comment]
Hi,

The 'Catalogue_Basics' notebook is part of the training package prepared
for the TREQ project, available here
<https://866d8384-6693-4663-8245-8284f7dd39ca.filesusr.com/archives/6d2e8f_ea8e444eb1424814bc868e170b823b76.zip?dn=TREQ-PSHA-ExampleMaterial-VirtualBox.zip>
.

The notebooks in the training materials have some additional dependencies
beyond the OQ Engine. The module openquake.plt is part of the Model
Building Toolkit (oq-mbtk)
<https://github.com/GEMScienceTools/oq-mbtk/tree/master/openquake>, and
thus to use the notebook on your local machine, you must also install the
oq-mbtk. This version of HMTKBaseMap also uses GMT.

In case you are unable to install these dependencies, we've also made
available a Virtual Image that works in Oracle VirtualBox. Please take a
look at the example instructions document provided with the training .zip
file.

Hope this helps,
Kendra

**Comment by Siglab-code** [comment]
Thank you very much for your help.
