### ISSUE TITLE
pointsource_distance behaving differently for incremental MFD vs truncated MFD 

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#7498]
I have two sources that are exactly the same, except that their MFDs have been defined in two different ways. One is a `TruncatedGRMFD`, and the other is an `EvenlyDiscretizedMFD`, defined using incremental rates in the source file. The occurrence rates acquired using the method `.get_annual_occurrence_rates() ` are almost identical:
![Screenshot 2022-01-19 at 12 26 03](https://user-images.githubusercontent.com/13698182/150121088-69695e48-42c3-4c7b-a08f-c35a08124c7e.png)

As expected, the sources produce the same hazard curve when run in an OQ job:
![Screenshot 2022-01-19 at 12 26 38](https://user-images.githubusercontent.com/13698182/150121158-4b005058-ca9f-4708-b3c8-0043acb20662.png)

However, if pointsource_distance is set (here, 50 km), I get very different hazard curves for low POEs:
![Screenshot 2022-01-19 at 12 27 02](https://user-images.githubusercontent.com/13698182/150121200-2414a578-7627-46bc-bef7-eafec4228806.png)

The hazard curve that uses the `TruncatedGRMFD` does not change, but the one from the `EvenlyDiscretizedMFD` does, and hazard increases a lot for the low POEs. 

This occurs for some source-site combinations but not for others.

The example jobs are attached.

[job_INC.zip](https://github.com/gem/oq-engine/files/7896691/job_INC.zip)
[job_TGR.zip](https://github.com/gem/oq-engine/files/7896689/job_TGR.zip)

**Comment by micheles** [comment]
Kudos @kejohnso for the clear analysis. I have everything I need to investigate further.
