### ISSUE TITLE
Ipython is not executing in OQ virtual environment

### ISSUE THREAD

**Issue by rameshpudi** [gem/oq-engine#7560]
Dear all,
I have successfully installed OQ but Ipython is not executing. It was showing below error. Kindly suggest possible issue.

(openquake) C:\Users\ramesh.pudi\openquake\Scripts>ipython
Fatal error in launcher: Unable to create process using '"c:\users\ramesh.pudi\openquake\scripts\python.exe"  "C:\Users\ramesh.pudi\openquake\Scripts\ipython.exe" ': Access is denied.

Thanks,
Ramesh

**Comment by micheles** [comment]
You should use the mailing list for this kind of questions.
