### ISSUE TITLE
Add an 'all' option for the 'num_rlzs_disagg'

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#7567]
For some applications, it can be useful getting all the realisations admitted by a LT. Currently, this can be achieved by using full path enumeration and setting 'num_rlzs_disagg' to the number of realisations admitted. This must be known a priori. By adding 'all' we let the engine define this number.

**Comment by micheles** [comment]
Since `num_rlzs_disagg` is an integer I would use `num_rlzs_disagg=0` to mean all realizations, similarly to what we do with the parameter `number_of_logic_tree_samples`.
