### ISSUE TITLE
Could magnitude-dependent `pointsource_distance` be reinstated?

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-engine#7614]
Between versions 3.10 and 3.11 of the engine the magnitude-dependent `pointsource_distance` option was removed (https://github.com/gem/oq-engine/pull/7106). It is not clear why this feature was not seen as worth keeping, as it is a particularly intuitive and smart way of applying point-source distances; collapsing the point sources for smaller events at closer distances while keeping the full distribution of rupture orientations and depths for the largest earthquakes at longer distances.  

This is unfortunate, as recent work that I had done in implementing seismic hazard models for France and Germany into OpenQuake had benefited from this feature, to the extent that this had even been documented in a report compiled for the Sigma 2 project. I am enclosing the relevant pages of the report in which the justification of the magnitude-dependent pointsource_distance is given, along with the calibrated set of magnitude-dependent distances and the comparison output seismic hazard curves. 

[France_OQ_Implementation_SIGMA2_Report_PSdist_expl.pdf](https://github.com/gem/oq-engine/files/8160808/France_OQ_Implementation_SIGMA2_Report_PSdist_expl.pdf)

For site-specific calculations using the PSHA model of Drouet et al. (2020), I was getting an approximately 75 % reduction in calculation time using the magnitude-dependent pointsource_distance, which is not a trivial reduction. The reductions were also seen for the regional scale calculations too, though as I hadn't been able to run the larger scale calculations  <i>at all</i> without the magnitude-dependent point-source distances I don't have a clearer benchmark for the reduction.

Of course, users have the option of reverting back to the previous OQ < 3.11 versions if they want to benefit from this feature. In doing so, however, they would of course lose the benefit of all of the developments in improving the efficiency of the GMPE library seen in the more recent versions. Ideally, it would be nice to be able to benefit from both!

**Comment by micheles** [comment]
Exactly.
