### ISSUE TITLE
Flexible multi-tag aggregation in risk calculations

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#7663]
Currently, when a multi-tag aggregation is requested, the engine generates `agg_keys` that represent the Cartesian product of the lists of tag values for each of the tags. A final, additional `agg_key` represents the complete portfolio.

Eg., `aggregate_by = canton, commune, occupancy`, where the exposure contains 26 cantons, 2,142 communes, and 3 occupancy classes will generate a `risk_by_event` table containing (26 × 2,142 × 3 + 1 =) 167,077 `agg_keys`. Instead, what users often want is not the full combination of all tag values, but very specific subsets. Eg. the user might be interested in 
1. Aggregation for the combination of all cantons and occupancy classes
2. Aggregation at the commune level

At present, to avoid the above situation, the user needs to run two separate risk calculations, one with `aggregate_by = canton, occupancy` and the second with `aggregate_by = commune`. This involves unnecessary duplication of risk calculations, whereas the issue could in principle be better handled at the post-risk stage after a single risk calculation. 

The syntax for `aggregate_by` could be modified to accept a list of tuples or a list of lists that specify the various single- and multi-tag aggregations that the user is actually interested in.
Eg. list of tuples —
`aggregate_by = [(canton, occupancy), (commune)]`
or list of lists —
`aggregate_by = [[canton, occupancy], [commune]]`

In this case, the engine would store (26 × 3 + 2,142 + 1 =) 2,221 `agg_keys`.

Proposal by @thpap

**Comment by micheles** [comment]
We need the syntax to be backward-compatible; something like the following
```
aggregate_by = canton, occupancy, commune  # same meaning as it is now
aggregate_by = canton, occupancy; commune  # aggregate first by canton, occupancy and then by commune only
```

**Comment by thpap** [comment]
> Is it enough to implement only the single-tag case `aggregate_by = canton; occupancy; commune`? That would be much easier.

Hi Michele, we talked a bit about this with Laurentiu. Basically, what we need for our risk model is essentially the multiple single-tag case. I think that having the multi-tag option too would be useful (I assume for other users too), but we can do without it if it is complex to implement. Many thanks and cheers.
