### ISSUE TITLE
Proposal - Can we have an estimating function to get W (km) (the width of the fault rupture plane) for CampbellBozorgnia2014 model?

### ISSUE THREAD

**Issue by SnowNooDLe** [gem/oq-engine#7697]
Hey team,

Currently, the width is a required parameter as per the paper (relevant parts referenced below) if the width is not specified, there is an estimation we can use.

So instead of enforcing users to input width, which is done by having the following variable
```python
REQUIRES_RUPTURE_PARAMETERS = {
        'mag', 'rake', 'dip', 'ztor', 'width', 'hypo_depth'}
```
We can remove the `width` and if the `width` is not provided, we use the equation above to estimate the `width`?

If this implementation is aligned to OpenQuake, we can implement this ourselves.

## width estimation from the paper
We recently found the following estimating function to get W (km) for the CampbellBozorgnia2014 model. from the following [paper](https://journals.sagepub.com/doi/pdf/10.1193/062913EQS175M)
![image](https://user-images.githubusercontent.com/7849113/161640906-b470b93b-b0f1-414a-a4eb-ef11fea9abb8.png)

**Comment by micheles** [comment]
We recently introduced the concept of *computed rupture parameter*: https://github.com/gem/oq-engine/pull/7554
That should give you some idea.
