### ISSUE TITLE
Configurable Mag-Area Scaling Relation

### ISSUE THREAD

**Issue by thingbaijam** [gem/oq-engine#7713]
Would be it  possible to have a mag-area scaling relation with variable coefficient(s)? For instance,  given a relation: log10(A) = bM-c, user supplies values of b and c in the source xml file.  Advantages of the configurable mag-area relation would be: 
-  Users can apply new scaling coefficients without need to write new class (or methods), 
-  Users can easily incorporate epistemic variability of scaling relations.

**Comment by micheles** [comment]
We are going to fix this properly, we just need to extend MSR classes to accept parameters and to change the XML readers/writers to manage the parameters properly.
