### ISSUE TITLE
Proposal - Can you permit to modify admin password / account / email with env variables for docker image

### ISSUE THREAD

**Issue by Mareak** [gem/oq-engine#7756]
Hello, at Descartes we use the openquake/engine docker image.

It could be very useful for us to deploy the container on the fly with a specific admin username/password/email.

`-e ADMIN_LOGIN=${LOGIN} -e ADMIN_PASSWORD=${PWD} -e ADMIN_EMAIL=${EMAIL}`

Thanks

**Comment by vot4anto** [comment]
Hi, 
 To better understand  about your proposal,  please can you specify how do you use the openquake/engine docker image? 

Thanks

**Comment by vot4anto** [comment]
We introduce the variables: 
`OQ_ADMIN_LOGIN, OQ_ADMIN_PASSWORD, OQ_ADMIN_EMAIL`

Those are available on nightly docker image and also on future ltr and latest image
