### ISSUE TITLE
Proposal for simple performance improvement of Kuehn et al. (2020) model

### ISSUE THREAD

**Issue by SnowNooDLe** [gem/oq-engine#7785]
# Proposal for simple performance improvement of Kuehn et al. (2020) model

Current implementation:
1. Splits input array into a small sub-arrays with the same magnitude
2. Loop over the sub-arrays to compute the results

If the input array contains many unique magnitudes, performance is reduced (due to the for loop).

Based on our understanding, the reason for splitting into small sub-arrays is to allow computation of the `sigma_mu_adjust` ([code](https://github.com/gem/oq-engine/blob/1123aab493891b64c34f25333951e0452e12da87/openquake/hazardlib/gsim/kuehn_2020.py#L712)).

## Proposal

Our proposal would be to keep the existing functionality if `sigma_mu_epsilon` is specified on model [instanstiation](https://github.com/gem/oq-engine/blob/20cf71da4d83d1ecd8894bc3e29a50eab35edf0a/openquake/hazardlib/gsim/kuehn_2020.py#L633), but otherwise don't split the array (and therefore compute all the results via vectorisation). This will keep existing behaviour in place but results in a nice performance improvement.

### Proposed workflow
The splitting of the input array is triggered in the context ([code](https://github.com/gem/oq-engine/blob/a02dcb038d84abc3b91a89cd39c581579e6d7940/openquake/hazardlib/contexts.py#L838)) by the existence of the `gmpe_table` class variable of the Kuehn model ([code](https://github.com/gem/oq-engine/blob/1123aab493891b64c34f25333951e0452e12da87/openquake/hazardlib/gsim/kuehn_2020.py#L603)). Based on our understanding removing the `gmpe_table` class variable and instead only creating it on model instantiation if `sigma_mu_epsilon` is specified and shifting this [line](https://github.com/gem/oq-engine/blob/1123aab493891b64c34f25333951e0452e12da87/openquake/hazardlib/gsim/kuehn_2020.py#L691) into the `if self.sigma_mu_epsilon:` block, should be all that is needed to achieve the proposed behaviour.

**Comment by micheles** [comment]
That should work, yes. Did you measure how big the performance improvement is?

**Comment by SnowNooDLe** [comment]
This test is based on the randomized 1000 magnitudes. (`np.random.uniform(5,10, 1000)`)

![Screenshot from 2022-05-05 16-48-32](https://user-images.githubusercontent.com/7849113/166865011-50fda007-48cb-474d-8ecc-90d4df83895f.png)

**Comment by micheles** [comment]
Then please go on and submit a pull request.
