### ISSUE TITLE
Add command to extract the computation time of completed analyses

### ISSUE THREAD

**Issue by nicolepaul** [gem/oq-engine#7805]
It would be useful to have a programmatic way to extract the computation time of completed analyses from the database.

An example `oq` command could look like:

`oq show calctime 1234`

**Comment by micheles** [comment]
In can be done from the command line already:
```
$ oq db "SELECT (julianday(stop_time) - julianday(start_time))*24 AS hours FROM job WHERE id=17637"
```

**Comment by raoanirudh** [comment]
A lot of other useful information can be extracted from the logs and performance reports also, by a bit of (tedious) grepping. For instance, when we were tracking the performance of the European risk calculations last year:

![Europe_Calcs](https://user-images.githubusercontent.com/1707414/167830656-2ca627df-339c-4400-8668-d42ecd924665.png)

**Comment by nicolepaul** [comment]
@raoanirudh Here is some starter Python code to extract the computation time across many analyses. Note that I am assuming the logs have been exported to a certain path, such as by using the `--log-file` option.

```
import re

# Get last line of log
last_line, line = None, None
with open(log_path, 'r') as f:
    for line in f:
        pass
    last_line = line

# Parse regular expressions
timing = re.search(r"in (.*?) seconds", last_line).group(1)
calc_id = re.search(r"calc_(.*?).hdf5", last_line).group(1)

```

**Comment by micheles** [comment]
Closing since it is enough to interrogate the db:
```python
In [1]: from openquake.commonlib.logs import dbcmd
In [3]: dbcmd("SELECT (julianday(stop_time) - julianday(start_time))*24 AS hours FROM job WHERE id=160")
Out[3]: [<Row(hours=0.9993455596268177)>]
In [4]: dbcmd("SELECT (julianday(stop_time) - julianday(start_time))*24 AS hours FROM job WHERE id=160")[0].hours
Out[4]: 0.9993455596268177
```
