### ISSUE TITLE
Serve openquake on a different context path

### ISSUE THREAD

**Issue by adnanesaghir** [gem/oq-engine#7841]
Hi, is there a way to serve openquake on a different context path?
For example for a custom path `mypath` we'd like to have:
* `http://localhost:8800/mypath/accounts/login/` instead of `http://localhost:8800/accounts/login/`
* `http://localhost:8800/mypath/engine` instead of `http://localhost:8800/engine`
* `http://localhost:8800/mypath/v1/engine_version` instead of `http://localhost:8800/v1/engine_version`

**Comment by micheles** [comment]
We accept pull requests.

**Comment by adnanesaghir** [comment]
Sorry i'm not a Python developer :)
I tried with `FORCE_SCRIPT_NAME = "/openquake"` in `settings.py` but it doesn't seem to work
I would like to implement the feature in one place without touching all the url paths in `urls.py`
Something like what I'm used to do in `Node.js` , please see this nodejs sample app
- app routes (urls) definition: https://github.com/adnanesaghir/expressjs-app/blob/master/routes.js
- setting secondary custom app path from an environment variable in one line without touching default routes: https://github.com/adnanesaghir/expressjs-app/blob/49f73bfcaaf663d065c217bb5c659f9d736ef50b/app.js#L8

**Comment by micheles** [comment]
This is now implemented in current master as documented here: https://github.com/gem/oq-engine/blob/master/docker/README.md (see the section on WEBUI_PATHPREFIX).
