### ISSUE TITLE
disaggregation by lon-lat-trt yields high hazard contributions from outside the integration distance

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#7842]
In the disaggregation by LLT, the contribution is being attributed mostly to a spatial bin without any sources, and which is outside the integration distance. It could be related to multifaults.

**Comment by kejohnso** [comment]
@micheles @mmpagani 

The problem is in identifying the closest point on the rupture surface to the site for multifaults. The function `get_closest_points` finds which surface is closest to the site based on the `rrup` distance, and then computes the closest point on that surface. The bug is that if the last surface in the list of surfaces is not the closest one, then no calculation is done, and the `lons` and `lats` arrays created by `np.empty_like()` keep the distance `rrup` instead. I have proposed a solution [here](https://github.com/gem/oq-engine/blob/fix_multifault_disagg/openquake/hazardlib/geo/surface/multi.py#L189) and tested it in a few small cases, but I'm not sure if it's the most elegant way and should probably be tested further.

**Comment by micheles** [comment]
Thanks for the analysis, @kejohnso . I will leave the ball to @mmpagani

**Comment by kejohnso** [comment]
@micheles @mmpagani 

This issue is partially solved by what's written above, but the problem is more complex. Here is what I have found:

- in the datastore (`dstore['rup']`), some ruptures incorrectly have `clat` or `clon` values of 0.0, despite that the test model is centered on ~70.7 W 19.5 N

<img width="674" alt="Screenshot 2022-08-16 at 09 10 58" src="https://user-images.githubusercontent.com/13698182/184819252-939c05b2-f54f-4221-9232-3c227690b32e.png">

- the problematic ruptures do not seem to correspond to a specific source or source typology. For example, if the problematic source is isolated from a larger source model and run by itself, everything is correct. 
- for all sources, what is returned by [get_ctxs](https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/contexts.py#L905) seems to be correct, so I don't think it's related to computation of `clat` and `clon`. the error occurs sometime between the `cmaker` and  where the [`rup_data` dictionary is written to the dstore](https://github.com/gem/oq-engine/blob/master/openquake/calculators/classical.py#L292). I tracked this as far as where [Starmap is used](https://github.com/gem/oq-engine/blob/master/openquake/calculators/classical.py#L439) but don't understand how to test what happens next... 

I will send the test job files and some more analysis separately.

**Comment by mmpagani** [comment]
@micheles the error is still there. Using the test case provided by @kejohnso, in `agg_dicts` the object `dic['source_data']` already contains clon = 0 (and clat has values that should be assigned to clon). Seems like a problem with indexes ... perhaps in the tiling mechanism.
