### ISSUE TITLE
classical_risk is ignoring risk_investigation_time

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#7927]
The loss curves outputs should provide the probability of exceedance of the corresponding loss values within the `risk_investigation_time`. The average loss, computed as the area under the loss exceedance curve is thus also dependent on the `risk_investigation_time`. See Equation 5 in the attached specs sheet: [Specs - Classical PSHA-Based Risk Calculator.pdf](https://github.com/gem/oq-engine/files/8955909/Specs.-.Classical.PSHA-Based.Risk.Calculator.pdf).

Bug reported on the forum: https://groups.google.com/g/openquake-users/c/IDAOfgv9kkE/m/rHvcKMPqAwAJ

**Comment by micheles** [comment]
We need to run `~/oq-risk-tests/test/classical_risk/inputs`
