### ISSUE TITLE
seismic intensity measures include the average spectrum acceleration, Saavg

### ISSUE THREAD

**Issue by YexiangYan** [gem/oq-engine#7947]
Hello, thank you for providing such an excellent platform. Can seismic intensity measures include the average spectrum acceleration, Saavg? If so, what should I do? If not, can it be calculated indirectly? Thanks.

**Comment by micheles** [comment]
This is not the right place. Questions must be asked on the mailing list: https://groups.google.com/u/1/g/openquake-users.
The answer is yes, anyway, the name of the IMT in the engine is `AvgSA`.

**Comment by YexiangYan** [comment]
Thanks. Do you have any examples or tutorials?
















At 2022-07-04 14:06:16, "Michele Simionato" ***@***.***> wrote:

This is not the right place. Questions must be asked on the mailing list: https://groups.google.com/u/1/g/openquake-users.
The answer is yes, anyway, the name of the IMT in the engine is AvgSA.
