### ISSUE TITLE
Implementing total loss curves

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#7967]
This is part of https://github.com/gem/oq-engine/issues/7886, but kept separate since it is also useful per se (for instance, for the global risk model). They could be enabled in the job.ini with a syntax like
```
total_losses = structural+nonstructural
total_losses = structural+nonstructural+contents
```
We must pay attention to the following:

- [x] the aggcurves and aggrisk exporters compute loss ratios and they must be changed to divide by the total loss
- [x] the sanity check in EventBasedRiskCalculator.post_execute must be fixed 
- [x] we must be able to compute average total losses to (avg_losses-XXXX)
- [x] total losses must work together with the taxonomy mapping feature
- [x] total losses must work together with insurance losses (left for another ticket)

**Comment by micheles** [comment]
No, it is different. Aggregation by tag works across loss types transparently. Here we need to define a kind of secondary loss, the total loss. I have already spent several hours on that, changing risk_by_event is *really* hard, so I am trying plan B, (and then C, D, ... etc).

**Comment by micheles** [comment]
After 20+ pull requests in #7886, now it is possible to implement total losses without changing risk_by_event.

**Comment by micheles** [comment]
Reopening since total_losses + taxonomy mapping is hard and not solved yet.

**Comment by nicolepaul** [comment]
For the next GRM release, we need both `total_losses` and `building_losses`, where:

    total_losses = structural + nonstructural + contents
    building_losses = structural + nonstructural

**Comment by micheles** [comment]
Let's open a different ticket for when we will need this feature.
