### ISSUE TITLE
Error -  uncertainties of Model Sources. Oq v3.15

### ISSUE THREAD

**Issue by Camillever** [gem/oq-engine#7972]
I have an error when running oq on oq engine v3.15 (on a Debian server) that doesn't happen on the Linux server of my coworker which has oq engine v3.13. It works on his computer. 

NB :
-  Run on the same inputs : no modification. That was checked.  
- My version of oq works on demos and an version simplified (with no uncertainties on the values of a and b of Gutenberg Richer of the 4 source models) of the current run (each type of source models are generated 100 times to simulated the uncertainties on the values of a and b (Gutenberg Richter)) .
- My coworker and I have the same version of python : 3.7. And the environment venv are correctly installed on our computer.

----------
**The error:**
 
![image](https://user-images.githubusercontent.com/33858952/178473825-efbfebba-643b-457f-a731-f65165841b06.png)
![image](https://user-images.githubusercontent.com/33858952/178475993-a043b31e-d94c-4973-a21b-875ec0bbb1e0.png)

------

_**Is it because of the latest version of oq ? (If it is, how can I download the version 3.13 via devel (the only method of installation that works for me) ? What is the command ?**_ 

Thank you for your time

Camille

**Comment by micheles** [comment]
You should use the mailing list for this kind of questions. When using the *devel* installation all versions are installed, just change the git branch to `engine-3.13`. Having said that, the error is related to having too many branches per branchset, so it should fail in engine 3.13 too (?)
