### ISSUE TITLE
sample_raster_at_points returns nan in some edge cells with values

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#8016]
The function [sample_raster_at_points](https://github.com/gem/oq-engine/blob/master/openquake/sep/utils.py#L13) returns 'nan' for some cells on the edge of a raster where other methods (e.g. QGIS Sample Raster Values) real values. 

![Screenshot 2022-08-17 at 10 22 34](https://user-images.githubusercontent.com/13698182/185070891-482c8be6-8841-4023-aea6-bd5158472f7d.png)

**Comment by micheles** [comment]
@kejohnso says it is not a problem, let's close it
