### ISSUE TITLE
Demos Bug

### ISSUE THREAD

**Issue by wukongtea** [gem/oq-engine#8025]
Os: WIN10
Oq: 3.14
When I try this demo: oq-engine/demos/hazard/EventBasedPSHA/job.py
The following error occurred:

X:\Conda\envs\oqe\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Both a converter and dtype were specified for column custom_site_id - only the converter will be used
  return func(*args, **kwargs)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_12080\2171980026.py in <module>
      8               site_model_file="site_model.csv",
      9               gsim_logic_tree_file="gmpe_logic_tree.xml")
---> 10 main(params)

~\AppData\Local\Temp\ipykernel_12080\290751073.py in main(params)
      5     print(inp.gsim_lt.get_rlzs_by_gsim_trt())
      6     acc = AccumDict(accum=[])
----> 7     ebrs = sample_ebruptures(inp.groups, inp.cmakerdict)
      8     ne = sum(ebr.n_occ for ebr in ebrs)
      9     print('There are %d ruptures and %d events' % (len(ebrs), ne))

D:\software\python\Conda\envs\geo\lib\site-packages\openquake\hazardlib\calc\stochastic.py in sample_ebruptures(src_groups, cmakerdict)
    313             samples = getattr(src, 'samples', 1)
    314             for rup, trt_smr, n_occ in src.sample_ruptures(
--> 315                     samples * cmaker.ses_per_logic_tree_path, cmaker.ses_seed):
    316                 ebr = EBRupture(rup, src.source_id, trt_smr, n_occ, e0=e0)
    317                 ebr.ordinal = ordinal

D:\software\python\Conda\envs\geo\lib\site-packages\openquake\hazardlib\source\base.py in sample_ruptures(self, eff_num_ses, ses_seed)
    117                 if hasattr(rup, 'occurrence_rate'):
    118                     # defined only for poissonian sources
--> 119                     rup.occurrence_rate *= self.smweight
    120                 seed += 1
    121                 yield rup, trt_smr, num_occ

AttributeError: 'AreaSource' object has no attribute 'smweight'

**Comment by wukongtea** [comment]
@micheles

**Comment by micheles** [comment]
We cannot reproduce this problem so we cannot help. Also, we do not support conda installations.
