### ISSUE TITLE
Downloading Previous Versions of OpenQuake-Engine from PyPI

### ISSUE THREAD

**Issue by stu-orchard** [gem/oq-engine#8026]
openquake-engine==3.10.0 downloaded from PyPI failed to install with the error shown in the snip below.
Running on Windows 10
Have tried installing with 32 bit and 64 bit Python, errors with both. 
Also fails with other versions prior to 3.14.0 but 3.14.0 installs without error.
Believe it is an issue with the Shapely library. 
Is anyone else experiencing this issue?

  C:\Users\so7\Desktop\RunOQ>py -m pip install openquake-engine==3.10.0
  Defaulting to user installation because normal site-packages is not writeable
  Collecting openquake-engine==3.10.0
    Using cached openquake.engine-3.10.0-py3-none-any.whl (31.7 MB)
  Collecting pyzmq<20.0
    Using cached pyzmq-19.0.2.tar.gz (1.2 MB)
    Preparing metadata (setup.py) ... done
  Collecting psutil<5.7,>=2.0
    Using cached psutil-5.6.7.tar.gz (448 kB)
    Preparing metadata (setup.py) ... done
  Collecting shapely<1.8,>=1.3
    Using cached Shapely-1.7.1.tar.gz (383 kB)
    Preparing metadata (setup.py) ... error
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [10 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\Users\so7\AppData\Local\Temp\pip-install-1wahpr2l\shapely_2bc6168e8ba743b1aeec8d68b1d7a202\setup.py", line 85, in <module>
            from shapely._buildcfg import geos_version_string, geos_version, \
          File "C:\Users\so7\AppData\Local\Temp\pip-install-1wahpr2l\shapely_2bc6168e8ba743b1aeec8d68b1d7a202\shapely\_buildcfg.py", line 205, in <module>
            lgeos = CDLL("geos_c.dll")
          File "C:\Program Files\Python310\lib\ctypes\__init__.py", line 374, in __init__
            self._handle = _dlopen(self._name, mode)
        FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
        [end of output]
  
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.

**Comment by micheles** [comment]
This kind of issues should be asked on the mailing list https://groups.google.com/u/1/g/openquake-users, not on github which is for bugs in the code. Having said that, when installing old versions of the engine one has to be careful to use old versions of the underlying libraries. The easier thing is to use the docker images, if possible.
