### ISSUE TITLE
BSSA14 fix for using basin models in oq-engine 3.14?

### ISSUE THREAD

**Issue by smithj382** [gem/oq-engine#8029]
I would like to know if the BSSA14 GMM in oq-engine version 3.14 can be back-patched to include the z1pt0 site parameter as a requirement? This additional code (https://github.com/gem/oq-engine/issues/7873) was merged into oq-engine in June and so missed the April release date of version 3.14

If I run the the script (available via gist: https://gist.github.com/smithj382/8b465d7f040d09835904cf1bf14f9bf9)  using version 3.14 I get an error, but if I update oq-engine to 3.15 (pip install git+https://github.com/gem/oq-engine.git), the error goes away. 

If there are no plans for an updated official release soon are you willing to patch the BSSA14 update into 3.14?

Thank you.

**Comment by micheles** [comment]
Actually we plan to release version 3.15 at the beginning of September.

**Comment by smithj382** [comment]
Understood. Thank you for your response.

**Comment by micheles** [comment]
Version 3.15 has been published today.
