### ISSUE TITLE
Event Based in-a-box

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#8112]
We have a mid-term goal to create a global stochastic event set. In order to build it, one useful feature to add to OQ Engine would be an option where the user defines a polygon A in the job.ini. The OQ Engine creates an SES (and possibly the corresponding GMFs) using all the ruptures included in A.

**Comment by micheles** [comment]
Can we say that the rupture is in the box if the hypocenter is in the polygon? If yes, then it is pretty easy and very efficient to implement.

**Comment by mmpagani** [comment]
PR https://github.com/gem/oq-engine/pull/9367 is an excellent step forward! Grazie Michele. The only other suggestion I have in case of an event-based analysis would be to add the possibility of specifying in the .ini file the path to a file (either a shapefile or a geojson) containing a polygon. This polygon represents the domain within which ruptures should be accepted if their centroid is inside.
