### ISSUE TITLE
Reinsurance checks

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#8124]
The user can do tons of mistakes in the input files. We need to make sure that the engine gives clear error messages in such situations.
Cases to consider:

**Checks in the policy file:**
- [x] policy present in the exposure but missing in the policy.csv file
- [x] `policy` column should have no duplicated values
- [x] Sum of fractions for prop treaties should be between >=0 and <=1
- [x] The `liability` and `deductible` columns should be float >= 0
- [x] The nonprop treaties should be 0 or 1
- [x] Any condition in the order of the treaties? Shall we write in the documentation how the information is processed?
- [x] Check what happens if there are spaces in the header (do they go in the field names?)

**Checks in the reinsurance file:**
- [x] treaties present in the reinsurance.xml but missing in the policy.csv file
- [x] `type` values are within `prop`, `wxlr` or `catxl`
- [x] The `deductible`, `limit` and `max_cession_event` columns should be float >= 0

**Checks in the configuration file:**
- [x] `aggregate_by` conditions:
    - [x] missing aggregate_by=policy
    - [x] multiple aggregate_by (i.e. aggregate_by=policy; taxonomy ok)
    - [x] multiple aggregate_by (i.e. aggregate_by=taxonomy; policy wrong)
    - [x] multiple aggregate_by (i.e. aggregate_by=policy, taxonomy wrong)
- [x] missing total_losses
- [x] multiple loss types in reinsurance_file must be an error

**Others**
- [x] scenario_risk starting from rupture or from GMFs

**Comment by CatalinaYepes** [comment]
Please check the updated list.
