### ISSUE TITLE
Include a link between `eid` and `rlz_id` in dstore 

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#8185]
Currently when reading gmfs from the datastore is possible to extract the ground motion data 
as a pandas DataFrame:
`dstore.read_df('gmf_data')`

However, it is hard to get the keys to associate the `eid` with a given realization.
The events information (`dstore.read_df('events')`) only provides integers (`rlz_id`) but not the associated GMPEs.

In the case of scenarios, this will be the corresponding GMPE, and for event-based, the combinations of GMPEs

**Comment by micheles** [comment]
Inside calculators/views.py there is the following code that should help:
```python
@view.add('gsim_for_event')
def view_gsim_for_event(token, dstore):
    """
    Display the GSIM used when computing the GMF for the given event:

    $ oq show gsim_for_event:123 -1
    [BooreAtkinson2008]
    """
    eid = int(token.split(':')[1])
    full_lt = dstore['full_lt']
    rup_id, rlz_id = dstore['events'][eid][['rup_id', 'rlz_id']]
    trt_smr = dstore['ruptures'][rup_id]['trt_smr']
    trti = trt_smr // len(full_lt.sm_rlzs)
    gsim = full_lt.get_realizations()[rlz_id].gsim_rlz.value[trti]
    return gsim
```
