### ISSUE TITLE
Providing push access to create new branch?

### ISSUE THREAD

**Issue by treviallen** [gem/oq-engine#8202]
Hi team,

I'm hoping to make some enhancements to the gsim library (new gsims and enhancements) - i'm trying to generate a new branch to make a push request, but I don't think that I have permissions.  

Grateful for any advice!
Trev

**Comment by micheles** [comment]
Hi Trevor, the right way to proceed is to fork the engine and then make the pull request from your fork to the master repo: in this way, you do not need any special permission.

**Comment by treviallen** [comment]
Ok – thanks Michele.  You might receive some more stupid questions over the next few days ☺
