### ISSUE TITLE
Missing page numbers in openquake manual

### ISSUE THREAD

**Issue by Shreyasvi91** [gem/oq-engine#8322]
Recently I was looking for something in the manual and observed that the page numbers have not been mentioned when citing in a paragraph. 
example:
https://docs.openquake.org/oq-engine/manual/latest/hazard.html#seismic-hazard-disaggregation. In the PDF version of the manual, the text `see page` is not followed by the page number.

**Comment by micheles** [comment]
I would just remove all page references. There is no concept of page number anymore since the main output now is HTML, not latex.
