### ISSUE TITLE
Computing mean disaggregation without running out of memory

### ISSUE THREAD

**Issue by Shreyasvi91** [gem/oq-engine#8326]
The hazard team is planning to perform disaggregation for National capital cities in all the mosaic models. The disaggregation results will be stored in the respective model repos. As of now, we are able to obtain disaggregation results for all the realizations which make the file sizes too large in some models. Also, this further makes it difficult to read the results directly from hdf5. 
It would be useful and faster if the mean disaggregation can be directly exported from hdf5 files. 
At the moment, we are calculating the mean using [get_mean_mde](https://github.com/GEMScienceTools/oq-mbtk/blob/update_disagg_mde_plotter/openquake/man/tools/csv_output.py#L78), which uses a CSV file.

**Comment by micheles** [comment]
We also need to avoid errors like
```python
ValueError: Estimated data transfer too big
579.27 GB > max_data_transfer=186.26 GB
```
The solution is to change the approach so that all relevant ruptures enter in a single task, then we can do the average on the workers and not on the master as it is now. The price to pay is the presence of slow tasks.
