### ISSUE TITLE
webui Unicode issue

### ISSUE THREAD

**Issue by UlBoy** [gem/oq-engine#8348]
Hi guys,
I'm trying to learn Openquake
I'm using Windows so I downloaded openquake via this link 'https://github.com/gem/oq-engine/blob/master/doc/installing/windows.md'

But I found some error when I trying to open the web ui through 'OpenQuake Engine(webui)' icon

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte

<img width="857" alt="image" src="https://user-images.githubusercontent.com/84957780/213382728-a19ce411-cc43-449b-888f-9a8611c4282c.png">

Can you guys help me?

**Comment by micheles** [comment]
Looks like you found this python bug when you have a host name containing non ascii characters:

https://github.com/python/cpython/issues/70415

The bug was solved in python 3.9 so you could use that Python (or change your hostname if you can do that).
