### ISSUE TITLE
How scenario-damage calculator calculates damage distribution?

### ISSUE THREAD

**Issue by Jiayue-LIN-CN** [gem/oq-engine#8365]
Hi dear Sir or Madam,

Currently, I met an issue about the scenario-damage calculator inside OQ.

I applied the same GM, same fragility curve for a single type of building at one site. And I calculate the damage distribution (i) by using OQ automatically and (ii) by using equations to calculate. It shows different damage distribution by comparing the results.
The one from OQ is: 0 (no damage), 0 (slight), 3 (moderate), 2 (extensive) and 13 (complete);
The one by equations using Matlab is: 1.68 (no damage), 1.85 (slight), 2.32 (moderate), 2.16 (extensive) and 10 (complete);
I tried for different cases and it shows the same conclusions. 

I am wondering if there is some uncertainty to calculate damage distribution and curious about how OQ run this scenario-damage process to calculate damage distribution. 

There is not enough information about it from OQ Manual, can I get some ideas from you about it?

Thanks in advance and have a nice day!

**Comment by micheles** [comment]
Sorry, but for this kind of question there is the mailing list: https://groups.google.com/u/1/g/openquake-users

GitHub is for reporting bug/submitting pull requests etc
