### ISSUE TITLE
shakemap2gmfs feature ignores user input site_model

### ISSUE THREAD

**Issue by alejocaldeGEM** [gem/oq-engine#8385]
Regarding the `shakemap2gmfs` command and `shakema2gmfs.py`, I noticed:

1. If the user specifies a site_model.csv file, the command **does not use the provided site model** to amplify the gmfs. The argument for considering site effects is set to `False `in the main function. But even if it could be changed by the user, the parameter is not send to the `to_gmfs()` function, which always operates with `oq.site_effects = False`. Therefore the site_model.csv is not used for gmfs amplification, only to build a `sitecol `instance. In other words, providing a site_model.csv or not yields the same results.

2. If the user manually sends `oq.siteffects = True` to the to_gmfs() function, the function looks into the `shakemap.npy` object and uses the Vs30 values found in `Shakemap['Vs30']` to amplify the intensities. It does not use the provided site_model.csv

I don’t know if this is the intended behavior you have planned for the command/function, but it can be misleading for the user to be able to provide a site_model.csv and run the calculation successfully. Furthermore, I have been unable to have the function use a provided vs30 site model or amplification functions to amplify the gmfs, where the potential for this feature is.

**Comment by micheles** [comment]
This is simply a case of not having specs, or having misunderstood the specs. It should be easy enough to change the code in such a way that the site model parameters are used.

**Comment by alejocaldeGEM** [comment]
Thank you Michele. That would be great. Enabling the user to amplify the shakemap intensities using a provided vs30 site model or using amplification functions would make this feature even more valuable for risk assessment. For example, being able to generate amplified gmfs from a shakemap, considering local conditions and for different IMTs, as owuld be the case for scenario risk assessment of a city
