### ISSUE TITLE
Lanzano et al. (2019) GMPE not working with vs30 > 1500

### ISSUE THREAD

**Issue by CB-quakemodel** [gem/oq-engine#8463]
The Lanzano et al. (2019) GMPE does not appear to work if vs30 => 1500 m/s. Manually changing the sites in flatfile to vs30 = 1499 m/s appears to be a temporary workaround/indicative of it being the cause. 

The issue occurs when generating expected values from the gmpe for residual analysis within the SMT:

![image](https://user-images.githubusercontent.com/119606956/221236556-52df98c3-36fb-4977-89da-7dd9c6b641c5.png)

**Comment by micheles** [comment]
"Does not work" is not clear: do you get an error? or so you silently get wrong numbers? Please send a script exhibiting the problem and we will look at it.

**Comment by CB-quakemodel** [comment]
Dear Michele,

 

Please find attached a notebook and files required to generate the error. The code and files run if placed in the same directory. The code is using the strong-motion toolkit (now within the oq-mbtk) to generate expected ground-motions using the inputs provided in the attached metadata (stored in the .pkl file). 

 

When I manually set these site vs30 values to 1499 m/s, the error does not occur. If vs30 is 1500 m/s or greater, the error in my original screenshot is produced. Furthermore, in this example script, the error is:

 

ValueError: NumPy boolean array indexing assignment cannot assign 28 input values to the 27 output values where the mask is true

 

If you print the vs30 values, 27 of the vs30 values within this array will be greater than 1500 m/s. I think this is indicative of vs30 being the issue?

 

Thanks,

 

Chris
