### ISSUE TITLE
Add checks in job.ini file

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#8503]
It is possible to run calculations with job.ini files with duplicated fields (for example, `aggregate_by`), and the engine uses the latest value passed. Instead, an error should be raised.

**Comment by ptormene** [comment]
I've tried duplicating the definition of aggregate_by in the .ini of a test calculation, and when I run the calculation I get the following error:
```python
configparser.DuplicateOptionError: While reading from '/home/ptormene/GIT/oq-engine/openquake/qa_tests_data/event_based_risk/case_1/job_ins.ini' [line  7]: option 'aggregate_by' in section 'general' already exists
```
Can you provide an example in which this does not happen?

**Comment by ptormene** [comment]
Example provided by @CatalinaYepes:
```python
[general]
description = Stochastic Event-Based Demo with reinsurance (Nepal)
calculation_mode = event_based_risk
aggregate_by = id
ses_seed = 113
​
[erf]
width_of_mfd_bin = 0.5
rupture_mesh_spacing = 10
area_source_discretization = 10
​
[site_params]
site_model_file = site_model.csv
​
[vulnerability]
structural_vulnerability_file = structural_vulnerability_model.xml
nonstructural_vulnerability_file = nonstructural_vulnerability_model.xml
​
[logic_trees]
source_model_logic_tree_file = source_model_logic_tree.xml
gsim_logic_tree_file = gmpe_logic_tree.xml
number_of_logic_tree_samples = 0
​
[hazard_calculation]
truncation_level = 3
investigation_time = 1000
maximum_distance = 200.0
ses_per_logic_tree_path = 1
minimum_intensity = 0.05
minimum_magnitude = 5.3
​
​
[exposure]
exposure_file = exposure_model.xml
​
[risk_calculation]
asset_hazard_distance = 20
aggregate_by = policy
reinsurance_file = {'structural+nonstructural': 'reinsurance.xml'}
total_losses = structural+nonstructural
​
[outputs]
avg_losses = true
quantiles = 0.15 0.85
risk_investigation_time = 1
```
The field `aggregate_by` is present both in the `general` and in the `risk_calculation` sections. Currently an error is raised only when a field is duplicated within the same section, whereas in the case above the latest value overrides the others silently.

**Comment by micheles** [comment]
I am reopening this issue. After thinking on it, printing a warning makes no sense: users never read warnings and the last value of the parameter will be taken. Instead an error should be raised, only in that way the users will recognize the problem.
