### ISSUE TITLE
Problem with executing the hazard file, for complex Fault Source

### ISSUE THREAD

**Issue by CatalinaCantone** [gem/oq-engine#8576]
When running the hazard file, there is an issue saying "missing 1 required positional argument: 'dtype' ". How can I solve it?

**Comment by micheles** [comment]
I win the price for worst bug report of the month. Please use the mailing list https://groups.google.com/u/1/g/openquake-users for this kind of questions and include the steps required to reproduce the error, i.e. send us the job.zip file obtained after giving the command `oq zip job.ini`.

**Comment by CatalinaCantone** [comment]
Now I understand, thanks for the information.
