### ISSUE TITLE
Error in openquake installation on p310

### ISSUE THREAD

**Issue by Shreyasvi91** [gem/oq-engine#8609]
I get the below error when testing a simple demo. It would be great if the latest version of OQ can be installed on p310 hazard account.
![Screenshot 2023-04-04 at 7 43 40 PM](https://user-images.githubusercontent.com/78085634/229842428-5179b780-b9d8-459f-982b-852e2283678d.png)

**Comment by micheles** [comment]
This is not the right place to report this kind of issues. You should use
https://gitlab.openquake.org/sysadmin/it-operations/-/issues
