### ISSUE TITLE
VS30 overwritten for all subsequent attenuation runs in SWISS GMPE's

### ISSUE THREAD

**Issue by JamesGaborVevo** [gem/oq-engine#8715]
In the Swiss GMPE's of ChiouYoungs2008SWISS01, CauzziFaccioli2008SWISS01, and AkkarBommer2010SWISS01, VS30 values are overwritten to a designated value by setting the values of the context numpy array ctx.vs30. 
This, however, overwrites the vs30 values for all subsequent attenuation runs. 
This was fixed in commit ebf1d47 for ZhaoEtAl2006AscSWISS05 but not in the aforementioned attenuations. 
A simple fix is to replicate the copy of ctx as in Zhao: https://github.com/gem/oq-engine/blob/4f10790e4d9d43dfe621c526a2dc6efff2986c3f/openquake/hazardlib/gsim/zhao_2006_swiss.py#L72-L79

**Comment by micheles** [comment]
Thanks for reporting the issue and please check if the pull request #8723 solves the issue.
