### ISSUE TITLE
Add FAQ for multiple single-user independent installations. 

### ISSUE THREAD

**Issue by vot4anto** [gem/oq-engine#8725]
Having independent installations is good to test difference from different version.
Single user installations must use different ports in order to be independent for dbserver.

Each installation must set on openquake.cfg the port for dbserver

[dbserver]
port = <some number different from 1908>

**Comment by micheles** [comment]
NB: multi-user installations could be done in the same way (different venvs, different ports) but are out of scope right now. The only difference is in the systemctl scripts (one would need to have different scripts).

**Comment by micheles** [comment]
NB: server installations use the port 1907 by default, which is different from user installations using the port 1908. This is on purpose to allow the installations to coexist (typical use case: you want to upgrade the engine and you do a user installation of the newest version for testing purposes before doing the real upgrade). This should be documented.
