### ISSUE TITLE
Kuehn Model Adjustment Calculation Bug

### ISSUE THREAD

**Issue by claudio525** [gem/oq-engine#8856]
This line in the Kuehn model (https://github.com/gem/oq-engine/blob/b0a5b94ad4dad625dee2023972ef007286325d72/openquake/hazardlib/gsim/kuehn_2020.py#L534) assumes that the model["R"] values and the corresponding adjustment values are in ascending order, i.e. last one corresponds to the maximum Rrup value. 
However this is not the case (see screenshot), which means that the incorrect adjustment factor is used when the rrup value exceeds the maximum model value of 1000km.
![image](https://github.com/gem/oq-engine/assets/45545396/349ee734-f284-47fd-bcc9-e218deb26d71)

This is can either be fixed by sorting the values upon loading or fixing the order in the hdf5 database. 

I have been working on updating this function so that it supports multiple magnitude values, currently it will crash on this line https://github.com/gem/oq-engine/blob/b0a5b94ad4dad625dee2023972ef007286325d72/openquake/hazardlib/gsim/kuehn_2020.py#L716 when ctx contains multiple different magnitude values
Planning on making a PR for that which would also fix this issue, but figured I'd make an issue for this so it doesn't get lost.

**Comment by micheles** [comment]
Thank you very much for making this point. I would suggest you to make immediately a pull request fixing the ordering issue in`_retrieve_sigma_mu_data` and then a second on with the new feature.
