### ISSUE TITLE
include fix in 16.5

### ISSUE THREAD

**Issue by schmidni** [gem/oq-engine#8876]
I would be very glad if 7f2aa780b0bae97138016c6c77e1e2ee38539b88 could be included in the next patch version of v3.16 since we're trying to stay on the LTS version for our current products and this bug is sporadically breaking our automatic calculations.

**Comment by micheles** [comment]
Staying with LTS release is a very bad plan, if I may say so. You are power users, you always need the latest features, you don't want to keep using the engine of two years ago. You have strong reasons to use the latest version instead.

For instance today we released version 3.17 which has better support for shakemaps, including https://github.com/gem/oq-engine/commit/7f2aa780b0bae97138016c6c77e1e2ee38539b88. In a few months we will release version 3.18 with support for HPC clusters and you will want that.

**Comment by schmidni** [comment]
Dear Michele, of course we will keep doing new developments on the most recent version of OpenQuake. But we are finalizing a software which we would like to keep on the LTS for its current major version, but the bug of 7f2aa780b0bae97138016c6c77e1e2ee38539b88 is breaking it in some cases.

Not complaining, but oq usually breaks and changes so many things from one version to another (especially if you're a power user), that it is very time consuming and "dangerous" to update to a new version since you need to find all the relevant changes, adapt to them, fix edge-cases and deal with bugs. 

I don't see why 7f2aa780b0bae97138016c6c77e1e2ee38539b88 can't be included in the LTS version, since it is clearly a very isolated bugfix. Otherwise I need to do some tedious work in the CI/CD pipeline to always cherry pick that commit....

**Comment by micheles** [comment]
Backported today; it will be part of 3.16.7
