### ISSUE TITLE
When `LOCKDOWN == True`, tools are hidden but reachable and IPT is broken

### ISSUE THREAD

**Issue by ptormene** [gem/oq-engine#8893]
### Current situation
The `Tools` button in the WebUI homepage is visible if the setting `TEMPLATES[0]['OPTIONS']['context_processors']` contains `openquakeplatform.utils.oq_context_processor`.
If `LOCKDOWN == True`, the `TEMPLATES` dict is entirely redefined without reinserting that context processor.
However, tools remain reachable by requesting the corresponding urls. With `LOCKDOWN == True`, IPT is broken, because the call to `get_available_gsims` returns a 403. The other tools work regardless from the value of `LOCKDOWN`.
Our initial investigation on the IPT issue was not sufficient to identify the actual cause of the problem, nor to find a solution.

#### Note about the installer
The current installer always installs tools, regardless from the application mode. For instance, in the AELO machine we uninstalled the tools afterwards, to avoid confusion.

### How to make the `Tools` button available
The following changes make the `Tools` button visible, but do not fix the issue that occurs in IPT when `LOCKDOWN == True`
```diff
diff --git a/openquake/server/settings.py b/openquake/server/settings.py
index b2ed55908c..14feccb676 100644
--- a/openquake/server/settings.py
+++ b/openquake/server/settings.py
@@ -192,10 +192,6 @@ if STANDALONE and WEBUI:
 
     FILE_PATH_FIELD_DIRECTORY = datastore.get_datadir()
 
-    CONTEXT_PROCESSORS = TEMPLATES[0]['OPTIONS']['context_processors']
-    CONTEXT_PROCESSORS.insert(0, 'django.template.context_processors.request')
-    CONTEXT_PROCESSORS.append('openquakeplatform.utils.oq_context_processor')
-
 try:
     # Try to load a local_settings.py from the current folder; this is useful
     # when packages are used. A custom local_settings.py can be placed in
@@ -305,13 +301,13 @@ if LOCKDOWN:
             'APP_DIRS': True,
             'OPTIONS': {
                 'context_processors': [
+                    'django.template.context_processors.request',
                     'django.contrib.auth.context_processors.auth',
                     'django.template.context_processors.debug',
                     'django.template.context_processors.i18n',
                     'django.template.context_processors.media',
                     'django.template.context_processors.static',
                     'django.template.context_processors.tz',
-                    'django.template.context_processors.request',
                     'django.contrib.messages.context_processors.messages',
                     'openquake.server.utils.oq_server_context_processor',
                 ],
@@ -337,3 +333,9 @@ if LOCKDOWN:
         {'NAME': 'django.contrib.auth.password_validation.'
                  'NumericPasswordValidator', },
     ]
+
+    # OpenQuake Standalone tools (IPT, Taxtweb, Taxonomy Glossary)
+    if STANDALONE and WEBUI:
+        CONTEXT_PROCESSORS = TEMPLATES[0]['OPTIONS']['context_processors']
+        CONTEXT_PROCESSORS.append(
+            'openquakeplatform.utils.oq_context_processor')
```

**Comment by pslh** [comment]
My thoughts regarding the desired behaviour in different cases:

- The tools do not make sense in AELO mode (regardless of the value LOCKDOWN), and so should not be visible and probably should not be installed at all.  
- When installed for a single user, all the tools should be accessible without a password
- The tools are potentially useful but not essential in a multi-user environment:
  - Taxonomy Glossary and TaxtWeb should be available and does not need to be password protected
  - Password protection makes more sense for IPT to prevent abuse (uploading large files), and perhaps for accessing the engine for e.g. the list of GSIMS
  - Perhaps it should be possible to decide at installation time whether to install the tools or not, or perhaps the tools could be optionally installed (and configured) as an optional second install step 

Obviously if we permit the various options we need to expand our tests to cover all supported options.

**Comment by micheles** [comment]
Is this solved and should be closed?
