### ISSUE TITLE
Add parameter `maximum_distance_stations` when conditioning the gmfs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#8935]
Currently the engine includes the parameter `maximum_distance` which filters out hazard sites and observations located further than the specified distance.

It will be nice to filter the observations independently by introducing a new parameter, for example, `maximum_distance_stations`. In this way, the user has the possibility to include, or not, stations that might not be relevant to the conditioning of the shaking.

NOTE: The site collection for hazard calculations should include the locations of the stations within the specified maximum distance. See https://github.com/gem/oq-engine/issues/8930#issuecomment-1669762577

**Comment by micheles** [comment]
I don't like to complicate the `maximum_distance` logic, which is already rather complex. Since the bug in #8930 has been fixed, I would close this issue, if you don't mind.
