### ISSUE TITLE
Improve tests for all operating systems

### ISSUE THREAD

**Issue by ptormene** [gem/oq-engine#8936]
We need actions running all demos and all tests on all operating systems and supported python versions. Although it might be acceptable to keep a minimal coverage in daily schedules, we definitely need to run full tests at least before releasing any new version of the engine.
If we expect some tests to fail in some specific cases, we need not to just skip them, but to add a clear comment explaining why we are skipping them.

Currently it is not obvious why we are running demos using different parameters for those that only have a job.ini with respect to those divided into a job_hazard.ini and a job_risk.ini (e.g. `--exports xml,hdf5 -p pointsource_distance=0 -r` versus `--exports npz -p pointsource_distance=0 ` for the hazard and nothing for the risk.

It would be useful to try downloading all outputs after completing each demo (not just downloading the outputs that are available, but checking with respect to a list of expected outputs).

**Comment by micheles** [comment]
Can we close this as done?

**Comment by ptormene** [comment]
We are now running all demos and tests also on Windows and MacOS (see https://github.com/gem/oq-engine/pull/8970 and 
https://github.com/gem/oq-engine/pull/8924)
