### ISSUE TITLE
Handle confusion between `occupants` and `residents` losses (fatalities, injuries, homeless)

### ISSUE THREAD

**Issue by nicolepaul** [gem/oq-engine#8976]
# Overview

It seems to be that there is a lot of inconsistency with how we treat `occupants` and `residents` losses. There are some cases where we are using the incorrect field. For example:

- Casualty (i.e., fatalities, injuries) calculations should use `occupants_avg` unless a `time_period` is indicated, in which case `occupants_<time_period>` should be used
- Homeless calculations should use `residents`  (see https://github.com/gem/oq-engine/issues/8966)

# Explanation

## Casualties (fatalities, injuries) using `occupants`

For the case of casualties (fatalities, injuries), we care about the number of `occupants` in the building at the time of the earthquake.  For example, let's consider a person that lives in a highly vulnerable residence, but works a 9-5 job in a resilient office building. If the earthquake occurs at 2am and their house collapses, they are likely to be injured or killed. However, if the earthquake occurs at 11am and their office building experiences little damage, they are unlikely to be injured or killed. Moreover, if the earthquake occurs at 8:30am, they are likely to be transiting to their job and may be outdoors.

For a **scenario_damage** or **scenario_risk** calculation, we are likely to know the `time_period` of the earthquake. As such, we will se the parameter in the job configuration (e.g., `time_period=night` for the 2am earthquake, `time_period=day` for the 11am earthquake, and `time_period=transit` for the 8:30am earthquake). When `time_period` is specified, we should use that for the occupants risk calculations. This way we use the relevant occupant count for that time of earthquake.

For an **event_based_damage** or **event_based_risk** calculation, the earthquake is equally likely to happen at any time of day (day, night, or transit). Therefore, it makes sense to use the time-averaged occupants of the buildings (`occupants_avg`). In this way, we account for the fact that sometimes people are in their residence, in their workplace, visiting other building types (e.g., shops, schools), or are outdoors. If we assumed _all_ earthquakes were at night, we would likely overestimate our risk (as residences tend to be more fragile than other building types). Alternatively, if we assumed _all_ earthquakes happened during transit hours, we would likely underestimate our risk.

## Homeless using `residents`

In contrast to casualty calculations, we don't care whether the normal inhabitants (`residents`) of a given residence are actively occupying their home (or some other building type) during the time of the earthquake. If their home is damaged such that it is uninhabitable, it doesn't matter if they are in the home, at their workplace, or even on vacation. Because their home has been damaged such that it is uninhabitable, they are considered to be rendered homeless. We do not need to use any time-based calculations here.

Before we introduced the `residents` loss type, it was a common assumption to assume `residents` == `occupants_night`. However, we no longer need to make this assumption. If we were to assume this, we would likely underestimate our risk slightly as <100% of residents are in their homes at night.

# Suggested actions

I suggest we do two things:

- Resolve the confusion between occupants (and their associated time periods) and residents loss types
- Add new tests to explicitly confirm these calculations are as expected

In summary, we should have:

- Homeless calculations _always_ use the `residents` field
- Fatality and injury calculations use the relevant `occupants` field
    - `occupants_<time_period>` if a `time_period` is specified in the job configuration (scenario calculations)
    - `occupants_avg` otherwise

**Comment by raoanirudh** [comment]
- [ ] Homeless calculations _always_ use the `residents` field
- [ ] Fatality and injury calculations use the relevant `occupants` field
    - `occupants_<time_period>` if a `time_period` is specified in the job configuration (scenario calculations)
    - `occupants_avg` otherwise

@nicolepaul can you confirm that at least the first item is resolved by #8972?

**Comment by ptormene** [comment]
I assume with `time_period` @nicolepaul means the existing `time_event` parameter, that is `avg` by default, so we can always use `occupants_<time_event>`.

**Comment by nicolepaul** [comment]
> * [ ]  Homeless calculations _always_ use the `residents` field
> * [ ]  Fatality and injury calculations use the relevant `occupants` field
>   
>   * `occupants_<time_period>` if a `time_period` is specified in the job configuration (scenario calculations)
>   * `occupants_avg` otherwise
> 
> @nicolepaul can you confirm that at least the first item is resolved by #8972?

Yes, LGTM.

**Comment by nicolepaul** [comment]
I am including some test cases and their expected output here.

- **scenario_damage**
    - [case_16a.zip](https://github.com/gem/oq-engine/files/12524240/case_16a.zip)
    - [case_16b.zip](https://github.com/gem/oq-engine/files/12524241/case_16b.zip)
- **scenario_risk**
    - [case_11.zip](https://github.com/gem/oq-engine/files/12524239/case_11.zip)
