### ISSUE TITLE
Bug: scenario RISK calculations when conditioning gmfs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#9003]
Scenario risk calculations can be run in two ways:

1. Using two job files: one for generating the gmfs (job_hazard.ini) and later running risk using the precomputed hazard footprints (job_risk.ini)
2. Using a single file that includes the hazard and risk parameters for the configuration file

This is wrong for calculations using a single job file, since only 1 gmf is produced, instead of the number indicated in the job.ini.
The risk numbers generated are completely wrong.

**Comment by micheles** [comment]
The conditioned GMFs calculator was meant to work correctly only for `number_of_ground_motion_fields=1`. Extending it to more simulations require some work to improve its performance, which I am doing as part of this issue.
