### ISSUE TITLE
Pandas ImportError

### ISSUE THREAD

**Issue by cossatot** [gem/oq-engine#9007]
I just rebuilt my python environment (python 3.10, linux) and got this error when trying to start the dbserver:

```python
File "/home/itchy/src/gem/oq-engine/openquake/commands/run.py", line 25, in <module>
    from pandas.core.common import SettingWithCopyWarning
ImportError: cannot import name 'SettingWithCopyWarning' from 'pandas.core.common' (/home/itchy/src/miniconda/envs/oq/lib/python3.10/site-packages/pandas/core/common.py)
```

Pandas is version 2.1.0; that error has either been removed or moved to a different place in the codebase.

I'm submitting a quick-fix PR for this as well.

**Comment by micheles** [comment]
You have to wait for this to become green: https://github.com/gem/oq-engine/pull/9014
