### ISSUE TITLE
First location of event-based runs are incorrectly allocated random variables by GMPE

### ISSUE THREAD

**Issue by JamesGaborVevo** [gem/oq-engine#9073]
This bug was discovered while comparing classical to event-based runs where the POE in the first location was consistently lower for event-based.

We have found a bug where the first location of the first (alphabetical) IMT has truncated normal values generated incorrectly. This applies only to the first location and occurs in event-based runs with number_of_logic_tree_samples set to zero. The result is that the truncated normal values applied to a mean and standard deviation are actually partitioned along the normal curve according to GMPE.

The bug occurs because the seed set for the allocation of realisations (linked to GMPE) to events is the _same seed_ as that set in the generation of truncated normal values for the mean. This seed, linked to the actual rupture, is set just before the generation of random variables to apply to the mean and standard deviations: https://github.com/gem/oq-engine/blob/c0420220f8d0d39be448317ecd749471635c699a/openquake/hazardlib/calc/gmf.py#L218-L223

This same rupture seed is also used to allocate realisations to events (in self.seed on line 775):
https://github.com/gem/oq-engine/blob/c0420220f8d0d39be448317ecd749471635c699a/openquake/hazardlib/source/rupture.py#L759-L775

The issue is that the function **general.random_choice(.)** randomly samples from the array of realisations - which importantly is not random but ordered by GMPE for number_of_logic_tree_samples=0 - by using a uniform random variable. This exact same uniform random variable will be generated in the sampling of a truncated normal variable as both use the same underlying numpy random number system. Since the first random uniform variable drawn is the same as that which distributed the realisations, the distance along the truncated normal curve will correspond to the same distance along the array of realisations (sorted in alphabetical order of GMPE). Note here that numpy uses a polar box-muller approach to generating truncated normal variables, meaning atleast 2 uniform variables are drawn. These additional uniform variables account for the noise in the attached plots – had numpy used a normal generation method requiring only a single uniform variable (ie. Inverse transform) then the truncated variables would exhibit no noise and fall exactly within the GMPE bands allocated by realisation id.

The issue is best illustrated by printing out the random values generated for the first location:
https://github.com/gem/oq-engine/blob/c0420220f8d0d39be448317ecd749471635c699a/openquake/hazardlib/calc/gmf.py#L222-L223
https://github.com/gem/oq-engine/blob/c0420220f8d0d39be448317ecd749471635c699a/openquake/hazardlib/source/rupture.py#L759-L775

We did this on a run with 7 GMPEs on large sources (so the number of occurrences for each rupture was typically one) and plotted the histograms of the random numbers generated _partitioned by GMPE_ for the first location:
![image](https://github.com/gem/oq-engine/assets/30425961/5ed4aa86-9bb3-4665-b82c-dca5afdec949)

In this example, Allen2012 uses a left partition of the distribution, with each GMPE using an incrementing partition of the curve moving left to right as they are in alphabetical order. The impact will vary depending on the differences in mean and standard deviation intensity of GMPES. For our runs, where the standard deviation of Allen2012 is high, we found the first location to be consistently 10% lower than it should have been relative to other locations. It could be that this was never noticed because other GMPEs may not lead to this bias or a bias in the other direction.

Two more plots are attached below showing a scatterplot of random values partitioned by GMPE for location 0 and location 1:

![image](https://github.com/gem/oq-engine/assets/30425961/80c28ceb-96a5-4521-bd64-03fd3d2ddd50)

![image](https://github.com/gem/oq-engine/assets/30425961/667ddff5-9c3f-4e4b-bdce-b9cd208b5554)

The solution requires the distribution of realisations to events to be generated by an independent seed unrelated to the seed which generates the truncated normal variables. This can be easily done in:
https://github.com/gem/oq-engine/blob/c0420220f8d0d39be448317ecd749471635c699a/openquake/hazardlib/source/rupture.py#L774
by passing in a randomly generated seed in the sampling of realisations, rather than the rupture seed.

**Comment by micheles** [comment]
Congratulations for the analysis since it looks like it was really hard to figure this out. We would never have discovered this bug since we exclusively use sampling and never full enumeration in the global risk model calculations. I will have to discuss with the scientific staff about how to proceed for the fix, in particular for the LTS release engine-3.16, while for current master I don't see any problem.
