### ISSUE TITLE
issue in installing the development version

### ISSUE THREAD

**Issue by karimtarbali** [gem/oq-engine#9117]
Dear OQ team, 
I was trying to install OQ on my mac using "openquake-setup-macos-3.7.1-3.run", but got errors ending with "OSError: Could not find lib c or load any of its variants [].". Googling this error gave an indication to me that installing from the development package would solve the issue. Now i get the error below when trying to install the development version. Could you kindly let me know of your thoughts on how to resolve this issue. Thansk so much!

ERROR: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/gem/oq-engine/master/requirements-py311-macos_x86_64.txt
Traceback (most recent call last):
  File "/Users/kt/Academic/20_openquake/software_install/2_approach2_InstallFromSRC/src/src/oq-engine/install.py", line 556, in <module>
    install(inst, args.version, args.repository)
  File "/Users/kt/Academic/20_openquake/software_install/2_approach2_InstallFromSRC/src/src/oq-engine/install.py", line 401, in install
    subprocess.check_call(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/kt/openquake/bin/python3', '-m', 'pip', 'install', '--trusted-host', 'wheelhouse.openquake.org', '--trusted-host', 'raw.githubusercontent.com', '-r', 'https://raw.githubusercontent.com/gem/oq-engine/master/requirements-py311-macos_x86_64.txt']' returned non-zero exit status 1.

**Comment by vot4anto** [comment]
Hi @karimtarbali thanks to contact us.
Please follow this guide to install OpenQuake on MacOS because the .run method are now not supported 
https://github.com/gem/oq-engine/blob/master/doc/installing/universal.md.

Note that on MacOS we support only if you're on macOS 12.x or MacOS 13.x and use python3.10.

**Comment by karimtarbali** [comment]
Thanks for your reply!
now that I follow the universal installation approach, I get this error when running the command via "python3.10 install.py user". I would appreciate your thoughts on how to resolve this. Thanks

ERROR: pandas-1.3.5-cp310-cp310-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
Traceback (most recent call last):
  File "/Users/kt/Academic/20_openquake/install.py", line 557, in <module>
    install(inst, args.version, args.repository)
  File "/Users/kt/Academic/20_openquake/install.py", line 408, in install
    subprocess.check_call(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/kt/openquake/bin/python3', '-m', 'pip', 'install', '--trusted-host', 'wheelhouse.openquake.org', '--trusted-host', 'raw.githubusercontent.com', '-r', 'https://raw.githubusercontent.com/gem/oq-engine/v3.17.1/requirements-py310-macos_x86_64.txt']' returned non-zero exit status 1.

**Comment by vot4anto** [comment]
Please as you can read on the previous page:

**Comment by karimtarbali** [comment]
Thanks for your reply!
I am using python3.10 installations from python.org. and this is how terminal outputs look like:


(base) cygne:20_openquake kt$ python3.10 install.py user
Looking in links: /var/folders/bk/gwddfdx9507bh2dt95z_7ymm0000gn/T/tmpedackxql
Requirement already satisfied: pip in /Users/kt/openquake/lib/python3.12/site-packages (23.3)
Requirement already satisfied: pip in /Users/kt/openquake/lib/python3.12/site-packages (23.3)
Requirement already satisfied: wheel in /Users/kt/openquake/lib/python3.12/site-packages (0.41.2)
ERROR: pandas-1.3.5-cp310-cp310-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
Traceback (most recent call last):
  File "/Users/kt/Academic/20_openquake/install.py", line 557, in <module>
    install(inst, args.version, args.repository)
  File "/Users/kt/Academic/20_openquake/install.py", line 408, in install
    subprocess.check_call(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/kt/openquake/bin/python3', '-m', 'pip', 'install', '--trusted-host', 'wheelhouse.openquake.org', '--trusted-host', 'raw.githubusercontent.com', '-r', 'https://raw.githubusercontent.com/gem/oq-engine/v3.17.1/requirements-py310-macos_x86_64.txt']' returned non-zero exit status 1.
(base) cygne:20_openquake kt$

**Comment by vot4anto** [comment]
I am sorry but something is not good on your system.
