### ISSUE TITLE
Empty rows in extract ruptures

### ISSUE THREAD

**Issue by CB-quakemodel** [gem/oq-engine#9133]
When extracting ruptures from a datastore empty rows occur. These result in errors when using the extracted rupture csvs in a scenario calculation (deleting these blank rows enables the calculation to run). Attached is a screenshot of the extracted rupture csv from the ScenarioCase1 job in the Hazard demos, with the empty rows. 
![image](https://github.com/gem/oq-engine/assets/119606956/0d120019-b58b-4781-b104-290fd9061c23)

And here is the error generated if using the extracted rupture csv in the same hazard calculation instead of the equivalent rupture xml provided in the demo.

![image](https://github.com/gem/oq-engine/assets/119606956/f7f8a448-62a0-4d9e-8671-228ff971663d)

**Comment by raoanirudh** [comment]
Also reported recently on the forum: https://groups.google.com/g/openquake-users/c/zRqpI4z8Jus/m/RxPd6nohAQAJ

@CB-quakemodel can you check if you see the blank rows even if you open a freshly exported ruptures csv file in a plain text editor (i.e., before opening it in Excel, to make sure it's not Excel that's adding the blank lines on saving)?

**Comment by CB-quakemodel** [comment]
![image](https://github.com/gem/oq-engine/assets/119606956/a5cd323d-5b5d-4352-bb4a-436ba03e86ce)
This is for a different rupture, but confirms the issue is not excel adding the blank lines.
