### ISSUE TITLE
alpha_shapes missing from install configuration

### ISSUE THREAD

**Issue by khaynie-usgs** [gem/oq-engine#9258]
It looks like alpha_shapes is missing from the install configuration. I am getting a `No module named alpha_shapes` error from openquake.hazardlib when trying to import `from alpha_shapes import Alpha_Shaper`

**Comment by cbworden-usgs** [comment]
Specifically, the offending import is in hazardlib/geo/mesh.py, line 28. The problem happens when hazardlib is used after a pip install of openquake.engine.

**Comment by micheles** [comment]
NEVER DO a blind pip install of the engine! Use the universal installer or first install the requirements file.

**Comment by cbworden-usgs** [comment]
So you're telling me that you have an *intentionally* broken pip package to force people to use an installer. That makes absolutely no sense whatsoever. Pip packages are supposed to be standalone entities and you can specify whatever versions of dependencies you want in your setup. Whatever. All we care about is hazardlib, so we're going to keep doing what we're doing and we'll just add any dependencies that you intentionally omit to our install.

**Comment by cbworden-usgs** [comment]
Yes, we've recently been going through something similar with ShakeMap. The main package still has an installer to create a basic environment, but almost everything else has been spun off into two pip installable libs. The libs are standalone (well, one depends on the other), and install their own dependencies. Then the main package installer installs the env, the libs, and anything tricky. FWIW, if you don't need the GDAL CLI, you can just use rasterio, which is a much easier install (pip).

**Comment by micheles** [comment]
> FWIW, if you don't need the GDAL CLI, you can just use rasterio

We *HATE* GDAL, it is the hazard team that forced it on us, it is you guys that use it! {lease ask the others in your group why they don't use rasterio ;-)
