### ISSUE TITLE
Unable to locate the startup path for the DbServer in oq engine

### ISSUE THREAD

**Issue by Grant33Hu** [gem/oq-engine#9325]
After executing "oq engine --run /path/to/job.ini," an error occurs stating, "Please start the DbServer: see the documentation for details." Due to version issues, I cannot find the startup path for the database, even after re-cloning..

**Comment by micheles** [comment]
You should use the mailing list for support questions, GitHub should be used only for bugs.

**Comment by Grant33Hu** [comment]
Sure, thank you! I appreciate your assistance.
