### ISSUE TITLE
Parallelization in liquefaction analysis

### ISSUE THREAD

**Issue by LanaTodorovic93** [gem/oq-engine#9351]
As @micheles suggested, I am describing the issue here (although this is not an issue, but rather a curiosity on how the parallelization works).

So, I am running some liquefaction analyses on horn (branch: fix-liquefaction ) using two different liquefaction models, one parametric (job) and one nonparametric (job_np). I am running event-based calculations, and there is a massive difference in the times required to complete the analyses using different models. Some notes:
I am using the same SSM
same logic trees
same distance filters
same min Mag

And I end up having the same number of events. I have noticed in the log files that the number of tasks increases when I use the nonparametric model, while it remains the same when I use the parametric model (see logs).

As @raoanirudh already mentioned, I am using her personal engine installation on a horn that Antonio made for me and not the systemwide installation: `source /home/ltodorovic/openquake/bin/activate`. 

I am attaching here the job files and the log files.

Thanks!
[job.zip](https://github.com/gem/oq-engine/files/13947324/job.zip)
[job_np.zip](https://github.com/gem/oq-engine/files/13947326/job_np.zip)
[log_227.txt](https://github.com/gem/oq-engine/files/13947330/log_227.txt)
[log_230.txt](https://github.com/gem/oq-engine/files/13947331/log_230.txt)

**Comment by LanaTodorovic93** [comment]
The same issue persists in the current master `commit: 50f208a`. I am attaching the log of the `job_np` where this can be observed (this time, I killed the calculation).


[log_calc_id_48459.txt](https://github.com/gem/oq-engine/files/13949204/log_calc_id_48459.txt)

**Comment by micheles** [comment]
@raoanirudh found the reason for the generation of many tasks: heavier calculations produce more tasks.
