### ISSUE TITLE
In rare cases, output coordinates are rounded differently depending way of specifying site

### ISSUE THREAD

**Issue by kejohnso** [gem/oq-engine#9454]
In extremely rare cases, the means of specifying a site is changing the coordinates that are listed in output files. 
This was discovered for the site `123.300795,9.510590`. 

If the site is directly specified in the job file: 
`sites = 123.300795 9.510590` 
The output longitude is rounded down incorrectly: 
`lon,lat`
`123.30079,9.51059`

On the other hand if the site is specified as inside a csv file:
`site_model_file = sites_2.csv` or `sites_csv = sites_2.csv` 
The rounding is correct:
`lon,lat`
`123.30080,9.51059`

If the site is changed to `123.300695,9.510590` the bug disappears. 

See the attached test jobs. 

[output_coords_example.zip](https://github.com/gem/oq-engine/files/14297366/output_coords_example.zip)

**Comment by micheles** [comment]
Looks like the numpy rounding is inconsistent with python rounding:
```python
>>> numpy.round( 123.300795, 5)
123.3008
>>> round( 123.300795, 5)
123.30079
```
Quite surprising, if I may say so.
