### ISSUE TITLE
BCHydroESHM20 Logic Tree Issue

### ISSUE THREAD

**Issue by elifyild** [gem/oq-engine#9486]
In BCHydroESHM20SInter and BCHydroESHM20SSlab gmm logic trees, the variable theta_6_adjustment is not correctly referenced as it appears in the code.  Thus, it is not working and it should affects the median value derived from gmm branch. It is written in the code as theta6_adjustment. 
Related codes are in below: 

Logic tree: https://github.com/gem/oq-engine/blob/d197c4170d753f9cd22a1e9d5013e8d20bccfbbd/openquake/qa_tests_data/mosaic/EUR/in/gmmLT.xml#L844 

Abrahamson 2015 code: https://github.com/gem/oq-engine/blob/d197c4170d753f9cd22a1e9d5013e8d20bccfbbd/openquake/hazardlib/gsim/abrahamson_2015.py#L290

**Comment by micheles** [comment]
It is easier to change the code than the model, so I would do that.

**Comment by micheles** [comment]
Closing because it is an issue on the gsim logic tree file and not on the engine side. We will make a new release of the EUR model soon.
