### ISSUE TITLE
Anaconda, Python=3.11.8 Openquake 3.19 Installation Error

### ISSUE THREAD

**Issue by NimaDolatabadi** [gem/oq-engine#9517]
when Runing openquake.engine to install version 3.19, I get these errors
```
ModuleNotFoundError: No module named 'numba'
ModuleNotFoundError: No module named 'fiona'
ModuleNotFoundError: No module named 'networkx'
```

simply installing them would do the job but you know if you are release a package it must be installed flawlessly.

Regards

**Comment by micheles** [comment]
It installs flawlessly if you use pip. Anaconda is NOT supported by the engine team.
