### ISSUE TITLE
multifaultsource sanity check breaks fault section prefix

### ISSUE THREAD

**Issue by chrisdicaprio** [gem/oq-engine#9534]
The NZ NSHM multfault sources use a text string prefix to the section id so that users can combine multiple source files (from different fault systems) without the fault section ids clashing. However, the [id sanity check](https://github.com/gem/oq-engine/blob/c3184cde5941e50b4917f27d0c9cb7dc6add5df2/openquake/hazardlib/sourceconverter.py#L1148-L1149) assumes indices can be cast to U32 
```
                for idx in idxs:
                    assert U32(idx).max() < TWO16, idx
```

The result is an error such as this:
```
File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/hazardlib/sourceconverter.py", line 1149, in convert_multiFaultSource
    assert U32(idx).max() < TWO16, idx
ValueError: node multiFaultSource: invalid literal for int() with base 10: 'U2NhbGVkSW52ZXJzaW9uU29sdXRpb246MTE0MjAw0', line 15 of /home/chrisdc/NSHM/oqruns/EGL_disagg/Disagg_Branch1/sources/U2NhbGVkSW52ZXJzaW9uU29sdXRpb246MTE0MjAw-ruptures.xml
```

**Comment by micheles** [comment]
What happens if you just comment out the sanity check? Chances are that everything will work.

**Comment by chrisdicaprio** [comment]
@micheles yes, it works if those lines are commented out. I didn't submit at PR as I didn't know if you wanted to keep the sanity check and how it might be modified, if so
