### ISSUE TITLE
use of region_grid_spacing in a conditioned gmf produces a key error now

### ISSUE THREAD

**Issue by CB-quakemodel** [gem/oq-engine#9777]
It appears that using a grid spacing to ensure a GMF calculation is not too large now produces a key error if the GMF is being conditioned (please see attached screenshot). Adding a grid spacing of about 20 km (or any value I've tested) causes the attached calculation to fail.

[test.zip](https://github.com/user-attachments/files/15808765/test.zip)

Thanks,

Chris

![image](https://github.com/gem/oq-engine/assets/119606956/877726dc-e358-4ca7-8195-13755707a37e)

**Comment by micheles** [comment]
I do not get that KeyError, @CB-quakemodel 
Do you still get it with current master?

**Comment by CB-quakemodel** [comment]
Yes sorry, if the grid spacing is added the error is generated
