### ISSUE TITLE
Incorrect documentation for Afshari Stewart 2016

### ISSUE THREAD

**Issue by lispandfound** [gem/oq-engine#9793]
In the definition of the model we are told the required rupture parameters are magnitude and rupture depth.
https://github.com/gem/oq-engine/blob/08c79a3ba69c17a82cdb59d79aa43aa89777fa27/openquake/hazardlib/gsim/afshari_stewart_2016.py#L189
however, the actually required parameters are magnitude and rake:
https://github.com/gem/oq-engine/blob/08c79a3ba69c17a82cdb59d79aa43aa89777fa27/openquake/hazardlib/gsim/afshari_stewart_2016.py#L190

This documentation should be updated to reflect the parameters that are actually required.

**Comment by micheles** [comment]
Thanks for the report, this is now fixed.
