### ISSUE TITLE
multifault msparams issues

### ISSUE THREAD

**Issue by cossatot** [gem/oq-engine#9856]
We on the hazard team are having a few issues with the `msparams` attribute of the MultiFaultSources, in particular it not being automatically populated in certain instances:
1. When all of the sites are far away from all of the MultiFaultSources, the calculation fails. I am not sure what the threshold for 'far' is, perhaps the integration distance. Nonetheless this is an issue when, for example, we want to calculate hazard at a single site in a large model such as for AELO.
2. When extracting all ruptures in Hamlet, `source.iter_ruptures()` is run. (The source is loaded from the hdf5path, because if a multifault sources is passed directly from the preclassical calculator like the rest of the sources, `source.iter_ruptures()` fails with `KeyError: '0/rupture_idxs not found in calc_xxx_tmp.hdf5`, perhaps because the preclassical calculator does not save all the necessary information).

I realize that the `msparams` attribute makes the calculations much faster but there are use cases where speed is not important, but having the process not crash is actually quite critical.

cc @ManuelaVillani @mmpagani

**Comment by micheles** [comment]
I need an example exhibiting issue 1. For what concerns issue 2, it is quite important to perform the preclassical part of the calculation, since it is the part storing the multi-fault-sources in the right format in the datastore, otherwise .iter_ruptures() cannot work. In other words, Hamlet should contain code like the following:
```python
import logging
from openquake.commonlib import datastore
from openquake.engine.engine import create_jobs, run_jobs

if __name__ == '__main__':
    [job] = create_jobs(['/home/michele/mosaic/EUR/in/job.ini'])
    job.params['calculation_mode'] = 'preclassical'
    run_jobs([job])
    with job, datastore.read(job.calc_id) as dstore:
        sources = dstore["_csm"].get_sources()
        for src in sources:
            logging.info('processing %s', src)
            for rup in src.iter_ruptures():
                pass
```

**Comment by cossatot** [comment]
Thanks, @micheles. For problem 1, here is a .zip with a working job (`job.ini`) and non-working job (`job_bad.ini`) that differ only in the sites file used. 

[mf_test.zip](https://github.com/user-attachments/files/16414775/mf_test.zip)
