### ISSUE TITLE
acme_2019.py throws np.RankWarning error

### ISSUE THREAD

**Issue by subsurfaceiodev** [gem/oq-engine#9859]
Hi, currently using numpy 2.0.1 when running openquake engine related to acme_2019.py file. I was able to fix it by changing line 37 from:

`warnings.filterwarnings("ignore", category=np.RankWarning)`

to

`warnings.filterwarnings("ignore", category=np.exceptions.RankWarning)`

**Comment by micheles** [comment]
We provide requirement files with the right dependencies to use with the engine: see https://github.com/gem/oq-engine.
You can use newer versions at your risk and peril. In the future we will upgrade to numpy 2.0, but it will take several months.
