### ISSUE TITLE
Kotha 2020 files missing from pip install

### ISSUE THREAD

**Issue by cbworden-usgs** [gem/oq-engine#9905]
I have OQ 3.20.1 installed but when I run the Kotha2020regional gsim, I get an error message that the files in oq-engine/openquake/hazardlib/gsim/Kotha_2020/ are not found. The files, namely kotha_attenuation_regions.geojson and kotha_tectonic_regions.geojson, do not appear anywhere in the install. The other gsim's data directories appear to be there, but this one is missing.

**Comment by mmpagani** [comment]
The files are here: https://github.com/gem/oq-engine/tree/master/openquake/hazardlib/gsim/Kotha_2020 so I suppose it's an installation problem @micheles @antonioettorre
